"""Regime 2 — RAG Answer Quality Tests (LLM-as-judge).

Scores the quality of answers generated by the RAG pipeline.
Only runs in full-judge mode (nightly), not CI fast path.
"""

from __future__ import annotations

import pytest


@pytest.mark.regime2
@pytest.mark.network
@pytest.mark.slow
class TestAnswerQualityLive:
    """LLM-as-judge answer quality tests — requires Claude API."""

    @pytest.fixture(autouse=True)
    def _check_api(self):
        import os
        if not os.getenv("ANTHROPIC_API_KEY"):
            pytest.skip("Answer quality tests require ANTHROPIC_API_KEY")

    def test_placeholder(self):
        """Placeholder — activated when API key is available."""
        pass
