#!/usr/bin/env python3
"""
Emit three markdown matrices from electrical model YAMLs and SVG sheets.
Pure Python (stdlib + pyyaml); run with `py -3 emit_matrices.py`.
Deterministic output: sorted rows, no timestamps.
"""

import re
import sys
from collections import defaultdict
from pathlib import Path

try:
    import yaml
except ImportError:
    print("ERROR: pyyaml not found. Install with: pip install pyyaml", file=sys.stderr)
    sys.exit(1)

# Paths
SCRIPT_DIR = Path(__file__).parent
MODEL_DIR = SCRIPT_DIR / "model"
SHEETS_DIR = SCRIPT_DIR / "sheets"
REVIEW_DIR = SCRIPT_DIR / "review"

# Create review dir
REVIEW_DIR.mkdir(exist_ok=True)

HEADER = "Generated by emit_matrices.py — do not hand-edit; regenerate after any model change."

# ============================================================================
# Load all YAML files
# ============================================================================


def load_yaml(path):
    """Load YAML file; return {} if missing with warning."""
    if not path.exists():
        print(f"[WARN] {path.name} not found", file=sys.stderr)
        return {}
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f) or {}


devices_data = load_yaml(MODEL_DIR / "devices.yaml")
terminals_data = load_yaml(MODEL_DIR / "terminals.yaml")
wires_data = load_yaml(MODEL_DIR / "wires.yaml")
sheets_data = load_yaml(MODEL_DIR / "sheets.yaml")
open_items_data = load_yaml(MODEL_DIR / "open_items.yaml")
e007_data = load_yaml(MODEL_DIR / "e007_rs485.yaml")

# Normalize to lists
devices = devices_data.get("devices", [])
wires = wires_data.get("wires", [])
nodes_allowlist = wires_data.get("nodes", [])
e007_links = e007_data.get("links", [])
open_items = open_items_data.get("items", [])

# ============================================================================
# Parse SVG files to find data-wire attributes and dashing
# ============================================================================


def parse_svg_wires(svg_path):
    """
    Parse SVG and return dict: wire_label -> {'rendered': 'dashed'|'solid'|'absent', 'tagged': bool}
    Looks for data-wire attributes and checks for stroke-dasharray or data-dashed.
    """
    if not svg_path.exists():
        print(f"[WARN] {svg_path.name} not found", file=sys.stderr)
        return {}

    with open(svg_path, "r", encoding="utf-8") as f:
        content = f.read()

    # Find all XML elements containing data-wire attribute
    # Check if element also contains stroke-dasharray (dashed marker)
    result = {}

    # Match complete element tags: < ... data-wire="..." ... >
    for element_match in re.finditer(r'<[^>]*data-wire="([^"]+)"[^>]*>', content):
        wire_label = element_match.group(1)
        element = element_match.group(0)

        # Check if element contains stroke-dasharray or data-dashed
        is_dashed = "stroke-dasharray" in element or "data-dashed" in element

        result[wire_label] = {"rendered": "dashed" if is_dashed else "solid", "tagged": True}

    return result


svg_wires = {
    "E-003": parse_svg_wires(SHEETS_DIR / "E-003_vfd_power.svg"),
    "E-005": parse_svg_wires(SHEETS_DIR / "E-005_plc_inputs.svg"),
    "E-006": parse_svg_wires(SHEETS_DIR / "E-006_plc_outputs.svg"),
    "E-007": parse_svg_wires(SHEETS_DIR / "E-007_rs485_modbus.svg"),
}

# ============================================================================
# Build device & terminal lookup
# ============================================================================


def flatten_terminals():
    """Flatten terminals.yaml structure into a dict: 'TAG.TERMINAL_ID' -> terminal_data"""
    terminals_flat = {}

    for device_tag in terminals_data:
        if device_tag not in devices_data:
            # Create a dummy entry for devices in terminals but not devices.yaml
            pass

        device_terminals = terminals_data[device_tag]

        if isinstance(device_terminals, list):
            # Flat list (S0, SS1, S2, B1, etc.)
            for term in device_terminals:
                term_id = term.get("id", "?")
                key = f"{device_tag}.{term_id}"
                terminals_flat[key] = term
        elif isinstance(device_terminals, dict):
            # Nested structure (PLC1, VFD1, etc.)
            for section_name in device_terminals:
                section = device_terminals[section_name]
                if isinstance(section, list):
                    for term in section:
                        term_id = term.get("id", "?")
                        key = f"{device_tag}.{term_id}"
                        terminals_flat[key] = term

    return terminals_flat


terminals_flat = flatten_terminals()

# ============================================================================
# FILE 1: EVIDENCE_MATRIX.md
# ============================================================================


def build_evidence_matrix():
    """Build conductor-by-conductor evidence matrix, one table per sheet."""

    lines = [
        "# EVIDENCE MATRIX",
        "",
        f"> {HEADER}",
        "",
    ]

    # Process each sheet (E-003, E-005, E-006, E-007)
    for sheet_id in ["E-003", "E-005", "E-006"]:
        # Get wires for this sheet
        sheet_wires = [w for w in wires if w.get("sheet") == sheet_id]
        sheet_wires_sorted = sorted(sheet_wires, key=lambda x: x.get("proposed_number", ""))

        lines.append(f"## {sheet_id}")
        lines.append("")
        lines.append(
            "| Wire | From | To | Signal | Type | Status | Source | Notes | Rendered | Tagged |"
        )
        lines.append(
            "|------|------|----|---------|---------|----|--------|-------|----------|--------|"
        )

        verified_count = 0
        field_verify_count = 0
        proposed_count = 0
        missing_source_verified = 0
        rendered_solid_not_verified = 0

        for wire in sheet_wires_sorted:
            wire_num = wire.get("proposed_number", "?")
            from_ep = wire.get("from", "?")
            to_ep = wire.get("to", "?")
            signal = wire.get("signal", "")
            wire_type = wire.get("type", "")
            status = wire.get("status", "")
            source = wire.get("source", "")
            notes = wire.get("note", "")

            # Count statuses
            if status == "verified":
                verified_count += 1
                if not source:
                    missing_source_verified += 1
            elif status == "field_verify":
                field_verify_count += 1
            elif status == "proposed":
                proposed_count += 1

            # Check rendering (all renderers tag conductors with data-wire as of V3)
            svg_data = svg_wires.get(sheet_id, {}).get(wire_num)
            if svg_data:
                rendered = svg_data["rendered"]
                tagged = "yes"
                # Check for logic error: rendered solid but not verified
                if rendered == "solid" and status != "verified":
                    rendered_solid_not_verified += 1
            else:
                rendered = "absent"
                tagged = "no"

            lines.append(
                f"| {wire_num} | {from_ep} | {to_ep} | {signal} | {wire_type} | {status} | "
                f"{source[:20] if source else ''} | {notes[:30] if notes else ''} | {rendered} | {tagged} |"
            )

        lines.append("")
        lines.append("### SUMMARY")
        lines.append(f"- Total wires: {len(sheet_wires_sorted)}")
        lines.append(f"- Verified: {verified_count}")
        lines.append(f"- Field verify: {field_verify_count}")
        lines.append(f"- Proposed: {proposed_count}")
        if missing_source_verified > 0:
            lines.append(
                f"- **Verified wires missing source: {missing_source_verified}** (should be 0)"
            )
        if rendered_solid_not_verified > 0:
            lines.append(
                f"- **Rendered solid but not verified: {rendered_solid_not_verified}** (should be 0)"
            )
        lines.append("")

    # E-007 RS-485 links
    lines.append("## E-007 RS-485 / Modbus RTU")
    lines.append("")
    lines.append(
        "| Wire | From | To | Signal | Type | Status | Source | Notes | Rendered | Tagged |"
    )
    lines.append(
        "|------|------|----|---------|---------|----|--------|-------|----------|--------|"
    )

    e007_links_sorted = sorted(e007_links, key=lambda x: x.get("wire_label", ""))
    verified_count_e007 = 0
    field_verify_count_e007 = 0

    for link in e007_links_sorted:
        wire_label = link.get("wire_label", "?")
        src_device = link.get("src_device", "?")
        src_terminal = link.get("src_terminal", "?")
        dst_device = link.get("dst_device", "?")
        dst_terminal = link.get("dst_terminal", "?")
        from_ep = f"{src_device}.{src_terminal}"
        to_ep = f"{dst_device}.{dst_terminal}"
        signal = link.get("signal", "")
        cable = link.get("cable", "")
        wire_type = cable
        status = link.get("evidence", "")
        source = link.get("source", "")
        notes = link.get("notes", "")

        if status == "verified":
            verified_count_e007 += 1
        elif status == "field_verify":
            field_verify_count_e007 += 1

        svg_data = svg_wires.get("E-007", {}).get(wire_label)
        if svg_data:
            rendered = svg_data["rendered"]
            tagged = "yes"
        else:
            rendered = "absent"
            tagged = "no"

        lines.append(
            f"| {wire_label} | {from_ep} | {to_ep} | {signal} | {wire_type} | {status} | "
            f"{source[:20] if source else ''} | {notes[:30] if notes else ''} | {rendered} | {tagged} |"
        )

    lines.append("")
    lines.append("### SUMMARY")
    lines.append(f"- Total links: {len(e007_links_sorted)}")
    lines.append(f"- Verified: {verified_count_e007}")
    lines.append(f"- Field verify: {field_verify_count_e007}")
    lines.append("")

    return "\n".join(lines)


# ============================================================================
# FILE 2: CROSSREF_MATRIX.md
# ============================================================================


def build_crossref_matrix():
    """Build terminal and device cross-reference."""

    lines = [
        "# CROSSREF MATRIX",
        "",
        f"> {HEADER}",
        "",
    ]

    # Device table
    lines.append("## Devices")
    lines.append("")
    lines.append("| Tag | Type | Evidence | Role |")
    lines.append("|-----|------|----------|------|")

    devices_sorted = sorted(devices, key=lambda x: x.get("tag", ""))
    for device in devices_sorted:
        tag = device.get("tag", "?")
        dev_type = device.get("type", "")
        evidence = device.get("evidence", "")
        role = device.get("role", "")
        # Truncate role at 90 chars
        if len(role) > 90:
            role = role[:87] + "..."
        lines.append(f"| {tag} | {dev_type} | {evidence} | {role} |")

    lines.append("")

    # Terminal table
    lines.append("## Terminals")
    lines.append("")
    lines.append("| Device.Terminal | Function | Status | Wires Touching | Sheets |")
    lines.append("|---|---|---|---|---|")

    # Build wire endpoint index
    wire_endpoints = defaultdict(list)
    for wire in wires:
        from_ep = wire.get("from", "")
        to_ep = wire.get("to", "")
        sheet = wire.get("sheet", "")
        wire_num = wire.get("proposed_number", "?")

        # Only match endpoints that look like "TAG.TERMINAL"
        if "." in from_ep and from_ep not in nodes_allowlist:
            wire_endpoints[from_ep].append((wire_num, sheet))
        if "." in to_ep and to_ep not in nodes_allowlist:
            wire_endpoints[to_ep].append((wire_num, sheet))

    # Add E-007 endpoints
    for link in e007_links:
        src_device = link.get("src_device", "")
        src_terminal = link.get("src_terminal", "")
        dst_device = link.get("dst_device", "")
        dst_terminal = link.get("dst_terminal", "")
        wire_label = link.get("wire_label", "?")
        sheet = e007_data.get("sheet", "E-007")

        src_ep = f"{src_device}.{src_terminal}"
        dst_ep = f"{dst_device}.{dst_terminal}"

        wire_endpoints[src_ep].append((wire_label, sheet))
        wire_endpoints[dst_ep].append((wire_label, sheet))

    # Flatten and sort terminals
    terminals_sorted = sorted(terminals_flat.items())

    for term_key, term_data in terminals_sorted:
        function = term_data.get("function", "")
        status = term_data.get("status", "")
        touching = wire_endpoints.get(term_key, [])

        # Build wire list and sheet set
        if touching:
            wire_list = ", ".join(sorted(set(w[0] for w in touching)))
            sheet_set = sorted(set(w[1] for w in touching))
            sheets_str = ", ".join(sheet_set)
        else:
            wire_list = "—"
            sheets_str = "—"

        lines.append(f"| {term_key} | {function} | {status} | {wire_list} | {sheets_str} |")

    lines.append("")

    # Pseudo-nodes
    lines.append("## Pseudo-Nodes (Rails, Buses, Off-Sheet)")
    lines.append("")
    lines.append("| Node | Wires Touching |")
    lines.append("|------|--------|")

    node_wires = defaultdict(list)
    for wire in wires:
        from_ep = wire.get("from", "")
        to_ep = wire.get("to", "")
        wire_num = wire.get("proposed_number", "?")

        if from_ep in nodes_allowlist:
            node_wires[from_ep].append(wire_num)
        if to_ep in nodes_allowlist:
            node_wires[to_ep].append(wire_num)

    for node in sorted(nodes_allowlist):
        wires_touching = sorted(set(node_wires.get(node, [])))
        wire_list = ", ".join(wires_touching) if wires_touching else "—"
        lines.append(f"| {node} | {wire_list} |")

    lines.append("")

    # Orphans check
    lines.append("## Orphans (Unresolved Endpoints)")
    lines.append("")

    orphans = set()
    for wire in wires:
        from_ep = wire.get("from", "")
        to_ep = wire.get("to", "")

        # Check if from_ep is resolvable
        if not (from_ep in nodes_allowlist or from_ep in terminals_flat):
            orphans.add(from_ep)
        # Check if to_ep is resolvable
        if not (to_ep in nodes_allowlist or to_ep in terminals_flat):
            orphans.add(to_ep)

    if orphans:
        lines.append("**ALERT: Unresolved endpoints found:**")
        lines.append("")
        for orphan in sorted(orphans):
            lines.append(f"- {orphan}")
    else:
        lines.append("OK: No orphans (all endpoints resolved)")

    lines.append("")

    return "\n".join(lines)


# ============================================================================
# FILE 3: FIELD_VERIFY_LIST.md
# ============================================================================


def build_field_verify_list():
    """Build meter-check docket."""

    lines = [
        "# FIELD VERIFY LIST",
        "",
        f"> {HEADER}",
        "",
        "The docket of everything NOT yet verified. Every wire with status ≠ verified, "
        "and every terminal marked field_verify.",
        "",
    ]

    # Wires by sheet
    for sheet_id in ["E-003", "E-005", "E-006", "E-007"]:
        if sheet_id == "E-007":
            sheet_wires = e007_links
            key_field = "wire_label"
        else:
            sheet_wires = [w for w in wires if w.get("sheet") == sheet_id]
            key_field = "proposed_number"

        # Filter to non-verified
        to_verify = [
            w
            for w in sheet_wires
            if w.get("evidence" if sheet_id == "E-007" else "status") != "verified"
        ]
        to_verify_sorted = sorted(to_verify, key=lambda x: x.get(key_field, ""))

        if to_verify:
            lines.append(f"## {sheet_id} — Wires to Verify")
            lines.append("")

            for wire in to_verify_sorted:
                if sheet_id == "E-007":
                    wire_label = wire.get("wire_label", "?")
                    from_ep = f"{wire.get('src_device', '?')}.{wire.get('src_terminal', '?')}"
                    to_ep = f"{wire.get('dst_device', '?')}.{wire.get('dst_terminal', '?')}"
                    notes = wire.get("notes", "")
                    verify = notes if notes else "confirm conductor + endpoints"
                else:
                    wire_label = wire.get("proposed_number", "?")
                    from_ep = wire.get("from", "?")
                    to_ep = wire.get("to", "?")
                    notes = wire.get("note", "")
                    verify = notes if notes else "confirm conductor + endpoints + wire number"

                lines.append(f"- **{wire_label}**: {from_ep} → {to_ep}")
                lines.append(f"  - Verify: {verify}")
                lines.append("")

    # Field-verify terminals per sheet
    for sheet_id in ["E-003", "E-005", "E-006", "E-007"]:
        # Find devices on this sheet
        sheet_devices = set()
        for wire in wires:
            if wire.get("sheet") == sheet_id:
                from_ep = wire.get("from", "")
                to_ep = wire.get("to", "")
                if "." in from_ep:
                    sheet_devices.add(from_ep.split(".")[0])
                if "." in to_ep:
                    sheet_devices.add(to_ep.split(".")[0])

        if sheet_id == "E-007":
            for link in e007_links:
                sheet_devices.add(link.get("src_device", ""))
                sheet_devices.add(link.get("dst_device", ""))

        # Find field_verify terminals on these devices
        fv_terminals = []
        for term_key, term_data in terminals_flat.items():
            device_tag = term_key.split(".")[0]
            if device_tag in sheet_devices and term_data.get("status") == "field_verify":
                fv_terminals.append((term_key, term_data))

        if fv_terminals:
            lines.append(f"## {sheet_id} — Terminals to Verify")
            lines.append("")
            for term_key, term_data in sorted(fv_terminals):
                function = term_data.get("function", "")
                lines.append(f"- **{term_key}**: {function}")
                lines.append("")

    # Open items table
    lines.append("## Open Items")
    lines.append("")
    lines.append("| OI ID | Sheet | Item | Verify |")
    lines.append("|-------|-------|------|--------|")

    oi_sorted = sorted(open_items, key=lambda x: x.get("id", ""))
    for item in oi_sorted:
        oi_id = item.get("id", "?")
        sheet = item.get("sheet", "?")
        item_text = item.get("item", "")
        verify = item.get("verify", "")
        lines.append(
            f"| {oi_id} | {sheet} | {item_text[:50] if len(item_text) > 50 else item_text} | "
            f"{verify[:50] if len(verify) > 50 else verify} |"
        )

    lines.append("")

    # Summary counts
    fv_wires_count = sum(1 for w in wires if w.get("status") != "verified")
    fv_wires_count += sum(1 for link in e007_links if link.get("evidence") != "verified")
    fv_terminals_count = sum(
        1 for t in terminals_flat.values() if t.get("status") == "field_verify"
    )
    oi_count = len(open_items)

    lines.append("### Summary")
    lines.append(f"- Total field-verify wires: {fv_wires_count}")
    lines.append(f"- Total field-verify terminals: {fv_terminals_count}")
    lines.append(f"- Total open items: {oi_count}")
    lines.append("")

    return "\n".join(lines)


# ============================================================================
# Write files
# ============================================================================

try:
    evidence_matrix = build_evidence_matrix()
    crossref_matrix = build_crossref_matrix()
    field_verify_list = build_field_verify_list()

    evidence_path = REVIEW_DIR / "EVIDENCE_MATRIX.md"
    crossref_path = REVIEW_DIR / "CROSSREF_MATRIX.md"
    fv_path = REVIEW_DIR / "FIELD_VERIFY_LIST.md"

    with open(evidence_path, "w", encoding="utf-8") as f:
        f.write(evidence_matrix)
    with open(crossref_path, "w", encoding="utf-8") as f:
        f.write(crossref_matrix)
    with open(fv_path, "w", encoding="utf-8") as f:
        f.write(field_verify_list)

    print(f"[OK] {evidence_path}")
    print(f"[OK] {crossref_path}")
    print(f"[OK] {fv_path}")

    sys.exit(0)

except Exception as e:
    print(f"ERROR: {e}", file=sys.stderr)
    import traceback

    traceback.print_exc()
    sys.exit(1)
