#!/usr/bin/env python3
"""Write a markdown vault report from a list of Findings.

Usage:
  python3 write_report.py --host factorylm.com --findings-file /tmp/f.json \
                          --out /Users/factorylm/mira/wiki/reviews/2026-04-25-factorylm.com.md
"""
from __future__ import annotations

import argparse
import json
import sys
from collections import Counter
from datetime import date
from pathlib import Path

SEV_EMOJI = {"P0": "🔴", "P1": "🟠", "P2": "🟡", "P3": "🟢"}


def render(host: str, findings: list[dict]) -> str:
    counts = Counter(f["severity"] for f in findings)
    sources = Counter(f.get("source", "?") for f in findings)
    lines: list[str] = []
    lines.append(f"# Web Review — {host} — {date.today().isoformat()}")
    lines.append("")
    lines.append("## Summary")
    lines.append("")
    lines.append(f"- Total findings: **{len(findings)}**")
    for sev in ("P0", "P1", "P2", "P3"):
        if counts[sev]:
            lines.append(f"- {SEV_EMOJI[sev]} {sev}: {counts[sev]}")
    lines.append(f"- Sources: " + ", ".join(f"{s}={c}" for s, c in sources.most_common()))
    lines.append("")
    lines.append("## Findings (most obvious first)")
    lines.append("")
    lines.append("| # | Sev | Route | Title | Source | Evidence |")
    lines.append("|---|---|---|---|---|---|")
    for i, f in enumerate(findings, 1):
        evidence = (f.get("evidence", "") or "").replace("|", "\\|").replace("\n", " ")[:120]
        lines.append(
            f"| {i} | {SEV_EMOJI.get(f['severity'], '?')} {f['severity']} | "
            f"`{f.get('page','/')}` | {f.get('title','')} | "
            f"{f.get('source','?')} | {evidence} |"
        )
    lines.append("")
    lines.append("## Detail")
    lines.append("")
    for i, f in enumerate(findings, 1):
        lines.append(f"### {i}. [{f['severity']}] {f.get('page','/')} — {f.get('title','')}")
        lines.append("")
        lines.append(f"- **Fingerprint:** `{f.get('id','?')}`")
        lines.append(f"- **Source:** `{f.get('source','?')}`")
        lines.append(f"- **Occurrences this run:** {f.get('occurrences', 1)}")
        lines.append("")
        lines.append("**Evidence:**")
        lines.append("")
        lines.append("```")
        lines.append((f.get("evidence", "") or "")[:600])
        lines.append("```")
        lines.append("")
        if f.get("suggested_fix"):
            lines.append(f"**Suggested fix:** {f['suggested_fix']}")
            lines.append("")
    lines.append("---")
    lines.append("")
    lines.append("_Generated by the `web-review` skill._")
    return "\n".join(lines) + "\n"


def main() -> int:
    p = argparse.ArgumentParser()
    p.add_argument("--host", required=True)
    p.add_argument("--findings-file", type=Path, required=True)
    p.add_argument("--out", type=Path, required=True)
    args = p.parse_args()
    findings = json.loads(args.findings_file.read_text())
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(args.host, findings))
    print(f"Wrote {args.out} ({len(findings)} findings)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
