/**
 * Conformance test for the TypeScript `factorylm.visual-region.v1` mirror.
 *
 * Every case here is driven from `./golden-vectors.json`, a fixture generated by
 * running the FROZEN Python reference (`mira-bots/shared/visual/region_schema.py`,
 * PR V0). If the TS canonicalization ever drifts from Python, this test fails —
 * cross-language drift becomes a red build, not a silent bug.
 *
 * NOTE: `golden-vectors.json` also carries `mat_key` vectors. `regionMaterialization
 * Key` is intentionally NOT mirrored in TypeScript for V1 — it is a server-side,
 * Python-owned zero-token reuse anchor (PRD §8.3) whose sha256 is computed over a
 * Python-float-formatted JSON payload. It is exercised server-side in a later PR;
 * the vectors are kept here as forward-documentation only.
 */

import { describe, expect, it } from "vitest";

import {
  canonicalGeometry,
  fromStorageGeometry,
  toStorageGeometry,
  validateRegion,
} from "./canonical";
import golden from "./golden-vectors.json";
import { RegionValidationError, SCHEMA_ID, COORDINATE_SPACE } from "./schema";

describe("golden vectors: schema-level constants match the frozen contract", () => {
  it("schema id / coordinate space / precision agree with Python", () => {
    expect(golden.schema_id).toBe(SCHEMA_ID);
    expect(golden.coordinate_space).toBe(COORDINATE_SPACE);
    expect(golden.precision).toBe(6);
  });
});

describe("golden vectors: canonicalGeometry matches region_schema.py", () => {
  for (const c of golden.canonical) {
    it(`canonical: ${c.name}`, () => {
      expect(canonicalGeometry(c.input)).toEqual(c.output);
    });
  }
});

describe("golden vectors: storage geometry round-trips (rect <-> bbox)", () => {
  for (const c of golden.storage) {
    it(`storage: ${c.name}`, () => {
      expect(toStorageGeometry(c.v1)).toEqual(c.stored);
      expect(fromStorageGeometry(c.stored)).toEqual(c.roundtrip);
    });
  }
});

describe("golden vectors: validateRegion accepts valid regions", () => {
  golden.validate_ok.forEach((region, i) => {
    it(`validate_ok[${i}]`, () => {
      expect(() => validateRegion(region)).not.toThrow();
    });
  });
});

describe("golden vectors: validateRegion rejects invalid regions", () => {
  for (const c of golden.validate_err) {
    it(`validate_err: ${c.name}`, () => {
      expect(() => validateRegion(c.region)).toThrow(RegionValidationError);
    });
  }
});

describe("golden vectors: canonicalGeometry rejects invalid geometry", () => {
  for (const c of golden.geometry_err) {
    it(`geometry_err: ${c.name}`, () => {
      expect(() => canonicalGeometry(c.geometry)).toThrow(RegionValidationError);
    });
  }
});

// --- TS-only edge cases that cannot round-trip through the JSON fixture -------

describe("non-finite coordinates are rejected (cannot cross JSON)", () => {
  it("rejects NaN", () => {
    expect(() => canonicalGeometry({ type: "point", x: NaN, y: 0.1 })).toThrow(
      RegionValidationError,
    );
  });
  it("rejects Infinity", () => {
    expect(() =>
      canonicalGeometry({ type: "point", x: Infinity, y: 0.1 }),
    ).toThrow(RegionValidationError);
  });
  it("rejects -Infinity", () => {
    expect(() =>
      canonicalGeometry({ type: "point", x: -Infinity, y: 0.1 }),
    ).toThrow(RegionValidationError);
  });
});

describe("canonicalization invariants", () => {
  it("always stamps coordinate_space", () => {
    const g = canonicalGeometry({ type: "point", x: 0.2, y: 0.2 });
    expect(g.coordinate_space).toBe(COORDINATE_SPACE);
  });

  it("strips keys not in the canonical shape", () => {
    const g = canonicalGeometry({
      type: "point",
      x: 0.3,
      y: 0.3,
      bogus: "ignored",
      width: 0.9,
    });
    expect(g).toEqual({ type: "point", coordinate_space: COORDINATE_SPACE, x: 0.3, y: 0.3 });
  });

  it("rounds coordinates to 6 decimals", () => {
    const g = canonicalGeometry({ type: "point", x: 0.12345678, y: 0.87654321 });
    expect(g.x).toBe(0.123457);
    expect(g.y).toBe(0.876543);
  });

  it("rect -> bbox rename is the only storage difference", () => {
    const stored = toStorageGeometry({
      type: "rect",
      x: 0.1,
      y: 0.2,
      width: 0.3,
      height: 0.4,
    });
    expect(stored).toEqual({ type: "bbox", x: 0.1, y: 0.2, w: 0.3, h: 0.4 });
  });

  it("ellipse passes through storage unchanged", () => {
    const geom = { type: "ellipse", x: 0.2, y: 0.2, width: 0.2, height: 0.1 };
    expect(toStorageGeometry(geom)).toEqual(canonicalGeometry(geom));
  });

  it("rejects a rect whose box exceeds the page", () => {
    expect(() =>
      canonicalGeometry({ type: "rect", x: 0.8, y: 0.1, width: 0.5, height: 0.1 }),
    ).toThrow(/exceeds original bounds/);
  });
});
