/**
 * Canonicalization + validation for `factorylm.visual-region.v1`.
 *
 * A faithful TypeScript mirror of `mira-bots/shared/visual/region_schema.py`
 * (frozen by PR V0). Parity is enforced by `./canonical.test.ts`, which drives
 * every assertion from `./golden-vectors.json` — a fixture generated by running
 * the Python reference implementation. A box drawn in this viewer therefore
 * produces byte-identical canonical geometry to the Python side, so the region
 * materialization key (server-side, PRD §8.3) stays stable across surfaces.
 *
 * Pure + isomorphic (no imports beyond the sibling contract types) — safe in the
 * browser bundle. The server-only `regionMaterializationKey` is intentionally
 * NOT mirrored here (Python owns it in V1); see the note in `canonical.test.ts`.
 */

import {
  BOX_TYPES,
  COORDINATE_SPACE,
  GEOMETRY_TYPES,
  ORIGINS,
  PRECISION,
  RegionValidationError,
  SCHEMA_ID,
  STORAGE_RECT_TYPE,
  type Geometry,
  type GeometryType,
  type PointPair,
  type StorageGeometry,
} from "./schema";

const BOX_TYPE_SET: ReadonlySet<string> = new Set(BOX_TYPES);
const GEOMETRY_TYPE_SET: ReadonlySet<string> = new Set(GEOMETRY_TYPES);
const ORIGIN_SET: ReadonlySet<string> = new Set(ORIGINS);
const EPSILON = 10 ** -PRECISION;

/** Coerce to a finite number, mirroring Python's `float(value)` + finiteness guard. */
function num(value: unknown, field: string): number {
  const f = typeof value === "number" ? value : Number(value);
  if (typeof value === "string" && value.trim() === "") {
    throw new RegionValidationError(`${field}: not a number (${JSON.stringify(value)})`);
  }
  if (Number.isNaN(f)) {
    throw new RegionValidationError(`${field}: not a number (${JSON.stringify(value)})`);
  }
  if (!Number.isFinite(f)) {
    throw new RegionValidationError(`${field}: non-finite (${JSON.stringify(value)})`);
  }
  return f;
}

/**
 * Round to `PRECISION` decimals matching Python's `round()` (round-half-to-even).
 * On binary floats an exact decimal tie at the 7th place is effectively
 * unreachable, but we implement half-to-even so parity holds even in the corner.
 */
function round6(value: number): number {
  const factor = 10 ** PRECISION;
  const scaled = value * factor;
  const floor = Math.floor(scaled);
  const diff = scaled - floor;
  let rounded: number;
  if (diff > 0.5) {
    rounded = floor + 1;
  } else if (diff < 0.5) {
    rounded = floor;
  } else {
    // exact half -> round to even
    rounded = floor % 2 === 0 ? floor : floor + 1;
  }
  // Number(...toFixed) strips binary-float artifacts from the division.
  return Number((rounded / factor).toFixed(PRECISION));
}

/** A normalized coordinate: rounded to 6dp and enforced to `0 <= v <= 1`. */
function coord(value: unknown, field: string): number {
  const f = round6(num(value, field));
  if (!(f >= 0 && f <= 1)) {
    throw new RegionValidationError(
      `${field}: ${f} out of normalized range [0, 1] (PRD §6 coordinate rule)`,
    );
  }
  return f;
}

function canonicalPoints(points: unknown, gtype: GeometryType): PointPair[] {
  if (!Array.isArray(points) || points.length === 0) {
    throw new RegionValidationError(`${gtype}: 'points' must be a non-empty list`);
  }
  const minPts = gtype === "polygon" ? 3 : 2;
  if (points.length < minPts) {
    throw new RegionValidationError(
      `${gtype}: needs >= ${minPts} points, got ${points.length}`,
    );
  }
  return points.map((p, i) => {
    if (!Array.isArray(p) || p.length !== 2) {
      throw new RegionValidationError(`${gtype}: point ${i} must be [x, y]`);
    }
    return [
      coord(p[0], `${gtype}.points[${i}].x`),
      coord(p[1], `${gtype}.points[${i}].y`),
    ] as PointPair;
  });
}

/**
 * Return the deterministic canonical form of a v1 geometry — validates types +
 * normalized bounds, rounds every coordinate, and stamps `coordinate_space`.
 * Mirrors `canonical_geometry` in region_schema.py.
 */
export function canonicalGeometry(geometry: unknown): Geometry {
  if (geometry === null || typeof geometry !== "object" || Array.isArray(geometry)) {
    throw new RegionValidationError("geometry must be an object");
  }
  const g = geometry as Record<string, unknown>;
  const gtype = g.type;
  if (typeof gtype !== "string" || !GEOMETRY_TYPE_SET.has(gtype)) {
    throw new RegionValidationError(
      `geometry.type ${JSON.stringify(gtype)} not in ${JSON.stringify(GEOMETRY_TYPES)}`,
    );
  }
  const space = g.coordinate_space ?? COORDINATE_SPACE;
  if (space !== COORDINATE_SPACE) {
    throw new RegionValidationError(
      `coordinate_space ${JSON.stringify(space)} != ${JSON.stringify(
        COORDINATE_SPACE,
      )} (v1 is normalized-original only)`,
    );
  }

  const type = gtype as GeometryType;
  const canon: Geometry = { type, coordinate_space: COORDINATE_SPACE };
  if (type === "point") {
    canon.x = coord(g.x, "point.x");
    canon.y = coord(g.y, "point.y");
  } else if (BOX_TYPE_SET.has(type)) {
    const x = coord(g.x, `${type}.x`);
    const y = coord(g.y, `${type}.y`);
    const w = coord(g.width, `${type}.width`);
    const h = coord(g.height, `${type}.height`);
    if (x + w > 1 + EPSILON || y + h > 1 + EPSILON) {
      throw new RegionValidationError(
        `${type}: box exceeds original bounds (x+width or y+height > 1)`,
      );
    }
    canon.x = x;
    canon.y = y;
    canon.width = w;
    canon.height = h;
  } else {
    canon.points = canonicalPoints(g.points, type);
  }
  return canon;
}

/**
 * Raise `RegionValidationError` if `region` violates the contract. Checks the
 * `schema` const, the optional `origin` enum, and delegates geometry validation.
 * Mirrors `validate_region` in region_schema.py. Does not mutate input.
 */
export function validateRegion(region: unknown): void {
  if (region === null || typeof region !== "object" || Array.isArray(region)) {
    throw new RegionValidationError("region must be an object");
  }
  const r = region as Record<string, unknown>;
  if (r.schema !== SCHEMA_ID) {
    throw new RegionValidationError(
      `schema must be ${JSON.stringify(SCHEMA_ID)}, got ${JSON.stringify(r.schema)}`,
    );
  }
  const origin = r.origin;
  if (origin !== undefined && origin !== null && !ORIGIN_SET.has(origin as string)) {
    throw new RegionValidationError(
      `origin ${JSON.stringify(origin)} not in ${JSON.stringify(ORIGINS)}`,
    );
  }
  if (!("geometry" in r)) {
    throw new RegionValidationError("region missing 'geometry'");
  }
  canonicalGeometry(r.geometry);
}

/**
 * Map a v1 geometry into the existing `region_of_interest.geometry` shape
 * (migration 063). The only rename is `rect(x,y,width,height)` -> `bbox(x,y,w,h)`.
 * Round-trips with `fromStorageGeometry`. Mirrors `to_storage_geometry`.
 */
export function toStorageGeometry(geometry: unknown): StorageGeometry {
  const canon = canonicalGeometry(geometry);
  if (canon.type === "rect") {
    return {
      type: STORAGE_RECT_TYPE,
      x: canon.x as number,
      y: canon.y as number,
      w: canon.width as number,
      h: canon.height as number,
    };
  }
  return canon;
}

/** Inverse of `toStorageGeometry`: stored `bbox` -> v1 `rect`. */
export function fromStorageGeometry(storage: unknown): Geometry {
  if (storage === null || typeof storage !== "object" || Array.isArray(storage)) {
    throw new RegionValidationError("storage geometry must be an object");
  }
  const s = storage as Record<string, unknown>;
  if (s.type === STORAGE_RECT_TYPE) {
    return canonicalGeometry({
      type: "rect",
      x: s.x,
      y: s.y,
      width: s.w,
      height: s.h,
    });
  }
  return canonicalGeometry(storage);
}
