/**
 * factorylm.visual-region.v1 — TypeScript view of the FROZEN canonical
 * annotation contract.
 *
 * The language-neutral source of truth is
 * `mira-bots/shared/visual/schemas/factorylm.visual-region.v1.json` (frozen by
 * PR V0). The Python reference implementation is
 * `mira-bots/shared/visual/region_schema.py`. This file mirrors the *types and
 * constants* of that contract for the shared Hub visual workspace (PR V1); the
 * canonicalization/validation logic lives in `./canonical.ts` and is pinned to
 * the Python implementation by the golden-vector conformance test
 * (`./golden-vectors.json`, generated by driving `region_schema.py`).
 *
 * Coordinate rule (PRD §6): all geometry is normalized to the ORIGINAL
 * page/photo, `0 <= x, y, width, height <= 1`. This survives device size, zoom,
 * pan, rotation, Telegram vs Hub, raster derivatives, and deep-zoom tiles.
 *
 * This module is pure (no imports, isomorphic) — safe in the browser bundle.
 */

/** The frozen schema identifier. */
export const SCHEMA_ID = "factorylm.visual-region.v1" as const;

/** The six supported geometry primitives (PRD §6 "Supported geometry"). */
export const GEOMETRY_TYPES = [
  "point",
  "rect",
  "ellipse",
  "polygon",
  "polyline",
  "freehand",
] as const;
export type GeometryType = (typeof GEOMETRY_TYPES)[number];

/** `region_of_interest.origin` CHECK values (migration 063). */
export const ORIGINS = ["user", "system"] as const;
export type Origin = (typeof ORIGINS)[number];

/** The only canonical coordinate space in v1 — normalized to the original. */
export const COORDINATE_SPACE = "normalized_original" as const;

/**
 * Canonical float precision — enough for sub-pixel accuracy on a 4K sheet
 * (1/1e6 of a page is < 0.004 px at 3840 px wide) while making serialization
 * deterministic across devices and float noise. Must match `_PRECISION` in
 * region_schema.py.
 */
export const PRECISION = 6;

/** Box-shaped primitives carry `x, y, width, height`. */
export const BOX_TYPES = ["rect", "ellipse"] as const;
/** Path-shaped primitives carry `points` (a list of `[x, y]` pairs). */
export const PATH_TYPES = ["polygon", "polyline", "freehand"] as const;

/**
 * The existing ledger's stored type for a rectangle (migration 063 comment
 * `{type:'bbox', x,y,w,h}`). `rect` <-> `bbox` is the only rename between the v1
 * contract and the stored geometry.
 */
export const STORAGE_RECT_TYPE = "bbox" as const;

/** A normalized `[x, y]` coordinate pair, each in `[0, 1]`. */
export type PointPair = [number, number];

/**
 * A canonical v1 geometry. Box types carry `x/y/width/height`; path types carry
 * `points`; `point` carries `x/y`. Always stamped with `coordinate_space`.
 */
export interface Geometry {
  type: GeometryType;
  coordinate_space: typeof COORDINATE_SPACE;
  x?: number;
  y?: number;
  width?: number;
  height?: number;
  points?: PointPair[];
}

/** A full v1 visual region (the annotation envelope). */
export interface VisualRegion {
  schema: typeof SCHEMA_ID;
  region_id?: string;
  evidence_id?: string;
  page_ref?: string | null;
  origin?: Origin;
  geometry: Geometry;
  style?: Record<string, unknown>;
  transform_to_original?: Record<string, unknown> | null;
  created_from?: Record<string, unknown>;
}

/** The stored geometry shape (migration 063): `rect` serialized as `bbox`. */
export type StorageGeometry =
  | { type: typeof STORAGE_RECT_TYPE; x: number; y: number; w: number; h: number }
  | Geometry;

/** Raised when a region/geometry violates `factorylm.visual-region.v1`. */
export class RegionValidationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "RegionValidationError";
  }
}
