import { NextResponse } from "next/server";
import { sessionOr401 } from "@/lib/session";
import { withTenantContext } from "@/lib/tenant-context";

export const dynamic = "force-dynamic";

/**
 * Detail / move / rename a namespace node.
 *
 * Spec: docs/specs/maintenance-namespace-builder-spec.md §"Namespace tree"
 *
 * GET /api/namespace/node/:id
 *   Returns the entity, its verified + proposed outbound relationships,
 *   and per-node counts (children, proposalsPending, proposalsVerified).
 *   Used by the namespace explorer right-side detail pane (#1347).
 *
 *   Synthetic ids (prefix "synthetic:") have no kg_entities row — they are
 *   parent-path placeholders generated by buildTree. We return 404 with a
 *   marker so the UI can render a "no detail available" placeholder
 *   without surfacing a hard error.
 *
 * PUT /api/namespace/node/:id
 *   Body: { "newParentId"?: string, "newName"?: string, "reason"?: string }
 *
 * Update path:
 *   1. SELECT the target entity FOR UPDATE.
 *   2. Resolve new uns_path: parent.uns_path + slug(newName) (or current name).
 *   3. UPDATE kg_entities (name, uns_path).
 *   4. INSERT into namespace_versions with the before/after JSONB snapshot.
 *
 * Both updates run inside the same `withTenantContext` transaction so a
 * failure rolls back the audit row alongside the move.
 */

interface KgEntityRow {
  id: string;
  entity_type: string;
  name: string;
  uns_path: string | null;
}

interface KgEntityDetailRow extends KgEntityRow {
  properties: unknown;
  created_at: string;
  updated_at: string;
}

interface VerifiedRelRow {
  id: string;
  relationship_type: string;
  target_id: string;
  target_name: string | null;
  target_uns_path: string | null;
  confidence: number | null;
  properties: unknown;
}

interface ProposedRelRow {
  id: string;
  relationship_type: string;
  target_entity_id: string;
  target_name: string | null;
  target_uns_path: string | null;
  confidence: number | null;
  created_by: string;
  status: string;
}

interface CountsRow {
  children: string;
  proposals_pending: string;
  proposals_verified: string;
}

export interface NodeDetailResponse {
  node: {
    id: string;
    name: string;
    kind: string;
    unsPath: string | null;
    properties: unknown;
    createdAt: string;
    updatedAt: string;
  };
  relationships: {
    verified: Array<{
      id: string;
      type: string;
      targetId: string;
      targetName: string | null;
      targetUnsPath: string | null;
      confidence: number | null;
      properties: unknown;
    }>;
    proposed: Array<{
      id: string;
      type: string;
      targetId: string;
      targetName: string | null;
      targetUnsPath: string | null;
      confidence: number | null;
      createdBy: string;
      status: string;
    }>;
  };
  counts: {
    children: number;
    proposalsPending: number;
    proposalsVerified: number;
  };
}

export async function GET(_req: Request, { params }: { params: Promise<{ id: string }> }) {
  if (!process.env.NEON_DATABASE_URL) {
    return NextResponse.json({ error: "DB not configured" }, { status: 503 });
  }
  const ctx = await sessionOr401();
  if (ctx instanceof NextResponse) return ctx;

  const { id } = await params;

  if (id.startsWith("synthetic:")) {
    return NextResponse.json(
      { error: "synthetic node", synthetic: true },
      { status: 404 },
    );
  }
  if (!/^[0-9a-f-]{36}$/i.test(id)) {
    return NextResponse.json({ error: "invalid id" }, { status: 400 });
  }

  try {
    const result = await withTenantContext(ctx.tenantId, async (c) => {
      const entityRes = await c.query<KgEntityDetailRow>(
        `SELECT id, entity_type, name, uns_path::text AS uns_path,
                properties, created_at, updated_at
         FROM kg_entities
         WHERE id = $1 AND tenant_id = $2::uuid`,
        [id, ctx.tenantId],
      );
      if (entityRes.rows.length === 0) {
        return { kind: "not_found" as const };
      }
      const entity = entityRes.rows[0];

      const verifiedRes = await c.query<VerifiedRelRow>(
        `SELECT r.id, r.relationship_type, r.target_id,
                t.name AS target_name, t.uns_path::text AS target_uns_path,
                r.confidence, r.properties
         FROM kg_relationships r
         LEFT JOIN kg_entities t ON t.id = r.target_id
         WHERE r.source_id = $1 AND r.tenant_id = $2::uuid
         ORDER BY r.relationship_type, t.name NULLS LAST`,
        [id, ctx.tenantId],
      );

      const proposedRes = await c.query<ProposedRelRow>(
        `SELECT p.id, p.relationship_type, p.target_entity_id,
                t.name AS target_name, t.uns_path::text AS target_uns_path,
                p.confidence, p.created_by, p.status
         FROM relationship_proposals p
         LEFT JOIN kg_entities t ON t.id = p.target_entity_id
         WHERE p.source_entity_id = $1
           AND p.tenant_id = $2::uuid
           AND p.status = 'proposed'
         ORDER BY p.confidence DESC NULLS LAST, p.relationship_type`,
        [id, ctx.tenantId],
      );

      // ltree-based direct-children + status-bucketed proposal counts in one round trip.
      // nlevel = depth, so `nlevel(c.uns_path) = nlevel(parent.uns_path) + 1` filters to
      // immediate children only (mirrors what the tree builder uses for `counts.children`).
      const countsRes = await c.query<CountsRow>(
        `WITH parent AS (
            SELECT uns_path FROM kg_entities WHERE id = $1 AND tenant_id = $2::uuid
         )
         SELECT
           COALESCE((SELECT COUNT(*)::text FROM kg_entities c, parent
                       WHERE c.tenant_id = $2::uuid
                         AND parent.uns_path IS NOT NULL
                         AND c.uns_path <@ parent.uns_path
                         AND c.id <> $1
                         AND nlevel(c.uns_path) = nlevel(parent.uns_path) + 1), '0') AS children,
           COALESCE((SELECT COUNT(*)::text FROM relationship_proposals p
                       WHERE p.tenant_id = $2::uuid
                         AND p.source_entity_id = $1
                         AND p.status = 'proposed'), '0') AS proposals_pending,
           COALESCE((SELECT COUNT(*)::text FROM relationship_proposals p
                       WHERE p.tenant_id = $2::uuid
                         AND p.source_entity_id = $1
                         AND p.status = 'verified'), '0') AS proposals_verified`,
        [id, ctx.tenantId],
      );

      return {
        kind: "ok" as const,
        entity,
        verified: verifiedRes.rows,
        proposed: proposedRes.rows,
        counts: countsRes.rows[0] ?? {
          children: "0",
          proposals_pending: "0",
          proposals_verified: "0",
        },
      };
    });

    if (result.kind === "not_found") {
      return NextResponse.json({ error: "node not found" }, { status: 404 });
    }

    const payload: NodeDetailResponse = {
      node: {
        id: result.entity.id,
        name: result.entity.name,
        kind: result.entity.entity_type,
        unsPath: result.entity.uns_path,
        properties: result.entity.properties,
        createdAt: result.entity.created_at,
        updatedAt: result.entity.updated_at,
      },
      relationships: {
        verified: result.verified.map((r: VerifiedRelRow) => ({
          id: r.id,
          type: r.relationship_type,
          targetId: r.target_id,
          targetName: r.target_name,
          targetUnsPath: r.target_uns_path,
          confidence: r.confidence,
          properties: r.properties,
        })),
        proposed: result.proposed.map((r: ProposedRelRow) => ({
          id: r.id,
          type: r.relationship_type,
          targetId: r.target_entity_id,
          targetName: r.target_name,
          targetUnsPath: r.target_uns_path,
          confidence: r.confidence,
          createdBy: r.created_by,
          status: r.status,
        })),
      },
      counts: {
        children: Number(result.counts.children) || 0,
        proposalsPending: Number(result.counts.proposals_pending) || 0,
        proposalsVerified: Number(result.counts.proposals_verified) || 0,
      },
    };
    return NextResponse.json(payload);
  } catch (err) {
    console.error("[api/namespace/node/:id GET]", err);
    return NextResponse.json({ error: "Query failed" }, { status: 500 });
  }
}

export async function PUT(req: Request, { params }: { params: Promise<{ id: string }> }) {
  if (!process.env.NEON_DATABASE_URL) {
    return NextResponse.json({ error: "DB not configured" }, { status: 503 });
  }
  const ctx = await sessionOr401();
  if (ctx instanceof NextResponse) return ctx;

  const { id } = await params;
  if (!id || !/^[0-9a-f-]{36}$/i.test(id)) {
    return NextResponse.json({ error: "invalid id" }, { status: 400 });
  }

  let body: { newParentId?: string; newName?: string; reason?: string };
  try {
    body = await req.json();
  } catch {
    return NextResponse.json({ error: "invalid JSON body" }, { status: 400 });
  }

  const newParentId = body.newParentId?.trim();
  const newName = body.newName?.trim();
  const reason = (body.reason ?? "").slice(0, 1000);

  if (!newParentId && !newName) {
    return NextResponse.json(
      { error: "either newParentId or newName must be provided" },
      { status: 400 },
    );
  }
  if (newParentId && !/^[0-9a-f-]{36}$/i.test(newParentId)) {
    return NextResponse.json({ error: "invalid newParentId" }, { status: 400 });
  }

  try {
    const result = await withTenantContext(ctx.tenantId, async (c) => {
      const targetRes = await c.query<KgEntityRow>(
        `SELECT id, entity_type, name, uns_path::text AS uns_path
         FROM kg_entities
         WHERE id = $1 AND tenant_id = $2
         FOR UPDATE`,
        [id, ctx.tenantId],
      );
      if (targetRes.rows.length === 0) {
        return { kind: "not_found" as const };
      }
      const target = targetRes.rows[0];

      let parentPath: string | null = parentOf(target.uns_path);
      let parentRow: KgEntityRow | null = null;

      if (newParentId) {
        const parentRes = await c.query<KgEntityRow>(
          `SELECT id, entity_type, name, uns_path::text AS uns_path
           FROM kg_entities
           WHERE id = $1 AND tenant_id = $2`,
          [newParentId, ctx.tenantId],
        );
        if (parentRes.rows.length === 0) {
          return { kind: "parent_not_found" as const };
        }
        parentRow = parentRes.rows[0];

        if (parentRow.id === target.id) {
          return { kind: "self_parent" as const };
        }
        if (
          parentRow.uns_path &&
          target.uns_path &&
          (parentRow.uns_path === target.uns_path ||
            parentRow.uns_path.startsWith(target.uns_path + "."))
        ) {
          return { kind: "descendant_parent" as const };
        }
        parentPath = parentRow.uns_path ?? null;
      }

      const finalName = newName && newName.length > 0 ? newName : target.name;
      const slug = slugify(finalName);
      const newPath = parentPath ? `${parentPath}.${slug}` : slug;

      await c.query(
        `UPDATE kg_entities
            SET name = $1,
                uns_path = $2::ltree,
                updated_at = now()
          WHERE id = $3`,
        [finalName, newPath, id],
      );

      const operation =
        newParentId && (newName === undefined || newName === target.name)
          ? "move"
          : newName && !newParentId
            ? "rename"
            : "move";

      await c.query(
        `INSERT INTO namespace_versions
            (tenant_id, operation, entity_id, entity_kind,
             from_state, to_state,
             actor_user_id, actor_kind, reason)
         VALUES ($1, $2, $3, $4, $5::jsonb, $6::jsonb, $7, 'human', $8)`,
        [
          ctx.tenantId,
          operation,
          id,
          target.entity_type,
          JSON.stringify({ uns_path: target.uns_path, name: target.name }),
          JSON.stringify({ uns_path: newPath, name: finalName }),
          ctx.userId,
          reason,
        ],
      );

      return {
        kind: "ok" as const,
        node: {
          id,
          name: finalName,
          unsPath: newPath,
          kind: target.entity_type,
          previousUnsPath: target.uns_path,
          previousName: target.name,
          operation,
        },
      };
    });

    if (result.kind === "not_found") {
      return NextResponse.json({ error: "node not found" }, { status: 404 });
    }
    if (result.kind === "parent_not_found") {
      return NextResponse.json({ error: "newParentId not found" }, { status: 404 });
    }
    if (result.kind === "self_parent") {
      return NextResponse.json({ error: "cannot make a node its own parent" }, { status: 400 });
    }
    if (result.kind === "descendant_parent") {
      return NextResponse.json(
        { error: "cannot move a node under one of its descendants" },
        { status: 400 },
      );
    }
    return NextResponse.json({ ok: true, ...result.node });
  } catch (err) {
    console.error("[api/namespace/node/:id PUT]", err);
    return NextResponse.json({ error: "Move failed" }, { status: 500 });
  }
}

function parentOf(path: string | null): string | null {
  if (!path) return null;
  const i = path.lastIndexOf(".");
  return i < 0 ? null : path.slice(0, i);
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "_")
    .replace(/^_+|_+$/g, "")
    .slice(0, 64) || "_";
}
