"""Unit tests for mira-bots/tools/fix_proposer.py

Coverage:
  - Scorecard parsing extracts failures from markdown
  - Cluster detection groups by signature; filters on min_cluster_size
  - Fixture tags flow into cluster metadata
  - Repo context gathering maps signature → files
  - Patch proposal prompts include cluster + context
  - Sandbox applies patch and reports correctly
  - Draft PR uses --draft, correct labels, assignee
  - Max PRs per run honored
  - FIX_PROPOSER_DISABLED=1 short-circuits run()
"""

from __future__ import annotations

import sys
import textwrap
from pathlib import Path
from unittest.mock import MagicMock, patch, call

import pytest
import yaml

# Ensure the tools dir is on the path so we can import fix_proposer directly
_TOOLS_DIR = Path(__file__).parent.parent.parent / "tools"
sys.path.insert(0, str(_TOOLS_DIR))

from fix_proposer import (  # noqa: E402
    FailureCluster,
    FailureRecord,
    FixProposer,
    PatchProposal,
    SandboxResult,
    _classify_signature,
    _parse_scorecard,
)


# ── Fixtures ──────────────────────────────────────────────────────────────────


SAMPLE_SCORECARD = textwrap.dedent("""\
    # MIRA Eval Scorecard — 2026-04-14

    **Pass rate:** 7/10 scenarios (70%)
    **Mode:** LIVE
    **Checkpoints:** FSM state / Pipeline active / Keyword match / No 5xx / Turn budget

    ## Results

    | Scenario | FSM state | Pipeline active | Keyword match | No 5xx | Turn budget | Score | FSM State |
    |----------|-----------|-----------------|---------------|--------|-------------|-------|-----------|
    | `gs10_overcurrent_01` | PASS | PASS | PASS | PASS | PASS | 5/5 | DIAGNOSIS |
    | `gs20_cross_vendor_03` | PASS | PASS | FAIL | PASS | PASS | 4/5 | DIAGNOSIS |
    | `yaskawa_out_of_kb_04` | PASS | PASS | FAIL | PASS | PASS | 4/5 | DIAGNOSIS |
    | `doc_intent_pilz_11` | PASS | PASS | FAIL | PASS | PASS | 4/5 | DIAGNOSIS |

    ## Failures

    ### gs20_cross_vendor_03
    - **cp_keyword_match** FAILED: Forbidden keywords present: ['PowerFlex 525']
    - Last response: `You're getting F004 on an Allen-Bradley PowerFlex, which typically indicates...`

    ### yaskawa_out_of_kb_04
    - **cp_keyword_match** FAILED: No honesty signal — possible hallucination
    - Last response: `The E7 fault on your Yaskawa V1000 indicates...`

    ### doc_intent_pilz_11
    - **cp_keyword_match** FAILED: No match from ['pilz.com/support', 'pilz.com']
    - Last response: `The Pilz PNOZ relay is a safety relay that...`

    ## Timing

    Total wall time: 52.1s across 10 scenarios

    ---
    *Generated by `tests/eval/run_eval.py` at 2026-04-14T02:00:00.000000+00:00*
""")

# Three scorecards with the same doc_intent failure = cluster of 3
DOC_INTENT_SCORECARD_TEMPLATE = textwrap.dedent("""\
    # MIRA Eval Scorecard — {date}

    **Pass rate:** 9/10 scenarios (90%)
    **Mode:** LIVE
    **Checkpoints:** FSM state / Pipeline active / Keyword match / No 5xx / Turn budget

    ## Failures

    ### doc_intent_pilz_11
    - **cp_keyword_match** FAILED: No match from ['pilz.com/support', 'pilz.com']
    - Last response: `The Pilz PNOZ relay is a safety relay...`

    ---
    *Generated at {date}T02:00:00+00:00*
""")


def _write_scorecards(tmp_path: Path, dates: list[str]) -> None:
    for date in dates:
        (tmp_path / f"{date}.md").write_text(
            DOC_INTENT_SCORECARD_TEMPLATE.format(date=date)
        )


def _write_fixture_yaml(fixtures_dir: Path, fixture_id: str, tags: list[str]) -> None:
    fixtures_dir.mkdir(parents=True, exist_ok=True)
    data = {
        "id": fixture_id,
        "description": f"Test fixture {fixture_id}",
        "expected_final_state": "DIAGNOSIS",
        "max_turns": 5,
        "expected_keywords": ["pilz.com/support"],
        "tags": tags,
    }
    (fixtures_dir / f"11_{fixture_id}.yaml").write_text(yaml.dump(data))


# ── Scorecard parsing tests ───────────────────────────────────────────────────


def test_parse_scorecard_extracts_all_failures(tmp_path: Path) -> None:
    md_path = tmp_path / "2026-04-14.md"
    md_path.write_text(SAMPLE_SCORECARD)

    records = _parse_scorecard(md_path)

    assert len(records) == 3
    ids = {r.scenario_id for r in records}
    assert ids == {"gs20_cross_vendor_03", "yaskawa_out_of_kb_04", "doc_intent_pilz_11"}


def test_parse_scorecard_checkpoint_names(tmp_path: Path) -> None:
    md_path = tmp_path / "2026-04-14.md"
    md_path.write_text(SAMPLE_SCORECARD)

    records = _parse_scorecard(md_path)

    # All failures in this scorecard are cp_keyword_match
    assert all(r.checkpoint == "cp_keyword_match" for r in records)


def test_parse_scorecard_extracts_run_date(tmp_path: Path) -> None:
    md_path = tmp_path / "2026-04-15.md"
    md_path.write_text(SAMPLE_SCORECARD)

    records = _parse_scorecard(md_path)

    assert all(r.run_date == "2026-04-15" for r in records)


def test_parse_scorecard_extracts_last_response(tmp_path: Path) -> None:
    md_path = tmp_path / "2026-04-14.md"
    md_path.write_text(SAMPLE_SCORECARD)

    records = _parse_scorecard(md_path)
    cross_vendor = next(r for r in records if r.scenario_id == "gs20_cross_vendor_03")

    assert "Allen-Bradley PowerFlex" in cross_vendor.last_response


def test_parse_scorecard_no_failures_returns_empty(tmp_path: Path) -> None:
    md_path = tmp_path / "2026-04-14.md"
    md_path.write_text("# MIRA Eval Scorecard\n\n**Pass rate:** 10/10\n")

    assert _parse_scorecard(md_path) == []


# ── Signature classifier tests ────────────────────────────────────────────────


def test_classify_forbidden_keywords() -> None:
    assert _classify_signature("cp_keyword_match", "Forbidden keywords present: ['PowerFlex 525']") == "cp_forbidden_keywords_hit"


def test_classify_no_honesty_signal() -> None:
    assert _classify_signature("cp_keyword_match", "No honesty signal — possible hallucination") == "cp_keyword_match_no_honesty_signal"


def test_classify_no_safety_terms() -> None:
    assert _classify_signature("cp_keyword_match", "No safety terms in response") == "cp_keyword_match_no_safety_terms"


def test_classify_no_match() -> None:
    assert _classify_signature("cp_keyword_match", "No match from ['pilz.com/support']") == "cp_keyword_match_no_match"


def test_classify_fsm_state_below() -> None:
    assert _classify_signature("cp_reached_state", "State='Q1', expected='DIAGNOSIS'") == "cp_reached_state_below_expected"


def test_classify_5xx() -> None:
    assert _classify_signature("cp_no_5xx", "5xx responses: [502]") == "cp_5xx_errors"


# ── Cluster detection tests ───────────────────────────────────────────────────


def test_cluster_detection_groups_3_doc_intent_failures(tmp_path: Path) -> None:
    scorecards_dir = tmp_path / "runs"
    scorecards_dir.mkdir()
    fixtures_dir = tmp_path / "fixtures"
    _write_scorecards(scorecards_dir, ["2026-04-12", "2026-04-13", "2026-04-14"])
    _write_fixture_yaml(fixtures_dir, "doc_intent_pilz_11", ["documentation", "pilz", "vfd"])

    proposer = FixProposer(
        scorecards_dir=scorecards_dir,
        repo_path=tmp_path,
        gh_token="",
    )
    proposer.fixtures_dir = fixtures_dir

    records = proposer.load_recent_scorecards(days=30)
    clusters = proposer.cluster_failures(records)

    assert len(clusters) == 1
    assert clusters[0].signature == "cp_keyword_match_no_match"
    assert len(clusters[0].members) == 3


def test_cluster_below_min_size_excluded(tmp_path: Path) -> None:
    scorecards_dir = tmp_path / "runs"
    scorecards_dir.mkdir()
    fixtures_dir = tmp_path / "fixtures"
    # Only 2 scorecards — below default min of 3
    _write_scorecards(scorecards_dir, ["2026-04-13", "2026-04-14"])
    _write_fixture_yaml(fixtures_dir, "doc_intent_pilz_11", ["documentation"])

    proposer = FixProposer(
        scorecards_dir=scorecards_dir,
        repo_path=tmp_path,
        gh_token="",
    )
    proposer.fixtures_dir = fixtures_dir

    records = proposer.load_recent_scorecards(days=30)
    clusters = proposer.cluster_failures(records)

    assert len(clusters) == 0


def test_cluster_includes_fixture_tags(tmp_path: Path) -> None:
    scorecards_dir = tmp_path / "runs"
    scorecards_dir.mkdir()
    fixtures_dir = tmp_path / "fixtures"
    _write_scorecards(scorecards_dir, ["2026-04-12", "2026-04-13", "2026-04-14"])
    _write_fixture_yaml(
        fixtures_dir, "doc_intent_pilz_11", ["documentation", "pilz", "safety"]
    )

    proposer = FixProposer(
        scorecards_dir=scorecards_dir,
        repo_path=tmp_path,
        gh_token="",
    )
    proposer.fixtures_dir = fixtures_dir

    records = proposer.load_recent_scorecards(days=30)
    clusters = proposer.cluster_failures(records)

    assert len(clusters) == 1
    assert "documentation" in clusters[0].fixture_tags
    assert "pilz" in clusters[0].fixture_tags


def test_cluster_sorted_by_size_descending(tmp_path: Path) -> None:
    scorecards_dir = tmp_path / "runs"
    scorecards_dir.mkdir()
    fixtures_dir = tmp_path / "fixtures"
    fixtures_dir.mkdir()

    # 5 forbidden-keyword failures across 5 dates
    for i, date in enumerate(["2026-04-10", "2026-04-11", "2026-04-12", "2026-04-13", "2026-04-14"]):
        (scorecards_dir / f"{date}.md").write_text(textwrap.dedent(f"""\
            # MIRA Eval Scorecard — {date}

            ## Failures

            ### gs20_cross_vendor_03
            - **cp_keyword_match** FAILED: Forbidden keywords present: ['PowerFlex 525']
            - Last response: `Allen-Bradley response {i}`

            ### doc_intent_pilz_11
            - **cp_keyword_match** FAILED: No match from ['pilz.com/support']
            - Last response: `Pilz response {i}`

            ---
        """))

    # Set min_cluster_size=3 — both clusters have 5 members
    proposer = FixProposer(
        scorecards_dir=scorecards_dir,
        repo_path=tmp_path,
        gh_token="",
    )
    proposer.fixtures_dir = fixtures_dir
    proposer.min_cluster_size = 3

    records = proposer.load_recent_scorecards(days=30)
    clusters = proposer.cluster_failures(records)

    # Both clusters have 5 members; order is stable
    assert len(clusters) == 2
    assert clusters[0].signature in ("cp_forbidden_keywords_hit", "cp_keyword_match_no_match")


# ── Context gathering tests ───────────────────────────────────────────────────


def test_gather_repo_context_reads_source_files(tmp_path: Path) -> None:
    # Create a fake source file
    src_dir = tmp_path / "mira-bots" / "shared"
    src_dir.mkdir(parents=True)
    (src_dir / "guardrails.py").write_text("VENDOR_SUPPORT_URLS = {}\n")

    fixtures_dir = tmp_path / "tests" / "eval" / "fixtures"
    fixtures_dir.mkdir(parents=True)

    cluster = FailureCluster(
        signature="cp_keyword_match_missed_vendor_url",
        members=[
            FailureRecord(
                scenario_id="doc_intent_pilz_11",
                checkpoint="cp_keyword_match",
                reason="No match from ['pilz.com/support']",
                last_response="Pilz response",
                run_date="2026-04-14",
            )
        ] * 3,
        fixture_tags=["documentation"],
        source_files=["mira-bots/shared/guardrails.py"],
    )

    proposer = FixProposer(
        scorecards_dir=tmp_path / "runs",
        repo_path=tmp_path,
        gh_token="",
    )
    proposer._fixture_cache = {}

    with patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(returncode=0, stdout="abc1234 fix guardrails\n")
        context = proposer.gather_repo_context(cluster)

    assert "VENDOR_SUPPORT_URLS" in context
    assert "mira-bots/shared/guardrails.py" in context


def test_gather_repo_context_handles_missing_file(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_keyword_match_missed_vendor_url",
        members=[
            FailureRecord("s1", "cp_keyword_match", "No match", "", "2026-04-14")
        ] * 3,
        source_files=["mira-bots/shared/does_not_exist.py"],
    )

    proposer = FixProposer(
        scorecards_dir=tmp_path,
        repo_path=tmp_path,
        gh_token="",
    )
    proposer._fixture_cache = {}

    with patch("subprocess.run") as mock_run:
        mock_run.return_value = MagicMock(returncode=0, stdout="")
        context = proposer.gather_repo_context(cluster)

    assert "FILE NOT FOUND" in context


# ── Patch proposal tests ──────────────────────────────────────────────────────


def test_propose_patch_prompt_includes_cluster_info(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_forbidden_keywords_hit",
        members=[
            FailureRecord("gs20_cross_vendor_03", "cp_keyword_match", "Forbidden keywords present: ['PowerFlex 525']", "", "2026-04-14"),
            FailureRecord("gs20_cross_vendor_03", "cp_keyword_match", "Forbidden keywords present: ['PowerFlex 525']", "", "2026-04-13"),
            FailureRecord("gs20_cross_vendor_03", "cp_keyword_match", "Forbidden keywords present: ['PowerFlex 525']", "", "2026-04-12"),
        ],
        fixture_tags=["cross-vendor", "gs20"],
        source_files=["mira-bots/shared/workers/rag_worker.py"],
    )

    captured_payload: list[dict] = []

    def mock_post(url: str, **kwargs: object) -> MagicMock:
        captured_payload.append(kwargs)
        mock_resp = MagicMock()
        mock_resp.raise_for_status = MagicMock()
        mock_resp.json.return_value = {
            "content": [{"text": "--- a/file.py\n+++ b/file.py\n@@ -1,1 +1,1 @@\n-old\n+new"}],
            "usage": {"input_tokens": 500},
        }
        return mock_resp

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    with patch.dict("os.environ", {"ANTHROPIC_API_KEY": "test-key"}):
        with patch("httpx.Client") as mock_client_cls:
            mock_client = MagicMock()
            mock_client.__enter__ = MagicMock(return_value=mock_client)
            mock_client.__exit__ = MagicMock(return_value=False)
            mock_client.post = mock_post
            mock_client_cls.return_value = mock_client

            result = proposer.propose_patch(cluster, context="## mira-bots/shared/workers/rag_worker.py\n```python\n# code\n```")

    assert result is not None
    assert result.model == "claude-sonnet-4-6"
    assert result.input_tokens == 500

    payload = captured_payload[0]["json"]
    prompt_text = payload["messages"][0]["content"]
    assert "cp_forbidden_keywords_hit" in prompt_text
    assert "gs20_cross_vendor_03" in prompt_text
    assert "cross-vendor" in prompt_text
    assert payload["temperature"] == 0.2


def test_propose_patch_returns_none_when_no_api_key(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_forbidden_keywords_hit",
        members=[FailureRecord("s1", "cp_keyword_match", "reason", "", "2026-04-14")] * 3,
    )
    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    with patch.dict("os.environ", {}, clear=True):
        result = proposer.propose_patch(cluster, context="")

    assert result is None


def test_propose_patch_returns_none_for_no_patch_possible(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_forbidden_keywords_hit",
        members=[FailureRecord("s1", "cp_keyword_match", "reason", "", "2026-04-14")] * 3,
    )
    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    with patch.dict("os.environ", {"ANTHROPIC_API_KEY": "test-key"}):
        with patch("httpx.Client") as mock_client_cls:
            mock_client = MagicMock()
            mock_client.__enter__ = MagicMock(return_value=mock_client)
            mock_client.__exit__ = MagicMock(return_value=False)
            mock_resp = MagicMock()
            mock_resp.raise_for_status = MagicMock()
            mock_resp.json.return_value = {
                "content": [{"text": "NO_PATCH_POSSIBLE"}],
                "usage": {"input_tokens": 100},
            }
            mock_client.post = MagicMock(return_value=mock_resp)
            mock_client_cls.return_value = mock_client

            result = proposer.propose_patch(cluster, context="")

    assert result is None


# ── Sandbox tests ─────────────────────────────────────────────────────────────


def test_sandbox_patch_applies_cleanly(tmp_path: Path) -> None:
    cluster = FailureCluster(signature="cp_forbidden_keywords_hit", members=[])
    patch_proposal = PatchProposal(
        diff="--- a/guardrails.py\n+++ b/guardrails.py\n@@ -1,1 +1,1 @@\n-old\n+new",
        model="claude-sonnet-4-6",
        input_tokens=100,
    )

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    def mock_subprocess_run(args: list[str], **kwargs: object) -> MagicMock:
        r = MagicMock()
        r.returncode = 0
        r.stdout = ""
        r.stderr = ""
        return r

    with patch("subprocess.run", side_effect=mock_subprocess_run):
        result = proposer.sandbox_patch(cluster, patch_proposal)

    assert result.patch_applies is True
    assert result.dry_run_passed is True
    assert result.error == ""


def test_sandbox_patch_fails_on_bad_diff(tmp_path: Path) -> None:
    cluster = FailureCluster(signature="cp_forbidden_keywords_hit", members=[])
    patch_proposal = PatchProposal(
        diff="not a valid diff at all",
        model="claude-sonnet-4-6",
        input_tokens=50,
    )

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    call_count = 0

    def mock_subprocess_run(args: list[str], **kwargs: object) -> MagicMock:
        nonlocal call_count
        r = MagicMock()
        cmd = args[0] if args else ""
        if cmd == "git" and "worktree" in args and "add" in args:
            r.returncode = 0
        elif cmd == "patch" and "--dry-run" in args:
            r.returncode = 1
            r.stderr = "patch: malformed patch"
        else:
            r.returncode = 0
        r.stdout = ""
        call_count += 1
        return r

    with patch("subprocess.run", side_effect=mock_subprocess_run):
        result = proposer.sandbox_patch(cluster, patch_proposal)

    assert result.patch_applies is False
    assert "patch --dry-run failed" in result.error


def test_sandbox_reports_regression_on_eval_failure(tmp_path: Path) -> None:
    cluster = FailureCluster(signature="cp_forbidden_keywords_hit", members=[])
    patch_proposal = PatchProposal(
        diff="--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,1 @@\n-old\n+new",
        model="claude-sonnet-4-6",
        input_tokens=100,
    )
    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    def mock_subprocess_run(args: list[str], **kwargs: object) -> MagicMock:
        r = MagicMock()
        r.stdout = ""
        r.stderr = ""
        cmd = args[0] if args else ""
        if cmd == "git" and "worktree" in args:
            r.returncode = 0
        elif cmd == "patch":
            r.returncode = 0
        elif cmd == "python3" and "run_eval.py" in " ".join(args):
            # rc=2 = crash (not 0 or 1)
            r.returncode = 2
            r.stderr = "ModuleNotFoundError: no module named 'foo'"
        else:
            r.returncode = 0
        return r

    with patch("subprocess.run", side_effect=mock_subprocess_run):
        result = proposer.sandbox_patch(cluster, patch_proposal)

    assert result.patch_applies is True
    assert result.dry_run_passed is False
    assert "rc=2" in result.error


# ── Draft PR tests ────────────────────────────────────────────────────────────


def test_open_draft_pr_uses_draft_flag(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_forbidden_keywords_hit",
        members=[FailureRecord("gs20_03", "cp_keyword_match", "Forbidden keywords", "", "2026-04-14")] * 3,
        fixture_tags=["cross-vendor"],
        source_files=[],
    )
    patch_proposal = PatchProposal(
        diff="--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,1 @@\n-old\n+new",
        model="claude-sonnet-4-6",
        input_tokens=200,
    )
    sandbox = SandboxResult(patch_applies=True, dry_run_passed=True)

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="test-token")

    captured_cmds: list[list[str]] = []

    def mock_run(args: list[str], **kwargs: object) -> MagicMock:
        captured_cmds.append(list(args))
        r = MagicMock()
        r.returncode = 0
        r.stdout = "https://github.com/owner/repo/pull/999"
        r.stderr = ""
        return r

    with patch("subprocess.run", side_effect=mock_run):
        pr_url = proposer.open_draft_pr(cluster, patch_proposal, sandbox)

    assert pr_url == "https://github.com/owner/repo/pull/999"

    # Find the gh pr create call
    gh_call = next((c for c in captured_cmds if c[0] == "gh" and "create" in c), None)
    assert gh_call is not None
    assert "--draft" in gh_call


def test_open_draft_pr_labels_and_assignee(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_forbidden_keywords_hit",
        members=[FailureRecord("gs20_03", "cp_keyword_match", "Forbidden keywords", "", "2026-04-14")] * 3,
        fixture_tags=["cross-vendor"],
    )
    patch_proposal = PatchProposal(
        diff="--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,1 @@\n-old\n+new",
        model="claude-sonnet-4-6",
        input_tokens=100,
    )
    sandbox = SandboxResult(patch_applies=True, dry_run_passed=True)

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="tok")

    captured_cmds: list[list[str]] = []

    def mock_run(args: list[str], **kwargs: object) -> MagicMock:
        captured_cmds.append(list(args))
        r = MagicMock()
        r.returncode = 0
        r.stdout = "https://github.com/owner/repo/pull/1000"
        r.stderr = ""
        return r

    with patch("subprocess.run", side_effect=mock_run):
        proposer.open_draft_pr(cluster, patch_proposal, sandbox)

    gh_call = next((c for c in captured_cmds if c[0] == "gh" and "create" in c), None)
    assert gh_call is not None
    assert "--label" in gh_call
    label_idx = gh_call.index("--label")
    labels_str = gh_call[label_idx + 1]
    assert "auto-generated" in labels_str
    assert "needs-human-review" in labels_str
    assert "--assignee" in gh_call


def test_open_draft_pr_adds_blocked_regression_label_on_sandbox_failure(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_forbidden_keywords_hit",
        members=[FailureRecord("s1", "cp_keyword_match", "reason", "", "2026-04-14")] * 3,
    )
    patch_proposal = PatchProposal(
        diff="--- a/f.py\n+++ b/f.py\n@@ -1,1 +1,1 @@\n-old\n+new",
        model="claude-sonnet-4-6",
        input_tokens=100,
    )
    sandbox = SandboxResult(patch_applies=True, dry_run_passed=False, error="eval crash")

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="tok")
    captured_cmds: list[list[str]] = []

    def mock_run(args: list[str], **kwargs: object) -> MagicMock:
        captured_cmds.append(list(args))
        r = MagicMock()
        r.returncode = 0
        r.stdout = "https://github.com/owner/repo/pull/1001"
        r.stderr = ""
        return r

    with patch("subprocess.run", side_effect=mock_run):
        proposer.open_draft_pr(cluster, patch_proposal, sandbox)

    gh_call = next((c for c in captured_cmds if c[0] == "gh" and "create" in c), None)
    assert gh_call is not None
    label_idx = gh_call.index("--label")
    labels_str = gh_call[label_idx + 1]
    assert "blocked:regression" in labels_str


# ── Max PRs per run tests ─────────────────────────────────────────────────────


def test_max_prs_per_run_honored(tmp_path: Path) -> None:
    """When max_prs=2 and 3 clusters qualify, only 2 PRs are opened."""
    scorecards_dir = tmp_path / "runs"
    scorecards_dir.mkdir()
    fixtures_dir = tmp_path / "fixtures"
    fixtures_dir.mkdir()

    # Three different signatures, each appearing 3 times
    sigs = ["cp_forbidden_keywords_hit", "cp_keyword_match_no_honesty_signal", "cp_keyword_match_no_safety_terms"]
    bodies = {
        "cp_forbidden_keywords_hit": "Forbidden keywords present: ['PowerFlex']",
        "cp_keyword_match_no_honesty_signal": "No honesty signal — possible hallucination",
        "cp_keyword_match_no_safety_terms": "No safety terms in response",
    }

    for date in ["2026-04-12", "2026-04-13", "2026-04-14"]:
        failure_blocks = "\n".join(
            f"### scenario_{i:02d}\n"
            f"- **cp_keyword_match** FAILED: {reason}\n"
            f"- Last response: `response`\n"
            for i, (_, reason) in enumerate(bodies.items())
        )
        (scorecards_dir / f"{date}.md").write_text(
            f"# MIRA Eval Scorecard — {date}\n\n## Failures\n\n{failure_blocks}\n---\n"
        )

    proposer = FixProposer(
        scorecards_dir=scorecards_dir,
        repo_path=tmp_path,
        gh_token="tok",
    )
    proposer.fixtures_dir = fixtures_dir
    proposer.max_prs = 2

    pr_count = 0

    def mock_run_pipeline(days: int = 7, dry_run: bool = False) -> list[str]:
        return [f"https://github.com/owner/repo/pull/{i}" for i in range(pr_count)]

    records = proposer.load_recent_scorecards(days=30)
    clusters = proposer.cluster_failures(records)

    # Should have 3 clusters, but we'll only process max_prs=2
    assert len(clusters) >= 2
    processed = clusters[: proposer.max_prs]
    assert len(processed) == 2


# ── Disabled env var tests ────────────────────────────────────────────────────


def test_disabled_env_var_skips_run(tmp_path: Path) -> None:
    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")

    with patch.dict("os.environ", {"FIX_PROPOSER_DISABLED": "1"}):
        result = proposer.run(days=7, dry_run=False)

    assert result == []


def test_run_returns_empty_when_no_scorecards(tmp_path: Path) -> None:
    scorecards_dir = tmp_path / "runs"
    scorecards_dir.mkdir()

    proposer = FixProposer(
        scorecards_dir=scorecards_dir,
        repo_path=tmp_path,
        gh_token="",
    )
    result = proposer.run(days=7)
    assert result == []


# ── Dry-run report test ───────────────────────────────────────────────────────


def test_dry_run_report_written_to_disk(tmp_path: Path) -> None:
    cluster = FailureCluster(
        signature="cp_keyword_match_no_match",
        members=[
            FailureRecord("doc_intent_pilz_11", "cp_keyword_match", "No match from ['pilz.com']", "", "2026-04-14"),
        ] * 3,
        fixture_tags=["documentation", "pilz"],
        source_files=["mira-bots/shared/guardrails.py"],
    )
    output = tmp_path / "dryrun.md"

    proposer = FixProposer(scorecards_dir=tmp_path, repo_path=tmp_path, gh_token="")
    proposer.dry_run_report([cluster], output)

    assert output.exists()
    content = output.read_text()
    assert "cp_keyword_match_no_match" in content
    assert "doc_intent_pilz_11" in content
    assert "documentation" in content
