#!/usr/bin/env python3
"""MIRA AR HUD Simulator — Phase 1 laptop webcam prototype.

Opens the laptop webcam and composites an AR heads-up display overlay showing
step-by-step maintenance instructions. Steps can be generated by Claude API
or loaded from a pre-baked JSON procedure file.

Controls:
    SPACE  — advance to next step
    R      — reset to step 1
    G      — generate new procedure via Claude API
    F      — toggle fullscreen
    Q/ESC  — quit

Usage:
    python mira_demo.py                                        # use default procedure
    python mira_demo.py --procedure procedures/press_unit_4.json  # load specific procedure
    python mira_demo.py --generate "Conveyor belt tensioning"     # generate via Claude API
    python mira_demo.py --camera 1                                # use camera index 1

Environment:
    ANTHROPIC_API_KEY — required for --generate mode
"""

import argparse
import json
import sys
import time
from pathlib import Path

import cv2
import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
DEFAULT_PROCEDURE = HERE / "procedures" / "press_unit_4.json"

# --- Colors (BGR for OpenCV) ---
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
GREEN = (0, 220, 100)
CYAN = (220, 200, 0)
GRAY = (160, 160, 160)
DARK_GRAY = (80, 80, 80)
ORANGE = (0, 140, 255)
RED = (60, 60, 220)

# --- HUD layout constants ---
TOP_BAR_H = 48
BOTTOM_CARD_H = 140
PROGRESS_BAR_H = 40
CARD_MARGIN = 40
CARD_PADDING = 16
ALPHA_OVERLAY = 0.65


def load_procedure(path: Path) -> dict:
    """Load a procedure from a JSON file."""
    with open(path) as f:
        return json.load(f)


def generate_procedure_claude(task_name: str) -> dict:
    """Generate a 6-step maintenance procedure via Claude API."""
    try:
        import anthropic
    except ImportError:
        print("ERROR: anthropic package required for --generate. Run: pip install anthropic")
        sys.exit(1)

    api_key = None
    import os
    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY environment variable required for --generate")
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)
    response = client.messages.create(
        model="claude-sonnet-4-20250514",
        max_tokens=1024,
        system=(
            "You are MIRA, an industrial maintenance AI. Generate a 6-step maintenance "
            "procedure for the given task. Return ONLY valid JSON with this exact structure: "
            '{"task": "...", "equipment_id": "...", "steps": [{"step": 1, "title": "...", '
            '"detail": "..."}]}. Each title should be under 6 words. Each detail should be '
            "one concise sentence under 15 words. Exactly 6 steps."
        ),
        messages=[{"role": "user", "content": f"Generate a maintenance procedure for: {task_name}"}],
    )

    text = response.content[0].text.strip()
    # Handle markdown code fences if Claude wraps the JSON
    if text.startswith("```"):
        lines = text.split("\n")
        text = "\n".join(lines[1:-1])
    return json.loads(text)


def get_font(size: int) -> ImageFont.FreeTypeFont:
    """Get a clean font, falling back through common system fonts."""
    candidates = [
        "C:/Windows/Fonts/segoeui.ttf",       # Windows
        "C:/Windows/Fonts/consola.ttf",        # Windows monospace
        "/System/Library/Fonts/SFNSMono.ttf",  # macOS
        "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",  # Linux
    ]
    for path in candidates:
        if Path(path).exists():
            return ImageFont.truetype(path, size)
    return ImageFont.load_default()


def pil_to_cv2(pil_img: Image.Image) -> np.ndarray:
    """Convert PIL RGBA image to OpenCV BGR numpy array."""
    return cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGBA_TO_BGRA)


def draw_text_pil(
    frame: np.ndarray,
    text: str,
    pos: tuple[int, int],
    font: ImageFont.FreeTypeFont,
    color: tuple[int, int, int] = (255, 255, 255),
) -> np.ndarray:
    """Draw anti-aliased text onto an OpenCV frame using Pillow."""
    pil_img = Image.fromarray(cv2.cvtColor(frame, cv2.COLOR_BGR2RGB))
    draw = ImageDraw.Draw(pil_img)
    draw.text(pos, text, font=font, fill=color)
    return cv2.cvtColor(np.array(pil_img), cv2.COLOR_RGB2BGR)


def draw_hud(
    frame: np.ndarray,
    steps: list[dict],
    current_step: int,
    elapsed: float,
    task_name: str,
    completed: bool,
) -> np.ndarray:
    """Composite the AR HUD overlay onto the camera frame."""
    h, w = frame.shape[:2]
    overlay = frame.copy()
    output = frame.copy()

    font_title = get_font(22)
    font_body = get_font(17)
    font_small = get_font(14)
    font_large = get_font(28)

    # --- Top bar ---
    cv2.rectangle(overlay, (0, 0), (w, TOP_BAR_H), BLACK, -1)

    # --- Bottom card area ---
    card_top = h - BOTTOM_CARD_H - PROGRESS_BAR_H
    cv2.rectangle(overlay, (0, card_top), (w, h), BLACK, -1)

    # Blend overlay
    cv2.addWeighted(overlay, ALPHA_OVERLAY, output, 1 - ALPHA_OVERLAY, 0, output)

    # --- Top bar text ---
    minutes = int(elapsed) // 60
    seconds = int(elapsed) % 60
    time_str = f"{minutes:02d}:{seconds:02d}"

    output = draw_text_pil(output, "MIRA", (16, 12), font_title, (0, 220, 200))
    output = draw_text_pil(output, "|", (80, 12), font_title, (100, 100, 100))
    output = draw_text_pil(output, "CRANE SYNC CORP", (100, 14), font_body, (180, 180, 180))
    output = draw_text_pil(output, time_str, (w - 80, 14), font_body, (180, 180, 180))

    # --- Thin accent line under top bar ---
    cv2.line(output, (0, TOP_BAR_H), (w, TOP_BAR_H), CYAN, 1)

    if completed:
        # --- Completion screen ---
        output = draw_text_pil(
            output, "PROCEDURE COMPLETE", (w // 2 - 160, card_top + 20), font_large, (0, 220, 100)
        )
        output = draw_text_pil(
            output,
            f"All {len(steps)} steps finished in {time_str}",
            (w // 2 - 140, card_top + 60),
            font_body,
            (180, 180, 180),
        )
        output = draw_text_pil(
            output, "[R] Restart   [Q] Quit", (w // 2 - 100, card_top + 90), font_small, (120, 120, 120)
        )
    else:
        # --- Step card ---
        step_data = steps[current_step]
        step_num = current_step + 1
        total = len(steps)

        # Step counter
        output = draw_text_pil(
            output,
            f"STEP {step_num} OF {total}",
            (CARD_MARGIN, card_top + CARD_PADDING),
            font_small,
            (0, 200, 200),
        )

        # Step title
        title = step_data["title"]
        output = draw_text_pil(
            output,
            f"> {title}",
            (CARD_MARGIN, card_top + CARD_PADDING + 28),
            font_title,
            (255, 255, 255),
        )

        # Step detail
        detail = step_data["detail"]
        output = draw_text_pil(
            output,
            f"  {detail}",
            (CARD_MARGIN, card_top + CARD_PADDING + 58),
            font_body,
            (180, 180, 180),
        )

    # --- Progress bar (bottom) ---
    progress_top = h - PROGRESS_BAR_H
    cv2.line(output, (0, progress_top), (w, progress_top), DARK_GRAY, 1)

    # Progress dots
    total = len(steps)
    dot_spacing = 28
    dots_width = total * dot_spacing
    dot_start_x = CARD_MARGIN
    dot_y = progress_top + PROGRESS_BAR_H // 2

    for i in range(total):
        cx = dot_start_x + i * dot_spacing + dot_spacing // 2
        if i < current_step:
            # Completed — filled green
            cv2.circle(output, (cx, dot_y), 8, GREEN, -1)
            output = draw_text_pil(output, "v", (cx - 5, dot_y - 9), font_small, (0, 0, 0))
        elif i == current_step and not completed:
            # Current — filled cyan with arrow
            cv2.circle(output, (cx, dot_y), 9, CYAN, -1)
            output = draw_text_pil(output, ">", (cx - 5, dot_y - 9), font_small, (0, 0, 0))
        else:
            # Future — empty
            cv2.circle(output, (cx, dot_y), 8, GRAY, 1)

    # Hint text (right side)
    if not completed:
        hint = "[SPACE] Next Step"
        output = draw_text_pil(output, hint, (w - 200, progress_top + 10), font_small, (120, 120, 120))

    # Task name (center-ish of progress bar)
    task_short = task_name[:40] + ("..." if len(task_name) > 40 else "")
    output = draw_text_pil(
        output, task_short, (dot_start_x + dots_width + 20, progress_top + 10), font_small, (100, 100, 100)
    )

    return output


def main():
    parser = argparse.ArgumentParser(description="MIRA AR HUD Simulator")
    parser.add_argument(
        "--procedure", type=Path, default=DEFAULT_PROCEDURE, help="Path to procedure JSON file"
    )
    parser.add_argument("--generate", type=str, default=None, help="Generate procedure via Claude API")
    parser.add_argument("--camera", type=int, default=0, help="Camera index (default: 0)")
    parser.add_argument("--width", type=int, default=1280, help="Requested camera width")
    parser.add_argument("--height", type=int, default=720, help="Requested camera height")
    args = parser.parse_args()

    # Load or generate procedure
    if args.generate:
        print(f"Generating procedure for: {args.generate}")
        procedure = generate_procedure_claude(args.generate)
        # Cache it
        cache_path = HERE / "procedures" / f"{args.generate.lower().replace(' ', '_')[:30]}.json"
        cache_path.parent.mkdir(parents=True, exist_ok=True)
        with open(cache_path, "w") as f:
            json.dump(procedure, f, indent=2)
        print(f"Cached to: {cache_path}")
    else:
        if not args.procedure.exists():
            print(f"ERROR: Procedure file not found: {args.procedure}")
            print("Use --generate 'task name' to create one via Claude API")
            sys.exit(1)
        procedure = load_procedure(args.procedure)

    steps = procedure["steps"]
    task_name = procedure.get("task", "Maintenance Procedure")
    print(f"Loaded: {task_name} ({len(steps)} steps)")

    # Open webcam
    cap = cv2.VideoCapture(args.camera)
    if not cap.isOpened():
        print(f"ERROR: Cannot open camera {args.camera}")
        sys.exit(1)

    cap.set(cv2.CAP_PROP_FRAME_WIDTH, args.width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, args.height)

    actual_w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    actual_h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    print(f"Camera: {actual_w}x{actual_h}")

    # Window
    window_name = "MIRA AR HUD"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    cv2.resizeWindow(window_name, actual_w, actual_h)

    current_step = 0
    completed = False
    fullscreen = False
    start_time = time.time()

    print("Controls: SPACE=next  R=reset  G=generate  F=fullscreen  Q=quit")

    while True:
        ret, frame = cap.read()
        if not ret:
            print("Camera read failed")
            break

        elapsed = time.time() - start_time
        output = draw_hud(frame, steps, current_step, elapsed, task_name, completed)

        cv2.imshow(window_name, output)

        key = cv2.waitKey(1) & 0xFF

        if key == ord("q") or key == 27:  # Q or ESC
            break
        elif key == ord(" "):  # SPACE — advance
            if not completed:
                current_step += 1
                if current_step >= len(steps):
                    completed = True
                    print(f"Procedure complete in {int(elapsed)}s")
        elif key == ord("r"):  # R — reset
            current_step = 0
            completed = False
            start_time = time.time()
            print("Reset to step 1")
        elif key == ord("f"):  # F — fullscreen toggle
            fullscreen = not fullscreen
            if fullscreen:
                cv2.setWindowProperty(window_name, cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_FULLSCREEN)
            else:
                cv2.setWindowProperty(window_name, cv2.WND_PROP_FULLSCREEN, cv2.WINDOW_NORMAL)
        elif key == ord("g"):  # G — generate new procedure
            task = input("Enter task name: ").strip()
            if task:
                print(f"Generating: {task}")
                procedure = generate_procedure_claude(task)
                steps = procedure["steps"]
                task_name = procedure.get("task", task)
                current_step = 0
                completed = False
                start_time = time.time()
                print(f"Loaded: {task_name} ({len(steps)} steps)")

    cap.release()
    cv2.destroyAllWindows()


if __name__ == "__main__":
    main()
