BEGIN;

-- ─── approved_tags — Sparkplug B allowlist seed (ConveyorEdge/Conv_Simple) ────────────
--
-- GENERATED by tools/seeds/gen_approved_tags_sparkplug.py — DO NOT EDIT BY HAND.
-- Re-run the generator after the node's BIRTH metric set changes.
--
-- Seeds the per-tenant fail-closed allowlist the relay enforces before
-- persisting to tag_events + live_signal_cache. Without it every Sparkplug
-- metric from this edge bounces (silently — zero rows, no error).
--
-- KEY MATCH — the relay matches normalize_tag_path(group/edge/device/metric)
-- against normalized_tag_path. These rows are generated with the SAME
-- mqtt_ingest path-builder + normalizer the live subscriber uses, so they agree.
--
-- TENANT — __TENANT_ID__ placeholder — substitute the real tenant UUID at apply time
-- source_system = 'ignition' (a Sparkplug edge IS the Ignition UNS arriving).
-- Idempotent — ON CONFLICT … DO UPDATE.

INSERT INTO approved_tags
  (tenant_id, source_system, source_tag_path, normalized_tag_path, uns_path, enabled, notes)
VALUES
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Amber_LED_Flash', 'factorylm_conveyoredge_conv_simple_conveyor_amber_led_flash', 'enterprise.home_garage.conveyor_lab.conveyor_1.status.amber_led_flash'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Discharge_Accepted', 'factorylm_conveyoredge_conv_simple_conveyor_discharge_accepted', 'enterprise.home_garage.conveyor_lab.conveyor_1.discharge.accepted'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Discharge_Complete', 'factorylm_conveyoredge_conv_simple_conveyor_discharge_complete', 'enterprise.home_garage.conveyor_lab.conveyor_1.discharge.complete'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Discharge_Fault', 'factorylm_conveyoredge_conv_simple_conveyor_discharge_fault', 'enterprise.home_garage.conveyor_lab.conveyor_1.discharge.timeout_fault'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Discharge_Pending', 'factorylm_conveyoredge_conv_simple_conveyor_discharge_pending', 'enterprise.home_garage.conveyor_lab.conveyor_1.discharge.pending_acceptance'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Discharge_Request', 'factorylm_conveyoredge_conv_simple_conveyor_discharge_request', 'enterprise.home_garage.conveyor_lab.conveyor_1.discharge.request'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Motor_Running', 'factorylm_conveyoredge_conv_simple_conveyor_motor_running', 'enterprise.home_garage.conveyor_lab.conveyor_1.status.motor_running'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Photo_Eye', 'factorylm_conveyoredge_conv_simple_conveyor_photo_eye', 'enterprise.home_garage.conveyor_lab.conveyor_1.status.photo_eye'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/Start_PB', 'factorylm_conveyoredge_conv_simple_conveyor_start_pb', 'enterprise.home_garage.conveyor_lab.conveyor_1.status.start_button'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/VFD_Comm_OK', 'factorylm_conveyoredge_conv_simple_conveyor_vfd_comm_ok', 'enterprise.home_garage.conveyor_lab.conveyor_1.status.vfd_comm_ok'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py'),
  ('__TENANT_ID__'::uuid, 'ignition', 'FactoryLM/ConveyorEdge/Conv_Simple/Conveyor/VFD_Hz', 'factorylm_conveyoredge_conv_simple_conveyor_vfd_hz', 'enterprise.home_garage.conveyor_lab.conveyor_1.process.vfd_frequency_hz'::ltree, true, 'Sparkplug ConveyorEdge/Conv_Simple — generated by gen_approved_tags_sparkplug.py')
ON CONFLICT (tenant_id, source_system, source_tag_path) DO UPDATE
  SET normalized_tag_path = EXCLUDED.normalized_tag_path,
      uns_path = EXCLUDED.uns_path,
      enabled = true,
      notes = EXCLUDED.notes,
      updated_at = now();

COMMIT;
