BEGIN;

-- ─── approved_tags — Northwind / Discharge Conveyor CV-200 allowlist seed ────
--
-- SEPARATE from the garage seed (tools/seeds/approved_tags_conveyor.sql) — that
-- one stays bound to enterprise.home_garage.conveyor_lab.conveyor_1 and is NOT
-- touched. This file ADDS a Northwind-tenant allowlist for the SAME physical rig
-- (Micro820 + GS10), mapped onto the CV-200 UNS subtree. Both tenants' allowlists
-- coexist (PK is (tenant_id, source_system, source_tag_path)); the gateway timer
-- publishes the rig tags a SECOND time as the Northwind tenant — ADD, never
-- repoint. See docs/handoffs/2026-06-28-plc-laptop-northwind-cv200-perspective.md.
--
-- Seeds the per-tenant SECURITY allowlist the mira-relay ingest endpoint
-- (POST /api/v1/tags/ingest) enforces FAIL-CLOSED before persisting tag readings
-- to tag_events + live_signal_cache. Without this seed every HMAC-signed batch
-- from the Ignition tag-stream timer (as the Northwind tenant) is rejected and
-- the CV-200 tile never gets a fresh live_signal_cache row → freshness dot gray.
--
-- KEY MATCH — the relay's hot-path query is
--   WHERE tenant_id=? AND source_system=? AND normalized_tag_path=? AND enabled=true
-- so normalized_tag_path MUST equal what mira-relay/tag_ingest.normalize_tag_path
-- produces. These values are byte-identical to the garage seed's (same rig tags,
-- same source paths) — only uns_path + notes differ. Pinned by
-- tests/test_northwind_cv200_seed_and_config.py.
--
-- UNS subtree — every row points at the CV-200 dotted ltree path so the Command
-- Center freshness rollup picks them up under the CV-200 node (the binding key).
--
-- TENANT — __TENANT_ID__ placeholder is replaced at apply time (apply-seeds.yml /
-- a -v override) with the Northwind tenant UUID 00000000-0000-0000-0000-0000000000b1.
--
-- Idempotent — re-running is safe via ON CONFLICT … DO UPDATE SET enabled=true.

INSERT INTO approved_tags
  (tenant_id, source_system, source_tag_path, normalized_tag_path, uns_path, enabled, notes)
VALUES
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/State',           'default_mira_monitored_conveyor_demo_state',           'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Motor_Running',   'default_mira_monitored_conveyor_demo_motor_running',   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/EStop_Active',    'default_mira_monitored_conveyor_demo_estop_active',    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Fault_Alarm',     'default_mira_monitored_conveyor_demo_fault_alarm',     'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Motor_Current_A', 'default_mira_monitored_conveyor_demo_motor_current_a', 'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/VFD_Hz',          'default_mira_monitored_conveyor_demo_vfd_hz',          'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Cycle_Counter',   'default_mira_monitored_conveyor_demo_cycle_counter',   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Motor_Running',                       'default_conveyor_motor_running',                       'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Conveyor_Running',                    'default_conveyor_conveyor_running',                    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Fault_Alarm',                         'default_conveyor_fault_alarm',                         'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Comm_OK',                         'default_conveyor_vfd_comm_ok',                         'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/System_Ready',                        'default_conveyor_system_ready',                        'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/EStop_Active',                        'default_conveyor_estop_active',                        'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Dir_FWD',                             'default_conveyor_dir_fwd',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Dir_REV',                             'default_conveyor_dir_rev',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Heartbeat',                           'default_conveyor_heartbeat',                           'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/EStop_Wiring_Fault',                  'default_conveyor_estop_wiring_fault',                  'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Dir_Fault',                           'default_conveyor_dir_fault',                           'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I00',                             'default_conveyor_raw_i00',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I01',                             'default_conveyor_raw_i01',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I02',                             'default_conveyor_raw_i02',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I03',                             'default_conveyor_raw_i03',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I04',                             'default_conveyor_raw_i04',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O00',                             'default_conveyor_raw_o00',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O01',                             'default_conveyor_raw_o01',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O02',                             'default_conveyor_raw_o02',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O03',                             'default_conveyor_raw_o03',                             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Poll_Active',                     'default_conveyor_vfd_poll_active',                     'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Fault_Reset_Pending',             'default_conveyor_vfd_fault_reset_pending',             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_OutputFreq_Raw',                  'default_conveyor_vfd_outputfreq_raw',                  'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_OutputCurrent_Raw',               'default_conveyor_vfd_outputcurrent_raw',               'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_DCBusVoltage_Raw',                'default_conveyor_vfd_dcbusvoltage_raw',                'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_DCBus_Raw',                       'default_conveyor_vfd_dcbus_raw',                       'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_FaultCode',                       'default_conveyor_vfd_faultcode',                       'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Error_Code',                          'default_conveyor_error_code',                          'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Item_Count',                          'default_conveyor_item_count',                          'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Uptime_Seconds',                      'default_conveyor_uptime_seconds',                      'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Speed_Cmd',                           'default_conveyor_speed_cmd',                           'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Conv_State',                          'default_conveyor_conv_state',                          'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_CmdWord',                         'default_conveyor_vfd_cmdword',                         'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_FreqSetpoint_Raw',                'default_conveyor_vfd_freqsetpoint_raw',                'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Poll_Step',                       'default_conveyor_vfd_poll_step',                       'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Hz',                              'default_conveyor_vfd_hz',                              'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Amps',                            'default_conveyor_vfd_amps',                            'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_DCBus_V',                         'default_conveyor_vfd_dcbus_v',                         'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Setpoint_Hz',                     'default_conveyor_vfd_setpoint_hz',                     'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_02',                    'default_mira_iocheck_inputs_di_02',                    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_05',                    'default_mira_iocheck_inputs_di_05',                    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Outputs/DO_02',                   'default_mira_iocheck_outputs_do_02',                   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/pe_latched',                  'default_mira_iocheck_vfd_pe_latched',                  'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_cmd_word',                'default_mira_iocheck_vfd_vfd_cmd_word',                'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_comm_ok',                 'default_mira_iocheck_vfd_vfd_comm_ok',                 'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_current',                 'default_mira_iocheck_vfd_vfd_current',                 'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_dc_bus',                  'default_mira_iocheck_vfd_vfd_dc_bus',                  'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_fault_code',              'default_mira_iocheck_vfd_vfd_fault_code',              'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_freq_sp',                 'default_mira_iocheck_vfd_vfd_freq_sp',                 'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_frequency',               'default_mira_iocheck_vfd_vfd_frequency',               'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_status_word',             'default_mira_iocheck_vfd_vfd_status_word',             'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — approved_tags_northwind_cv200.sql 2026-06-28'),
  -- ── added 2026-06-28: 11 MIRA_IOCheck tags the staged NorthwindBottling Perspective project binds ──
  -- These were missing from the initial seed; without them the relay drops them fail-closed and the
  -- CV-200 view's inputs/outputs/motor-rpm/power/torque/warn-code panels show no live data.
  -- Pinned against the project's actual bindings by tests/test_northwind_cv200_seed_and_config.py.
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_00',                    'default_mira_iocheck_inputs_di_00',                    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_01',                    'default_mira_iocheck_inputs_di_01',                    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_04',                    'default_mira_iocheck_inputs_di_04',                    'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Outputs/DO_00',                   'default_mira_iocheck_outputs_do_00',                   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Outputs/DO_01',                   'default_mira_iocheck_outputs_do_01',                   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Outputs/DO_03',                   'default_mira_iocheck_outputs_do_03',                   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_freq_cmd',                'default_mira_iocheck_vfd_vfd_freq_cmd',                'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_motor_rpm',               'default_mira_iocheck_vfd_vfd_motor_rpm',               'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_power',                   'default_mira_iocheck_vfd_vfd_power',                   'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_torque',                  'default_mira_iocheck_vfd_vfd_torque',                  'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_warn_code',               'default_mira_iocheck_vfd_vfd_warn_code',               'enterprise.riverside.area.packaging.line.line1.equipment.discharge_conveyor_cv200'::ltree, true, 'Northwind CV-200 live rig — staged Perspective binding 2026-06-28')

ON CONFLICT (tenant_id, source_system, source_tag_path) DO UPDATE
  SET normalized_tag_path = EXCLUDED.normalized_tag_path,
      uns_path = EXCLUDED.uns_path,
      enabled = true,
      notes = EXCLUDED.notes,
      updated_at = now();

COMMIT;
