BEGIN;

-- ─── approved_tags — Home Garage Conveyor allowlist seed ────────────────────
--
-- Seeds the per-tenant SECURITY allowlist the mira-relay ingest endpoint
-- (POST /api/v1/tags/ingest) enforces FAIL-CLOSED before persisting tag
-- readings to `tag_events` + `live_signal_cache`. Without this seed, every
-- HMAC-signed batch from the Ignition tag-stream timer is rejected and the
-- Command Center conveyor tile never gets a fresh row in `live_signal_cache`
-- → freshness dot stays gray.
--
-- Source of truth: `ignition/project/approved_tags.json` (57 entries, gateway-
-- side allowlist deployed by deploy_ignition.ps1). This seed mirrors the same
-- list per-tenant in NeonDB so the relay enforces defense-in-depth on the way
-- in.
--
-- KEY MATCH — the relay's hot-path query is
--   WHERE tenant_id=? AND source_system=? AND normalized_tag_path=? AND enabled=true
-- so `normalized_tag_path` MUST match what `mira-relay/tag_ingest.normalize_tag_path`
-- produces (lowercase, runs of [^a-z0-9]+ → '_', trim '_'). The values below
-- were generated by applying that exact regex to each raw path.
--
-- UNS subtree — every row points at `enterprise.home_garage.conveyor_lab.conveyor_1`
-- so the Command Center freshness rollup picks them up under the conveyor's
-- UNS node. Finer per-component mapping (gs10_vfd / micro820_plc / photoeye_1)
-- is a follow-up; subtree match works either way.
--
-- TENANT — `__TENANT_ID__` placeholder is replaced at apply time by
-- apply-seeds.yml from the workflow's `tenant_id_uuid` input (NOT the legacy
-- text tenant slug used by KB seeds).
--
-- Idempotent — re-running is safe via `ON CONFLICT … DO UPDATE SET enabled=true`.

INSERT INTO approved_tags
  (tenant_id, source_system, source_tag_path, normalized_tag_path, uns_path, enabled, notes)
VALUES
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/State',           'default_mira_monitored_conveyor_demo_state',           'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Motor_Running',   'default_mira_monitored_conveyor_demo_motor_running',   'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/EStop_Active',    'default_mira_monitored_conveyor_demo_estop_active',    'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Fault_Alarm',     'default_mira_monitored_conveyor_demo_fault_alarm',     'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Motor_Current_A', 'default_mira_monitored_conveyor_demo_motor_current_a', 'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/VFD_Hz',          'default_mira_monitored_conveyor_demo_vfd_hz',          'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Mira_Monitored/conveyor_demo/Cycle_Counter',   'default_mira_monitored_conveyor_demo_cycle_counter',   'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Motor_Running',                       'default_conveyor_motor_running',                       'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Conveyor_Running',                    'default_conveyor_conveyor_running',                    'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Fault_Alarm',                         'default_conveyor_fault_alarm',                         'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Comm_OK',                         'default_conveyor_vfd_comm_ok',                         'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/System_Ready',                        'default_conveyor_system_ready',                        'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/EStop_Active',                        'default_conveyor_estop_active',                        'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Dir_FWD',                             'default_conveyor_dir_fwd',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Dir_REV',                             'default_conveyor_dir_rev',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Heartbeat',                           'default_conveyor_heartbeat',                           'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/EStop_Wiring_Fault',                  'default_conveyor_estop_wiring_fault',                  'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Dir_Fault',                           'default_conveyor_dir_fault',                           'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I00',                             'default_conveyor_raw_i00',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I01',                             'default_conveyor_raw_i01',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I02',                             'default_conveyor_raw_i02',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I03',                             'default_conveyor_raw_i03',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_I04',                             'default_conveyor_raw_i04',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O00',                             'default_conveyor_raw_o00',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O01',                             'default_conveyor_raw_o01',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O02',                             'default_conveyor_raw_o02',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Raw_O03',                             'default_conveyor_raw_o03',                             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Poll_Active',                     'default_conveyor_vfd_poll_active',                     'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Fault_Reset_Pending',             'default_conveyor_vfd_fault_reset_pending',             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_OutputFreq_Raw',                  'default_conveyor_vfd_outputfreq_raw',                  'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_OutputCurrent_Raw',               'default_conveyor_vfd_outputcurrent_raw',               'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_DCBusVoltage_Raw',                'default_conveyor_vfd_dcbusvoltage_raw',                'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_DCBus_Raw',                       'default_conveyor_vfd_dcbus_raw',                       'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_FaultCode',                       'default_conveyor_vfd_faultcode',                       'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Error_Code',                          'default_conveyor_error_code',                          'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Item_Count',                          'default_conveyor_item_count',                          'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Uptime_Seconds',                      'default_conveyor_uptime_seconds',                      'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Speed_Cmd',                           'default_conveyor_speed_cmd',                           'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/Conv_State',                          'default_conveyor_conv_state',                          'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_CmdWord',                         'default_conveyor_vfd_cmdword',                         'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_FreqSetpoint_Raw',                'default_conveyor_vfd_freqsetpoint_raw',                'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Poll_Step',                       'default_conveyor_vfd_poll_step',                       'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Hz',                              'default_conveyor_vfd_hz',                              'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Amps',                            'default_conveyor_vfd_amps',                            'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_DCBus_V',                         'default_conveyor_vfd_dcbus_v',                         'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]Conveyor/VFD_Setpoint_Hz',                     'default_conveyor_vfd_setpoint_hz',                     'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_02',                    'default_mira_iocheck_inputs_di_02',                    'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Inputs/DI_05',                    'default_mira_iocheck_inputs_di_05',                    'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/Outputs/DO_02',                   'default_mira_iocheck_outputs_do_02',                   'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/pe_latched',                  'default_mira_iocheck_vfd_pe_latched',                  'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_cmd_word',                'default_mira_iocheck_vfd_vfd_cmd_word',                'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_comm_ok',                 'default_mira_iocheck_vfd_vfd_comm_ok',                 'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_current',                 'default_mira_iocheck_vfd_vfd_current',                 'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_dc_bus',                  'default_mira_iocheck_vfd_vfd_dc_bus',                  'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_fault_code',              'default_mira_iocheck_vfd_vfd_fault_code',              'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_freq_sp',                 'default_mira_iocheck_vfd_vfd_freq_sp',                 'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_frequency',               'default_mira_iocheck_vfd_vfd_frequency',               'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07'),
  ('__TENANT_ID__'::uuid, 'ignition', '[default]MIRA_IOCheck/VFD/vfd_status_word',             'default_mira_iocheck_vfd_vfd_status_word',             'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'Seeded by approved_tags_conveyor.sql 2026-06-07')
ON CONFLICT (tenant_id, source_system, source_tag_path) DO UPDATE
  SET normalized_tag_path = EXCLUDED.normalized_tag_path,
      uns_path = EXCLUDED.uns_path,
      enabled = true,
      notes = EXCLUDED.notes,
      updated_at = now();

COMMIT;
