BEGIN;

-- ─── approved_tags — FactoryLM PLC-bridge canonical tag allowlist (PRD #3048) ─
--
-- Seeds the per-tenant fail-closed allowlist `mira-relay/tag_ingest.ingest_batch`
-- enforces before persisting to tag_events + live_signal_cache. Without this
-- seed a valid factorylm.machine-snapshot.v1 envelope is accepted with
-- accepted=0 and every tag rejected as not_allowlisted — the handoff would
-- look wired end-to-end and deliver nothing (see the PRD's amended § "The
-- allowlist is fail-closed — seeding is a prerequisite, not a detail").
--
-- SOURCE — the 7 canonical FactoryLM PLC tags named in the PRD ("Existing
-- canonical tag vocabulary", docs/prd/2026-08-01-mira-factorylm-machine-evidence-handoff.md),
-- produced by FactoryLM's services/plc-modbus/src/factorylm_plc/modbus_tag_source.py
-- (canonical_tag_name / canonical_tags_from_snapshot).
--
-- source_system = 'plc_bridge' — the FactoryLM producer identity moves to
-- provenance.producer, not source_system (factorylm-plc-modbus is rejected by
-- VALID_SOURCE_SYSTEMS; see the PRD's amended contract note).
--
-- KEY MATCH — normalize_tag_path collapses '.', '/', ':' to '_', so
-- `conv_simple.vfd_speed_hz` normalizes to `conv_simple_vfd_speed_hz`. These
-- rows were generated by applying that exact regex to each canonical tag path.
--
-- UNS subtree — points at the same enterprise.home_garage.conveyor_lab.conveyor_1
-- subtree the other conv_simple allowlist seeds (approved_tags_conveyor.sql)
-- use, per that seed's own note: "Finer per-component mapping is a follow-up;
-- subtree match works either way." proposed_uns_path in the envelope itself is
-- provenance only and never creates/mutates this mapping (PRD § contract rules).
--
-- TENANT — `__TENANT_ID__` placeholder, substituted at apply time (see
-- apply-approved-tags.yml).
--
-- Idempotent — ON CONFLICT … DO UPDATE.

INSERT INTO approved_tags
  (tenant_id, source_system, source_tag_path, normalized_tag_path, uns_path, enabled, notes)
VALUES
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.motor_run',         'conv_simple_motor_run',         'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist'),
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.vfd_speed_hz',      'conv_simple_vfd_speed_hz',      'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist'),
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.vfd_current_amps',  'conv_simple_vfd_current_amps',  'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist'),
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.fault_code',        'conv_simple_fault_code',        'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist'),
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.comm_ok',           'conv_simple_comm_ok',           'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist'),
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.height_sensor_mm',  'conv_simple_height_sensor_mm',  'enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist'),
  ('__TENANT_ID__'::uuid, 'plc_bridge', 'conv_simple.sort_divert_active','conv_simple_sort_divert_active','enterprise.home_garage.conveyor_lab.conveyor_1'::ltree, true, 'PRD #3048 — FactoryLM canonical PLC snapshot allowlist')
ON CONFLICT (tenant_id, source_system, source_tag_path) DO UPDATE
  SET normalized_tag_path = EXCLUDED.normalized_tag_path,
      uns_path = EXCLUDED.uns_path,
      enabled = true,
      notes = EXCLUDED.notes,
      updated_at = now();

COMMIT;
