#!/usr/bin/env python3
"""Generate a Sparkplug B ``approved_tags`` allowlist seed from a node manifest.

The relay ingest path is **fail-closed**: a tag whose ``normalize_tag_path`` is
not in ``approved_tags`` for ``(tenant_id, source_system)`` is rejected and never
stored. A Sparkplug feed's raw tag path is ``group/edge[/device]/metric`` — a
DIFFERENT shape than the HTTP ``[default]Conveyor/...`` paths — so it needs its
own allowlist whose ``normalized_tag_path`` matches what the live subscriber
emits. This generator builds that seed from the SAME two functions the live path
uses, so the keys can never drift (the design §5 fail-closed contract):

  * ``mqtt_ingest.codecs.sparkplug_b.metric_to_tag_path`` — the path-builder the
    decoder uses (``group/edge[/device]/metric``).
  * ``ingest_contract.normalize_tag_path`` — THE allowlist match key.

Both are loaded by file path (no sys.path pollution), exactly like
``gen_approved_tags_simulator.py``.

Run::

    python tools/seeds/gen_approved_tags_sparkplug.py            # __TENANT_ID__ placeholder
    python tools/seeds/gen_approved_tags_sparkplug.py --tenant <uuid>

Writes ``tools/seeds/approved_tags_sparkplug_<edge>.sql`` (idempotent
``ON CONFLICT … DO UPDATE``). Apply staging-first, then prod (see the runbook
``docs/runbooks/2026-06-28-sparkplug-mqtt-consumer.md``). ``source_system`` is
``ignition`` (a Sparkplug edge IS the Ignition UNS arriving — design §6).
"""

from __future__ import annotations

import argparse
import importlib.util
import sys
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[2]


def _load(path: Path, name: str):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    # Register before exec: @dataclass resolves cls.__module__ via sys.modules.
    sys.modules[name] = mod
    spec.loader.exec_module(mod)  # type: ignore[union-attr]
    return mod


# sparkplug_b.py + ingest_contract.py are both dependency-free (stdlib only), so
# they load standalone. Same function the live subscriber uses → no key drift.
_spb = _load(_REPO_ROOT / "mira-relay" / "mqtt_ingest" / "codecs" / "sparkplug_b.py", "spb_seed")
_ic = _load(_REPO_ROOT / "mira-relay" / "ingest_contract.py", "ingest_contract_seed")
metric_to_tag_path = _spb.metric_to_tag_path
normalize_tag_path = _ic.normalize_tag_path
SparkplugTopic = _spb.SparkplugTopic


# ── node manifest: the Conv_Simple discharge-conveyor demo (spec §E) ─────────
# Edit / copy this block for another edge node. metric → uns leaf under uns_base.
CONVEYOR_NODE = {
    "group_id": "FactoryLM",
    "edge_node_id": "ConveyorEdge",
    "device_id": "Conv_Simple",
    "source_system": "ignition",
    "uns_base": "enterprise.home_garage.conveyor_lab.conveyor_1",
    "metrics": {
        "Conveyor/Motor_Running": "status.motor_running",
        "Conveyor/VFD_Hz": "process.vfd_frequency_hz",
        "Conveyor/VFD_Comm_OK": "status.vfd_comm_ok",
        "Conveyor/Photo_Eye": "status.photo_eye",
        "Conveyor/Amber_LED_Flash": "status.amber_led_flash",
        "Conveyor/Start_PB": "status.start_button",
        "Conveyor/Discharge_Request": "discharge.request",
        "Conveyor/Discharge_Pending": "discharge.pending_acceptance",
        "Conveyor/Discharge_Accepted": "discharge.accepted",
        "Conveyor/Discharge_Complete": "discharge.complete",
        "Conveyor/Discharge_Fault": "discharge.timeout_fault",
    },
}

_HEADER_TMPL = """\
BEGIN;

-- ─── approved_tags — Sparkplug B allowlist seed ({edge}/{device}) ────────────
--
-- GENERATED by tools/seeds/gen_approved_tags_sparkplug.py — DO NOT EDIT BY HAND.
-- Re-run the generator after the node's BIRTH metric set changes.
--
-- Seeds the per-tenant fail-closed allowlist the relay enforces before
-- persisting to tag_events + live_signal_cache. Without it every Sparkplug
-- metric from this edge bounces (silently — zero rows, no error).
--
-- KEY MATCH — the relay matches normalize_tag_path(group/edge/device/metric)
-- against normalized_tag_path. These rows are generated with the SAME
-- mqtt_ingest path-builder + normalizer the live subscriber uses, so they agree.
--
-- TENANT — {tenant_note}
-- source_system = 'ignition' (a Sparkplug edge IS the Ignition UNS arriving).
-- Idempotent — ON CONFLICT … DO UPDATE.

INSERT INTO approved_tags
  (tenant_id, source_system, source_tag_path, normalized_tag_path, uns_path, enabled, notes)
VALUES
"""

_CONFLICT = """\
ON CONFLICT (tenant_id, source_system, source_tag_path) DO UPDATE
  SET normalized_tag_path = EXCLUDED.normalized_tag_path,
      uns_path = EXCLUDED.uns_path,
      enabled = true,
      notes = EXCLUDED.notes,
      updated_at = now();

COMMIT;
"""


def _lit(s: str) -> str:
    return "'" + s.replace("'", "''") + "'"


def build_sql(node: dict, tenant: str) -> str:
    topic = SparkplugTopic(
        namespace="spBv1.0",
        group_id=node["group_id"],
        message_type="DBIRTH",
        edge_node_id=node["edge_node_id"],
        device_id=node.get("device_id"),
    )
    tenant_uuid = "'__TENANT_ID__'" if tenant == "__TENANT_ID__" else _lit(tenant)
    rows: list[str] = []
    for metric_name, uns_leaf in sorted(node["metrics"].items()):
        raw = metric_to_tag_path(topic, metric_name)
        norm = normalize_tag_path(raw)
        uns = f"{node['uns_base']}.{uns_leaf}"
        rows.append(
            f"  ({tenant_uuid}::uuid, {_lit(node['source_system'])}, "
            f"{_lit(raw)}, {_lit(norm)}, {_lit(uns)}::ltree, true, "
            f"'Sparkplug {node['edge_node_id']}/{node.get('device_id', '')} — "
            f"generated by gen_approved_tags_sparkplug.py')"
        )
    tenant_note = (
        "__TENANT_ID__ placeholder — substitute the real tenant UUID at apply time"
        if tenant == "__TENANT_ID__"
        else f"hardcoded tenant {tenant}"
    )
    header = _HEADER_TMPL.format(
        edge=node["edge_node_id"], device=node.get("device_id", ""), tenant_note=tenant_note
    )
    return header + ",\n".join(rows) + "\n" + _CONFLICT


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument(
        "--tenant",
        default="__TENANT_ID__",
        help="tenant UUID to embed, or leave as __TENANT_ID__ placeholder",
    )
    args = ap.parse_args()
    node = CONVEYOR_NODE
    sql = build_sql(node, args.tenant)
    out = Path(__file__).parent / f"approved_tags_sparkplug_{node['edge_node_id'].lower()}.sql"
    out.write_text(sql, encoding="utf-8")
    n = len(node["metrics"])
    print(f"Wrote {out} ({n} Sparkplug allowlist rows, tenant {args.tenant})")


if __name__ == "__main__":
    main()
