#!/usr/bin/env python3
"""Generate ``tools/seeds/approved_tags_simulator.sql`` from the SimLab snapshot.

Closes **Gap C** of the SimLab -> UNS ingest roadmap
(``docs/plans/2026-06-22-simlab-uns-ingest-roadmap.md``, Lane 2): the relay's
``/api/v1/tags/ingest`` is **fail-closed** — a tag whose normalized path is not
in ``approved_tags`` for ``(tenant_id, source_system='simulator')`` is rejected
and never stored. Without this seed, every SimLab reading bounces.

One row per ``SimEngine.snapshot()`` reading:

  source_tag_path     = reading.uns_path          (SimLab's canonical dot-ltree)
  normalized_tag_path = normalize(uns_path)        (must match the relay's
                          ``mira-relay/tag_ingest.normalize_tag_path``)
  uns_path            = reading.uns_path           (landing resolves the UNS from
                          THIS column, not the reading's own path — so you may
                          repoint it at any target subtree if remapping)

Tenant is the **reserved** ``SIMLAB_TENANT_ID`` (``simlab/__init__.py``) — no
provisioning needed; the SimLab self-feed does not use the ``proveit`` tenant.

Run::

    python tools/seeds/gen_approved_tags_simulator.py
    # writes tools/seeds/approved_tags_simulator.sql

Apply (staging first, per docs/environments.md — seeds reach prod only after
retrieval/landing is proven on staging-shape data)::

    psql "$STAGING_URL" -f tools/seeds/approved_tags_simulator.sql

The seed is idempotent (``ON CONFLICT … DO UPDATE``) and re-running this
generator after the line changes is the supported way to keep it in sync.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

# Make the repo root importable when run as a plain script (python adds the
# script's own dir to sys.path, not the repo root).
_REPO_ROOT = Path(__file__).resolve().parents[2]
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

# Reserved SimLab tenant (UUID) — simlab/__init__.py SIMLAB_TENANT_ID.
from simlab import SIMLAB_TENANT_ID  # noqa: E402
from simlab.engine import SimEngine  # noqa: E402
from simlab.lines.juice_bottling import build_line  # noqa: E402

# Mirror of mira-relay/tag_ingest.normalize_tag_path (uns.slug-style). Kept local
# so the generator has no relay/DB import; tests assert it equals the real one.
_NON_ALNUM = re.compile(r"[^a-z0-9]+")


def normalize_tag_path(raw: str) -> str:
    """Lowercase; runs of non-alphanumerics -> '_'; trim leading/trailing '_'."""
    if not raw:
        return ""
    return _NON_ALNUM.sub("_", raw.strip().lower()).strip("_")


_OUT = Path(__file__).parent / "approved_tags_simulator.sql"

_HEADER = """\
BEGIN;

-- ─── approved_tags — SimLab juice-bottling-line allowlist seed ───────────────
--
-- GENERATED by tools/seeds/gen_approved_tags_simulator.py — DO NOT EDIT BY HAND.
-- Re-run the generator after the SimLab line changes to regenerate this file.
--
-- Seeds the per-tenant SECURITY allowlist the mira-relay ingest endpoint
-- (POST /api/v1/tags/ingest) enforces FAIL-CLOSED before persisting readings to
-- tag_events + live_signal_cache. Without it, every simulator batch is rejected
-- (Gap C — docs/plans/2026-06-22-simlab-uns-ingest-roadmap.md, Lane 2).
--
-- KEY MATCH — the relay's hot-path query is
--   WHERE tenant_id=? AND source_system='simulator' AND normalized_tag_path=? AND enabled=true
-- so normalized_tag_path MUST equal what mira-relay/tag_ingest.normalize_tag_path
-- produces. These values are generated with the identical regex.
--
-- TENANT — the RESERVED SimLab tenant (simlab/__init__.py SIMLAB_TENANT_ID),
-- hardcoded: it always exists, so no provisioning / no __TENANT_ID__ substitution
-- (unlike customer seeds). The SimLab self-feed is NOT the proveit import corpus.
--
-- UNS — uns_path mirrors source_tag_path (SimLab's own UNS). To remap SimLab onto
-- a different target subtree, repoint the uns_path column; landing reads the UNS
-- from THIS row, not the reading's own path.
--
-- Idempotent — re-applying is safe via ON CONFLICT … DO UPDATE.

INSERT INTO approved_tags
  (tenant_id, source_system, source_tag_path, normalized_tag_path, uns_path, enabled, notes)
VALUES
"""

_CONFLICT = """\
ON CONFLICT (tenant_id, source_system, source_tag_path) DO UPDATE
  SET normalized_tag_path = EXCLUDED.normalized_tag_path,
      uns_path = EXCLUDED.uns_path,
      enabled = true,
      notes = EXCLUDED.notes,
      updated_at = now();

COMMIT;
"""


def _sql_literal(s: str) -> str:
    """Single-quote a SQL string literal (double any embedded quote)."""
    return "'" + s.replace("'", "''") + "'"


def build_sql() -> str:
    engine = SimEngine(build_line())
    readings = engine.snapshot()

    seen: set[str] = set()
    rows: list[str] = []
    for r in sorted(readings, key=lambda x: x.uns_path):
        path = r.uns_path
        if path in seen:
            continue
        seen.add(path)
        norm = normalize_tag_path(path)
        rows.append(
            f"  ({_sql_literal(SIMLAB_TENANT_ID)}::uuid, 'simulator', "
            f"{_sql_literal(path)}, {_sql_literal(norm)}, "
            f"{_sql_literal(path)}::ltree, true, "
            f"'SimLab juice line — generated by gen_approved_tags_simulator.py')"
        )

    return _HEADER + ",\n".join(rows) + "\n" + _CONFLICT


def main() -> None:
    sql = build_sql()
    _OUT.write_text(sql, encoding="utf-8")
    n = sql.count("::uuid, 'simulator'")
    print(f"Wrote {_OUT} ({n} simulator allowlist rows, tenant {SIMLAB_TENANT_ID})")


if __name__ == "__main__":
    main()
