"""MIRA morning pass-down report — 6AM Eastern daily.

Queries recent interactions, groups by asset, sends via Resend email (if configured)
and ntfy push. Falls back to ntfy-only when RESEND_API_KEY is absent.

Celery beat entry (add to mira-crawler/celeryconfig.py):
    from celery.schedules import crontab
    beat_schedule['mira-morning-report'] = {
        'task': 'mira_bots.morning_report',
        'schedule': crontab(hour=11, minute=0),  # 11:00 UTC = 07:00 ET
    }
"""

from __future__ import annotations

import logging
import os
import sqlite3
from collections import defaultdict
from datetime import datetime, timedelta, timezone
from pathlib import Path

logger = logging.getLogger("mira-morning-report")

RESEND_API_KEY = os.getenv("RESEND_API_KEY", "")
RESEND_FROM = os.getenv("RESEND_FROM", "mira@factorylm.com")
RESEND_TO = os.getenv("MORNING_REPORT_EMAIL", "harperhousebuyers@gmail.com")
NTFY_URL = os.getenv("NTFY_URL", "https://ntfy.sh")
NTFY_TOPIC = os.getenv("NTFY_TOPIC", "mira-factorylm-alerts")
REPORT_DIR = Path(__file__).parent.parent.parent.parent / "tests" / "eval" / "runs"


def _query_recent_interactions(db_path: str, since_hours: int = 12) -> list[dict]:
    """Return all interactions since cutoff, ordered by asset then time."""
    cutoff = (datetime.now(timezone.utc) - timedelta(hours=since_hours)).isoformat()
    try:
        db = sqlite3.connect(db_path)
        db.row_factory = sqlite3.Row
        cur = db.cursor()
        cur.execute(
            """
            SELECT chat_id, platform, user_message, bot_response,
                   fsm_state, intent, confidence, created_at
            FROM interactions
            WHERE created_at >= ?
            ORDER BY created_at ASC
            """,
            (cutoff,),
        )
        rows = [dict(r) for r in cur.fetchall()]
        db.close()
        return rows
    except Exception as exc:
        logger.warning("MORNING_REPORT DB query failed: %s", exc)
        return []


def _group_by_asset(rows: list[dict]) -> dict[str, list[dict]]:
    """Best-effort: group by chat_id as proxy for tech session."""
    grouped: dict[str, list[dict]] = defaultdict(list)
    for r in rows:
        grouped[r["chat_id"]].append(r)
    return dict(grouped)


def _build_markdown(groups: dict[str, list[dict]], date_str: str) -> str:
    lines = [f"# MIRA Morning Pass-Down — {date_str}\n"]
    if not groups:
        lines.append("_No activity in the last 12 hours._")
        return "\n".join(lines)
    for session_id, events in groups.items():
        lines.append(f"## Session: {session_id[:16]}")
        lines.append(f"Events: {len(events)}")
        for ev in events[-5:]:  # last 5 per session
            ts = str(ev.get("created_at", ""))[:16]
            state = ev.get("fsm_state") or "?"
            snippet = str(ev.get("user_message", ""))[:80].replace("\n", " ")
            lines.append(f"- `{ts}` [{state}] {snippet}")
        lines.append("")
    return "\n".join(lines)


def _build_html(groups: dict[str, list[dict]], date_str: str) -> str:
    rows_html = ""
    for session_id, events in groups.items():
        rows_html += f"<tr><td colspan='3'><strong>Session {session_id[:16]}</strong></td></tr>"
        for ev in events[-5:]:
            ts = str(ev.get("created_at", ""))[:16]
            state = ev.get("fsm_state") or "?"
            snippet = str(ev.get("user_message", ""))[:80].replace("\n", " ")
            rows_html += (
                f"<tr><td>{ts}</td><td>{state}</td>"
                f"<td>{snippet}</td></tr>"
            )
    return f"""<!DOCTYPE html>
<html>
<head><style>
body {{ font-family: -apple-system, sans-serif; max-width: 640px; margin: auto; padding: 16px; }}
table {{ border-collapse: collapse; width: 100%; }}
td, th {{ border: 1px solid #ddd; padding: 8px; font-size: 13px; }}
th {{ background: #1a1a2e; color: white; }}
</style></head>
<body>
<h2>MIRA Morning Pass-Down — {date_str}</h2>
{"<p><em>No activity in the last 12 hours.</em></p>" if not groups else ""}
<table>
<tr><th>Time</th><th>FSM State</th><th>Message</th></tr>
{rows_html}
</table>
<p style="color:#888;font-size:11px">Generated by MIRA · factorylm.com</p>
</body></html>"""


async def _send_email(subject: str, html: str) -> bool:
    if not RESEND_API_KEY:
        return False
    import httpx

    try:
        async with httpx.AsyncClient(timeout=15) as client:
            resp = await client.post(
                "https://api.resend.com/emails",
                headers={"Authorization": f"Bearer {RESEND_API_KEY}"},
                json={
                    "from": RESEND_FROM,
                    "to": [RESEND_TO],
                    "subject": subject,
                    "html": html,
                },
            )
            resp.raise_for_status()
            logger.info("MORNING_REPORT email sent to %s", RESEND_TO)
            return True
    except Exception as exc:
        logger.warning("MORNING_REPORT email failed: %s", exc)
        return False


async def _send_ntfy(markdown: str, date_str: str) -> bool:
    import httpx

    try:
        async with httpx.AsyncClient(timeout=10) as client:
            resp = await client.post(
                f"{NTFY_URL}/{NTFY_TOPIC}",
                content=markdown[:4000],  # ntfy message limit
                headers={
                    "Title": f"Morning Report {date_str}",
                    "Priority": "default",
                    "Tags": "sunrise,clipboard",
                },
            )
            resp.raise_for_status()
            return True
    except Exception as exc:
        logger.warning("MORNING_REPORT ntfy failed: %s", exc)
        return False


def _save_report(markdown: str, date_str: str) -> None:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORT_DIR / f"morning-report-{date_str}.md"
    path.write_text(markdown, encoding="utf-8")
    logger.info("MORNING_REPORT saved to %s", path)


async def generate_and_send(db_path: str) -> dict:
    """Build and deliver the morning pass-down report. Returns run stats."""
    date_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    rows = _query_recent_interactions(db_path, since_hours=12)
    groups = _group_by_asset(rows)
    markdown = _build_markdown(groups, date_str)
    html = _build_html(groups, date_str)

    _save_report(markdown, date_str)

    subject = f"MIRA Morning Report — {date_str}"
    email_sent = await _send_email(subject, html)
    ntfy_sent = False
    if not email_sent:
        ntfy_sent = await _send_ntfy(markdown, date_str)

    result = {
        "date": date_str,
        "sessions": len(groups),
        "events": len(rows),
        "email_sent": email_sent,
        "ntfy_sent": ntfy_sent,
    }
    logger.info("MORNING_REPORT complete: %s", result)
    return result


# ---------------------------------------------------------------------------
# Celery task (optional)
# ---------------------------------------------------------------------------
try:
    from celery import shared_task

    @shared_task(name="mira_bots.morning_report", bind=True)
    def morning_report_task(self, db_path: str = ""):
        """Celery task: 6AM ET daily pass-down report."""
        import asyncio

        if not db_path:
            logger.warning("morning_report_task called without db_path")
            return {"error": "db_path required"}
        try:
            return asyncio.run(generate_and_send(db_path))
        except Exception as exc:
            logger.error("morning_report_task failed: %s", exc)
            raise self.retry(exc=exc, countdown=300)

except ImportError:
    pass
