"""Weekly crawl report generator.

Reads dedup store stats and generates a markdown report showing
coverage by source type, tier, and knowledge domain.
"""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from ingest.dedup import DedupStore

logger = logging.getLogger("mira-crawler.report")


def generate_report(dedup: DedupStore, output_path: Path) -> str:
    """Generate a crawl report markdown file.

    Returns the report content as a string and writes to output_path.
    """
    stats = dedup.stats()
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    lines = [
        f"# MIRA Crawler Report — {now}",
        "",
        "## Summary",
        "",
        f"- **Total documents indexed:** {stats['total_documents']}",
        f"- **Total chunks stored:** {stats['total_chunks']}",
        "",
        "## Documents by Source Type",
        "",
        "| Source Type | Count |",
        "|---|---|",
    ]

    for source_type, count in sorted(stats["by_source_type"].items()):
        lines.append(f"| {source_type} | {count} |")

    if not stats["by_source_type"]:
        lines.append("| (none) | 0 |")

    lines.extend([
        "",
        "---",
        f"*Generated by mira-crawler at {now}*",
    ])

    content = "\n".join(lines)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content)
    logger.info("Crawl report written to %s", output_path)
    return content
