/**
 * Generate THIRD_PARTY_NOTICES.md for the shared UI workspace.
 *
 * Walks the same installed set the licence audit walks (Bun's isolated store)
 * and writes, for every external package: name, version, licence, and the
 * copyright lines from its LICENSE file. Packages admitted by a maintainer-
 * approved exception (license-policy.ts) additionally carry their LICENSE text
 * verbatim — that preservation is the condition of the approval, and the
 * audit (`bun run licenses`) fails when it is missing or stale.
 *
 * Deterministic: sorted by name@version, no timestamps, so the file only
 * changes when the dependency set does.
 */
import { existsSync } from "node:fs";
import { readdir, readFile, realpath, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { findException } from "./license-policy";

const appRoot = resolve(import.meta.dir, "..");
const workspaceRoot = resolve(appRoot, "../..");
const store = join(workspaceRoot, "node_modules", ".bun");

interface Entry {
  readonly key: string;
  readonly license: string;
  readonly copyright: readonly string[];
  readonly licenseText?: string;
  readonly exception?: ReturnType<typeof findException>;
}

const seen = new Set<string>();
const entries: Entry[] = [];

async function collect(packagePath: string): Promise<void> {
  const manifestPath = join(packagePath, "package.json");
  if (!existsSync(manifestPath)) return;
  const real = dirname(await realpath(manifestPath));
  if (seen.has(real)) return;
  seen.add(real);
  const manifest = JSON.parse(await readFile(manifestPath, "utf8")) as { name?: string; version?: string; license?: string | { type?: string }; private?: boolean };
  if (manifest.private || !manifest.name || !manifest.version) return;
  const license = typeof manifest.license === "string" ? manifest.license : manifest.license?.type ?? "unknown";
  const files = await readdir(real);
  const licenseFile = files.find((entry) => /^(LICENSE|LICENCE|COPYING)/i.test(entry));
  const text = licenseFile ? await readFile(join(real, licenseFile), "utf8") : "";
  // Only the notice lines themselves ("Copyright (c) …"), not the boilerplate
  // that merely mentions the word.
  const copyright = text.split(/\r?\n/).map((line) => line.trim()).filter((line) => /^(copyright\b|\(c\)|©)/i.test(line));
  const exception = findException(manifest.name, manifest.version);
  entries.push({
    key: `${manifest.name}@${manifest.version}`,
    license,
    copyright,
    ...(exception ? { licenseText: text.trim(), exception } : {}),
  });
}

if (!existsSync(store)) {
  console.error("generate-third-party-notices: no isolated store at node_modules/.bun — run `bun install` at the workspace root first.");
  process.exit(1);
}
for (const entry of await readdir(store, { withFileTypes: true })) {
  if (entry.name === "node_modules") continue;
  const nodeModules = join(store, entry.name, "node_modules");
  if (!existsSync(nodeModules)) continue;
  for (const scope of await readdir(nodeModules, { withFileTypes: true })) {
    if (scope.name.startsWith(".")) continue;
    const scopePath = join(nodeModules, scope.name);
    if (scope.name.startsWith("@")) {
      for (const pkg of await readdir(scopePath)) await collect(join(scopePath, pkg));
    } else {
      await collect(scopePath);
    }
  }
}
if (entries.length === 0) {
  console.error("generate-third-party-notices: walked zero external packages — wrong root or uninstalled tree.");
  process.exit(1);
}
entries.sort((a, b) => a.key.localeCompare(b.key));

const lines: string[] = [
  "# Third-party notices — FactoryLM shared UI workspace",
  "",
  "Generated by `bun run notices` (apps/factorylm-ui-lab/scripts/generate-third-party-notices.ts) from the installed dependency set. Do not edit by hand; `bun run licenses` fails when an approved exception's notice is missing or stale.",
  "",
  "Policy: MIT or Apache-2.0 (PRD §4), plus the maintainer-approved per-version exceptions listed with their full licence text below (scripts/license-policy.ts).",
  "",
  "## Summary",
  "",
  "| package | licence | copyright |",
  "|---|---|---|",
  ...entries.map((entry) => `| ${entry.key} | ${entry.license}${entry.exception ? " (approved exception)" : ""} | ${entry.copyright.join("; ").replace(/\|/g, "\\|") || "—"} |`),
  "",
];
for (const entry of entries.filter((candidate) => candidate.exception)) {
  lines.push(
    `## ${entry.key} — ${entry.license}`,
    "",
    `Approved by ${entry.exception!.approvedBy}: ${entry.exception!.decision}. In the tree via ${entry.exception!.via}. Licence text preserved verbatim:`,
    "",
    "```text",
    entry.licenseText ?? "",
    "```",
    "",
  );
}
await writeFile(join(appRoot, "THIRD_PARTY_NOTICES.md"), `${lines.join("\n")}\n`);
console.log(`generate-third-party-notices: ${entries.length} packages, ${entries.filter((entry) => entry.exception).length} approved exception(s) with verbatim licence text → THIRD_PARTY_NOTICES.md`);
