#!/usr/bin/env python3
"""ccw_ld_gen.py — Generate CCW-importable .isaxch files.

Phase 1 (this file): ST emission. Self-test round-trips
plc/ccw/drive_test/step1_io_check/PROG_IO.isaxch byte-for-byte.

Phase 2 (pending Steps 2-3 of the experiment): LD emission.
Schema discovery protocol lives in wiki/references/ccw-ld-isaxch-schema.md.
"""

from __future__ import annotations

import argparse
import difflib
import sys
from pathlib import Path

XML_HEADER = '<?xml version="1.0" encoding="utf-8"?>'

ISAXCH_WRAPPER = """{header}
<ISaGRAF_Export version="1.0">
  <Program>
    <Name>{name}</Name>
    <Language>{language}</Language>
    <Description>{description}</Description>
    <SourceCode><![CDATA[{source}]]></SourceCode>
  </Program>
</ISaGRAF_Export>
"""


def emit_st_isaxch(*, name: str, description: str, source: str) -> str:
    """Emit a CCW-importable .isaxch for a Structured Text program."""
    return ISAXCH_WRAPPER.format(
        header=XML_HEADER,
        name=name,
        language="ST",
        description=description,
        source=source if source.endswith("\n") else source + "\n",
    )


def emit_ld_isaxch(*, name: str, description: str, rungs: list[dict]) -> str:
    del description, rungs
    raise NotImplementedError(
        f"LD .isaxch generation for '{name}' is gated on Steps 2-3 of the experiment. "
        "See wiki/references/ccw-ld-isaxch-schema.md for the discovery protocol."
    )


def _self_test() -> int:
    repo_root = Path(__file__).resolve().parent.parent
    reference = repo_root / "plc" / "ccw" / "drive_test" / "step1_io_check" / "PROG_IO.isaxch"
    if not reference.exists():
        print(f"reference missing: {reference}", file=sys.stderr)
        return 2

    expected = reference.read_text(encoding="utf-8")
    generated = emit_st_isaxch(
        name="PROG_IO",
        description="Step 1 I/O check — toggles heartbeat every scan",
        source="heartbeat := NOT heartbeat;\n",
    )
    if expected == generated:
        print("ST round-trip PASS — generated bytes identical to PROG_IO.isaxch")
        return 0

    print("ST round-trip FAIL — diff:", file=sys.stderr)
    sys.stderr.writelines(
        difflib.unified_diff(
            expected.splitlines(keepends=True),
            generated.splitlines(keepends=True),
            fromfile="PROG_IO.isaxch",
            tofile="generated",
        )
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--self-test", action="store_true", help="Verify ST round-trip and exit")
    args = parser.parse_args()
    if args.self_test:
        return _self_test()
    parser.print_help()
    return 0


if __name__ == "__main__":
    sys.exit(main())
