#!/usr/bin/env python3
"""
Scan docs/{plans,superpowers/plans,superpowers/specs,adr}/ and emit
docs/superpowers/INDEX.md — a single roadmap of every plan/spec/ADR with
status, last-touched date (from git), and linked counterpart (plan<->spec).

Reads YAML frontmatter when present:

    ---
    status: active | shipped | abandoned | draft
    linked: <relative path to counterpart doc>
    owner: <name>
    tags: [a, b]
    ---

When frontmatter is absent, the script derives what it can from filename +
first H1 + first `**Goal:**` line + `git log -1 --format=%ai`, and flags
the entry with `?` status so the gap is visible.

Run from repo root: `python tools/generate_docs_index.py`
"""
from __future__ import annotations

import re
import subprocess
from dataclasses import dataclass, field
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
INDEX_PATH = REPO / "docs" / "superpowers" / "INDEX.md"

SCAN_DIRS = [
    ("docs/plans", "plan"),
    ("docs/superpowers/plans", "plan"),
    ("docs/superpowers/specs", "spec"),
    ("docs/adr", "adr"),
]

FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
FILENAME_DATE_RE = re.compile(r"^(\d{4}-\d{2}-\d{2})")
H1_RE = re.compile(r"^#\s+(.+?)\s*$", re.MULTILINE)
GOAL_RE = re.compile(r"\*\*Goal:\*\*\s*(.+?)(?:\n\n|\n\*\*)", re.DOTALL)


@dataclass
class DocEntry:
    path: Path
    kind: str
    title: str
    goal: str
    status: str
    linked: str
    owner: str
    tags: list[str] = field(default_factory=list)
    filename_date: str = ""
    last_touched: str = ""
    has_frontmatter: bool = False

    @property
    def sort_key(self) -> tuple[str, str]:
        return (self.last_touched or self.filename_date or "", str(self.path))


def parse_frontmatter(text: str) -> dict[str, str]:
    match = FRONTMATTER_RE.match(text)
    if not match:
        return {}
    body = match.group(1)
    out: dict[str, str] = {}
    for line in body.splitlines():
        if ":" not in line:
            continue
        key, _, value = line.partition(":")
        out[key.strip()] = value.strip()
    return out


def git_last_touched(path: Path) -> str:
    try:
        result = subprocess.run(
            ["git", "log", "-1", "--format=%ai", "--", str(path.relative_to(REPO))],
            cwd=REPO,
            capture_output=True,
            text=True,
            check=False,
        )
        stdout = result.stdout.strip()
        if not stdout:
            return ""
        return stdout.split()[0]
    except Exception:
        return ""


def read_entry(path: Path, kind: str) -> DocEntry:
    text = path.read_text(encoding="utf-8", errors="replace")
    fm = parse_frontmatter(text)
    body = FRONTMATTER_RE.sub("", text, count=1)

    h1 = H1_RE.search(body)
    title = fm.get("title") or (h1.group(1) if h1 else path.stem)

    goal_match = GOAL_RE.search(body)
    goal = ""
    if goal_match:
        goal = re.sub(r"\s+", " ", goal_match.group(1)).strip()[:180]

    fn_date_match = FILENAME_DATE_RE.match(path.stem)
    filename_date = fn_date_match.group(1) if fn_date_match else ""

    tags_raw = fm.get("tags", "").strip("[]")
    tags = [t.strip() for t in tags_raw.split(",") if t.strip()] if tags_raw else []

    return DocEntry(
        path=path,
        kind=kind,
        title=title,
        goal=goal,
        status=fm.get("status", ""),
        linked=fm.get("linked", ""),
        owner=fm.get("owner", ""),
        tags=tags,
        filename_date=filename_date,
        last_touched=git_last_touched(path),
        has_frontmatter=bool(fm),
    )


def status_badge(status: str) -> str:
    s = (status or "").lower()
    if s in ("shipped", "abandoned", "draft", "active"):
        return s
    return "?"


def render(entries: list[DocEntry]) -> str:
    entries.sort(key=lambda e: e.sort_key, reverse=True)

    total = len(entries)
    with_fm = sum(1 for e in entries if e.has_frontmatter)
    shipped = sum(1 for e in entries if (e.status or "").lower() == "shipped")
    active = sum(1 for e in entries if (e.status or "").lower() == "active")
    unknown = total - shipped - active

    lines: list[str] = [
        "# Docs Index - Plans, Specs, ADRs",
        "",
        "_Auto-generated by `tools/generate_docs_index.py`. Do not hand-edit._",
        "",
        f"**Summary:** {total} docs - {with_fm} with frontmatter - "
        f"{active} active - {shipped} shipped - {unknown} unlabeled",
        "",
        "**Status legend:** `active` = in-progress - `shipped` = merged/done - "
        "`abandoned` = rejected - `draft` = pre-commitment - `?` = missing frontmatter",
        "",
        "## Entries",
        "",
        "| Status | Kind | Touched | Title | Goal | Linked |",
        "| --- | --- | --- | --- | --- | --- |",
    ]

    for e in entries:
        rel = e.path.relative_to(REPO).as_posix()
        title_link = f"[{e.title}]({rel})"
        goal_cell = (e.goal[:120] + "...") if len(e.goal) > 120 else e.goal
        goal_cell = goal_cell.replace("|", "\\|") or "-"
        linked_cell = f"[link]({e.linked})" if e.linked else "-"
        touched = e.last_touched or e.filename_date or "?"
        status = status_badge(e.status)
        lines.append(
            f"| `{status}` | {e.kind} | {touched} | {title_link} | {goal_cell} | {linked_cell} |"
        )

    lines += [
        "",
        "## Frontmatter Schema",
        "",
        "Add this block at the top of any plan/spec/ADR to control how it appears above:",
        "",
        "```yaml",
        "---",
        "status: active         # active | shipped | abandoned | draft",
        "linked: ../specs/2026-04-17-mira-connect-design.md",
        "owner: Mike",
        "tags: [velocity, ci]",
        "---",
        "```",
        "",
        "Regenerate this index after adding or updating frontmatter:",
        "",
        "```bash",
        "python tools/generate_docs_index.py",
        "```",
        "",
        f"_Generated: {datetime.now(tz=timezone.utc).isoformat(timespec='seconds')}_",
        "",
    ]
    return "\n".join(lines)


def main() -> None:
    entries: list[DocEntry] = []
    for rel_dir, kind in SCAN_DIRS:
        dir_path = REPO / rel_dir
        if not dir_path.is_dir():
            continue
        for md in sorted(dir_path.glob("*.md")):
            if md.name.upper() in {"README.MD", "INDEX.MD"}:
                continue
            entries.append(read_entry(md, kind))

    INDEX_PATH.parent.mkdir(parents=True, exist_ok=True)
    INDEX_PATH.write_text(render(entries), encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(REPO)} - {len(entries)} entries")


if __name__ == "__main__":
    main()
