-- 048_schema_migrations_ledger.sql
--
-- Beta-readiness P3-2 (#5): make mira-hub/db/migrations re-apply correctly via
-- an applied-ledger instead of trusting per-file IF NOT EXISTS guards on every
-- "all" run.
--
-- REUSE, don't rebuild: a `schema_migrations` table already exists in the Neon
-- databases (columns id / migration_name / applied_at, UNIQUE(migration_name)),
-- created by a legacy migration set (001_saas_layer.sql, 002_knowledge_base.sql)
-- that is no longer in the repo and no longer maintained. apply-migrations.yml
-- never recorded into it, so it sat with 2 stale rows. We adopt THIS table as
-- the canonical ledger and key on `migration_name` (the migration FILENAME).
--
-- Filenames are stable and unique even where two files share a numeric prefix
-- (006_add_hub_ui_source.sql vs 006_system_canary.sql), so the 8 historical
-- duplicate prefixes do NOT need renumbering — renumbering an already-applied
-- file would change its ledger key and make it re-apply. 3-digit zero-padded
-- prefixes already sort numerically under a plain lexical sort, and the 038–042
-- gap is harmless, so apply order is unaffected.
--
-- Seeding an EXISTING database: run apply-migrations.yml with mode=seed-ledger
-- once per target to record every current migration filename as applied WITHOUT
-- executing SQL, baselining the current schema. Then mode=apply migrations=all
-- runs only un-recorded files.
--
-- This migration is defensive on both shapes:
--   * fresh DB (no table)  → create it matching the legacy shape
--   * existing DB          → IF NOT EXISTS is a no-op; ensure the unique key

CREATE TABLE IF NOT EXISTS schema_migrations (
    id             integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    migration_name varchar NOT NULL,
    applied_at     timestamptz NOT NULL DEFAULT now()
);

-- Ensure the natural key exists (legacy table already has it; a freshly created
-- one needs it for the workflow's ON CONFLICT (migration_name)).
DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'schema_migrations'::regclass AND contype = 'u'
          AND pg_get_constraintdef(oid) ILIKE '%(migration_name)%'
    ) THEN
        ALTER TABLE schema_migrations
            ADD CONSTRAINT schema_migrations_migration_name_key UNIQUE (migration_name);
    END IF;
END $$;

COMMENT ON TABLE schema_migrations IS
    'Applied-migration ledger for mira-hub/db/migrations (keyed on migration_name = filename). apply-migrations.yml records each applied file and skips files already present. Seed an existing DB once via apply-migrations.yml mode=seed-ledger.';

-- Record this migration itself (idempotent).
INSERT INTO schema_migrations (migration_name)
VALUES ('048_schema_migrations_ledger.sql')
ON CONFLICT (migration_name) DO NOTHING;
