-- 066_migration_ledger_content_sha.sql
--
-- Root-cause prevention for the draft-poisoning drift class (#2284, recurred as
-- #2945 on 2026-07-27). See .claude/rules/mira-hub-migrations.md §8.
--
-- THE MECHANISM THIS DEFEATS
--   (auto-apply drafts to persistent staging)
--     x (CREATE TABLE IF NOT EXISTS)
--     x (ledger keyed on FILENAME only)
--   = silent staging-only drift that the ledger reports as healthy.
--
-- migration-verify.yml auto-applies migrations to the PERSISTENT staging Neon
-- branch on every PR touching this directory — including EARLY DRAFTS. If the
-- file is later rewritten before merge, the canonical version "applies" (the
-- ledger records the filename) but its `CREATE TABLE IF NOT EXISTS` SKIPS over
-- the pre-existing draft table. Staging is then frozen at the draft shape while
-- `schema_migrations` says "applied" and CI is green. The drift is INVISIBLE
-- until something writes the canonical shape and gets `column ... does not exist`.
--
-- The ledger keys on `migration_name` (the filename), which is stable by design
-- (§7: renumbering an applied migration makes it re-run, so filenames must not
-- change). But a stable KEY with mutable CONTENT is exactly the blind spot: the
-- ledger cannot distinguish "this file was applied" from "a DIFFERENT VERSION of
-- this file was applied".
--
-- FIX: record the sha256 of the file CONTENT alongside the filename. A later run
-- that sees the same filename with a different sha can then FAIL LOUD instead of
-- silently skipping. Detection lives in apply-migrations.yml; this migration only
-- provides the column.
--
-- NULL semantics (deliberate): existing rows get NULL, meaning "applied before
-- content tracking existed — unknown". The checker treats NULL as unknown and
-- does NOT fail on it, because we cannot retroactively know what content those
-- rows were applied with. Use `mode=seed-ledger` to stamp the CURRENT file shas
-- onto NULL rows once the deployed schema is believed canonical — that baselines
-- the detector so it protects everything from that point forward. Without that
-- backfill this column protects only migrations applied after it lands.
--
-- Idempotent (§5) and additive-only: no data is read, moved, or destroyed, and
-- nothing here can fail on a DB that already has the column.

BEGIN;

-- The ledger may not exist on a brand-new DB (048 creates it defensively; this
-- mirrors that shape so 066 is safe to run standalone / out of order).
CREATE TABLE IF NOT EXISTS schema_migrations (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  migration_name varchar NOT NULL UNIQUE,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- The content fingerprint. Nullable on purpose — see NULL semantics above.
ALTER TABLE schema_migrations
  ADD COLUMN IF NOT EXISTS content_sha256 text;

COMMENT ON COLUMN schema_migrations.content_sha256 IS
  'sha256 of the migration file content at apply time. NULL = applied before '
  'content tracking (unknown). A recorded sha that no longer matches the file '
  'on main means the file was REWRITTEN after being applied — the #2284 '
  'draft-poisoning drift class. See .claude/rules/mira-hub-migrations.md section 8.';

-- Records WHEN the fingerprint was captured, so a backfill (seed-ledger) is
-- distinguishable from a genuine apply-time capture during incident forensics.
ALTER TABLE schema_migrations
  ADD COLUMN IF NOT EXISTS content_sha256_at timestamptz;

COMMENT ON COLUMN schema_migrations.content_sha256_at IS
  'When content_sha256 was captured. Lets a baseline backfill be told apart '
  'from an apply-time capture.';

COMMIT;
