-- Migration 093: `turn_ingress` — the counter that is NOT the recorder.
--
-- Claim #3939, "Independently reconcile ingress/client attempts with durable
-- records."
--
-- THE DEFECT THIS CLOSES
-- 091/092 gave every accepted turn a durable start and an outcome, and
-- `lifecycleCoverage()` reports how many of those finished. But that number is
-- computed FROM `decision_traces`, so it can only ever describe turns the
-- recorder managed to write a start for. A turn whose start never landed — the
-- write failed, the process died between accept and insert, the code path
-- returned before `openTurn` — is not a low coverage score. It is INVISIBLE,
-- and coverage reads 100%.
--
--   "A missing start row cannot appear in a query of that ledger."
--
-- So arrival is counted somewhere else, before any of the recorder's machinery
-- runs, and the two are reconciled by difference.
--
-- WHY THIS IS NOT A SECOND REGISTRY (materialized-evidence rule 15)
-- Rule 15 forbids a parallel EVIDENCE registry. This table holds no evidence:
-- no question, no answer, no citations, no packet, no content of any kind. It
-- is a measuring instrument — "a request arrived / a response left" — and its
-- whole purpose is to be independent of the ledger it measures. Storing it in
-- `decision_traces` would defeat the requirement by construction.
--
-- TWO APPENDED ROWS, keyed by attempt_id (the same discipline 092 settled on):
--   phase='arrived'   written before auth, validation, retrieval or provider
--                     work — the earliest point the process can honestly say a
--                     request existed.
--   phase='responded' written in a `finally`, carrying the HTTP status that
--                     actually left. No UPDATE, so the arrival can never be
--                     rewritten to look accounted-for.
--
-- The reconciliation this enables:
--   arrived                                     — every request that reached the handler
--   responded 4xx/5xx AND no ledger start       — a PRE-ACCEPT failure (expected; its own denominator)
--   responded 2xx      AND no ledger start      — a LOST START. The capture defect.
--   ledger start       AND no ledger close      — an unfinished turn (091's orphan)
--
-- `attempt_id` is minted at arrival and handed to `openTurn`, so the ingress
-- row and the ledger row share a key and the join is exact rather than
-- heuristic on timestamps.
--
-- WHAT IT NEVER STORES: no credentials, no cookies, no bearer tokens, no
-- message text, no answer text, no file contents. `client_request_id` is a
-- client-minted UUID and nothing else.
--
-- Idempotent throughout; safe to re-run.

BEGIN;

CREATE TABLE IF NOT EXISTS turn_ingress (
    ingress_id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    attempt_id        UUID        NOT NULL,
    phase             TEXT        NOT NULL,
    route             TEXT        NOT NULL,
    -- NULL on an unauthenticated arrival: a 401 has no tenant, and pretending
    -- otherwise would put a rejected stranger inside a tenant's counts.
    tenant_id         TEXT,
    notebook_id       UUID,
    client_request_id TEXT,
    http_status       INTEGER,
    environment       TEXT,
    git_sha           TEXT,
    at                TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- At most one arrival and one response per attempt. A retried write is absorbed
-- by the conflict instead of inflating the denominator — an over-counted
-- arrival would manufacture phantom "lost starts".
CREATE UNIQUE INDEX IF NOT EXISTS turn_ingress_attempt_phase_uk
    ON turn_ingress (attempt_id, phase);

-- The reconciliation window scan.
CREATE INDEX IF NOT EXISTS turn_ingress_at_idx ON turn_ingress (at DESC);

-- Per-tenant coverage without scanning every tenant's arrivals.
CREATE INDEX IF NOT EXISTS turn_ingress_tenant_at_idx
    ON turn_ingress (tenant_id, at DESC) WHERE tenant_id IS NOT NULL;

-- Append-only from the request path, exactly like decision_traces (032): the
-- app role may read and insert, never mutate or delete. A counter the request
-- path can rewrite is not a counter.
GRANT SELECT, INSERT ON turn_ingress TO factorylm_app;
GRANT USAGE, SELECT ON SEQUENCE turn_ingress_ingress_id_seq TO factorylm_app;

COMMIT;
