#!/usr/bin/env python3
"""Generate the mira-proxy SSRF allowlist from display_endpoints.

Emits an nginx `map $display_id $upstream { ... }` block to stdout. Each enabled
row becomes `<id> "<host>:<port>";`. nginx uses it to resolve a request's
display_id to an upstream host:port; an id not in the map resolves to "" → 404,
so the proxy can ONLY ever reach hosts that an operator registered in
display_endpoints. This is the SSRF boundary (goal prompt risks §).

Read-only against the DB (SELECT only). Run with the target env's Doppler config:

    doppler run -p factorylm -c stg -- python mira-proxy/gen_allowlist.py \
        > mira-proxy/conf.d/allowlist.conf

then reload nginx (docker compose exec mira-proxy nginx -s reload).

Default port by scheme when port is NULL: http→80, https→443. Only http/https
upstreams are emitted (the iframe is HTTP/WS; vnc/signals are handled elsewhere).
"""
from __future__ import annotations

import os
import sys

import psycopg2  # psycopg2-binary — matches tools/*.py DB scripts


SCHEME_DEFAULT_PORT = {"http": 80, "https": 443}


def main() -> int:
    url = os.environ.get("NEON_DATABASE_URL", "")
    if not url:
        print("# ERROR: NEON_DATABASE_URL not set", file=sys.stderr)
        return 1

    conn = psycopg2.connect(url, sslmode="require")
    try:
        with conn.cursor() as cur:
            # display_type web_iframe / nodered are the framed-web kinds; vnc/signals
            # are not plain HTTP upstreams and are excluded from the proxy allowlist.
            cur.execute(
                """
                SELECT id::text, scheme, host, port
                  FROM display_endpoints
                 WHERE enabled = true
                   AND display_type IN ('web_iframe', 'nodered')
                 ORDER BY id
                """
            )
            rows = cur.fetchall()
    finally:
        conn.close()

    lines = [
        "# GENERATED by mira-proxy/gen_allowlist.py — do not edit by hand.",
        "# Maps Command Center display_id -> upstream host:port (SSRF allowlist).",
        "map $display_id $upstream {",
        "    default '';",
    ]
    emitted = 0
    for did, scheme, host, port in rows:
        scheme = (scheme or "http").lower()
        if scheme not in SCHEME_DEFAULT_PORT:
            continue
        if not host:
            continue
        eff_port = port or SCHEME_DEFAULT_PORT[scheme]
        # host is operator-entered; keep it strict — host[:port] only, no slashes.
        if "/" in host or " " in host:
            print(f"# SKIP malformed host for {did}: {host!r}", file=sys.stderr)
            continue
        lines.append(f'    "{did}" "{host}:{eff_port}";')
        emitted += 1
    lines.append("}")
    lines.append(f"# {emitted} display(s) allowlisted.")
    sys.stdout.write("\n".join(lines) + "\n")
    print(f"# wrote {emitted} allowlist entries", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
