"""Tests for the drive-pack manual extractor (PR-A, hardened).

Runs entirely against the SYNTHETIC fixture
(``tools/drive-pack-extract/fixtures/pf_sample.pdf``, generated by
``_make_pf_sample_pdf.py``) — the real PowerFlex manual is never read in CI
and is not present in this repo. The fixture reproduces the real manual's
MEASURED messiness (position-only column separation, a row's Description
rendering on a different physical line than its own code, a footnote paren
glued onto a code/Fault-Type, a shared group whose Fault-Type value floats
mid-group, a fault->parameter cross-reference rendering above its own code
line, a Min/Max column wrapping across 4 lines with the code line landing in
the middle, and the real manual's quoted-option-with-inline-"(Default)" enum
shape) — see ``_make_pf_sample_pdf.py``'s module docstring for the full list.
"""

from __future__ import annotations

from pathlib import Path

import cite_integrity
import extractor

FIXTURE = Path(__file__).parent.parent / "fixtures" / "pf_sample.pdf"


def _faults():
    return extractor.parse_faults(FIXTURE)


def _params():
    return extractor.parse_parameters(FIXTURE)


# ---------------------------------------------------------------------------
# Fault parser — position-aware Name/Fault-Type recovery
# ---------------------------------------------------------------------------


def test_parse_faults_extracts_known_codes_with_clean_name():
    by_id = {f["fault_id"]: f for f in _faults()}

    f004 = by_id["F004"]
    assert f004["code"] == 4
    assert f004["name"] == "UnderVoltage"
    assert f004["fault_type"] == "1"
    assert f004["page"] == 1
    # The row's Description rendered on a DIFFERENT physical line than the
    # code+name+type line (the real manual's actual F004 layout) — proving
    # the name came out clean means the column bins didn't bleed together.
    assert "1" not in f004["name"]
    assert "DC bus" not in f004["name"]


def test_parse_faults_strips_footnote_paren_glued_to_code():
    by_id = {f["fault_id"]: f for f in _faults()}
    f015 = by_id["F015"]
    assert f015["fault_id"] == "F015"  # not "F015(3)"
    assert f015["name"] == "Load Loss"
    assert f015["fault_type"] == "2"


def test_parse_faults_strips_footnote_paren_glued_to_fault_type():
    by_id = {f["fault_id"]: f for f in _faults()}
    f013 = by_id["F013"]
    assert f013["name"] == "Ground Fault"
    assert f013["fault_type"] == "1"  # not "1(2)"


def test_parse_faults_handles_em_dash_fault_type():
    by_id = {f["fault_id"]: f for f in _faults()}
    f000 = by_id["F000"]
    assert f000["name"] == "No Fault"
    assert f000["fault_type"] == "—"


def test_parse_faults_shared_group_yields_one_entry_per_code():
    faults = _faults()
    codes = [f["fault_id"] for f in faults]
    for code in ("F038", "F039", "F040"):
        assert codes.count(code) == 1, f"expected exactly one entry for {code}"


def test_every_fault_row_has_a_recovered_fault_type_not_none():
    """Regression for the real-manual bug where scoping by RE-SLICING pages
    into a new PDF (rather than selecting pages by number from the original)
    reordered pages and destroyed the per-page column geometry the Fault-Type
    column depends on — every fault_type came back ``None``. Every fault in
    the fixture must carry SOME recovered value (a real "1"/"2"/em-dash),
    never ``None`` or an empty string."""
    for fault in _faults():
        assert fault["fault_type"], f"{fault['fault_id']} has no recovered fault_type"


def test_parse_faults_shared_group_fault_type_floats_mid_group():
    """Regression: the real manual sometimes renders a shared group's
    Fault-Type value BETWEEN member lines (closing after the 2nd member) —
    the trailing 3rd member (F040) must still inherit the same type, not get
    swallowed into whatever unrelated fault happens to close next."""
    by_id = {f["fault_id"]: f for f in _faults()}
    for code, name in (
        ("F038", "Phase U to Gnd"),
        ("F039", "Phase V to Gnd"),
        ("F040", "Phase W to Gnd"),
    ):
        assert by_id[code]["name"] == name
        assert by_id[code]["fault_type"] == "2"


# ---------------------------------------------------------------------------
# references_parameters — fault -> parameter cross-refs (correct DIRECTION)
# ---------------------------------------------------------------------------


def test_fault_references_parameters_captured_even_when_action_renders_above_code_line():
    """F081's "Modify using C125 [...]" action text renders ABOVE its own
    code line in the fixture (mirroring the real manual's F081 layout) —
    nearest-row assignment must still attribute it to F081."""
    by_id = {f["fault_id"]: f for f in _faults()}
    assert by_id["F081"]["references_parameters"] == ["C125"]


def test_fault_references_parameters_empty_when_no_cross_ref():
    by_id = {f["fault_id"]: f for f in _faults()}
    for code in ("F004", "F015", "F013", "F000", "F038", "F039", "F040"):
        assert by_id[code]["references_parameters"] == []


# ---------------------------------------------------------------------------
# Parameter parser — grid layout (position-aware)
# ---------------------------------------------------------------------------


def test_parse_parameters_grid_layout_captures_range_and_default():
    by_id = {p["parameter_id"]: p for p in _params()}
    p042 = by_id["P042"]
    assert p042["name"] == "Decel Time 1"
    assert p042["range"] == "0.00/600.00"
    assert p042["default"] == "10.00"
    assert p042["unit"] == "s"
    assert "decel" in p042["purpose"].lower()


def test_parse_parameters_grid_layout_recovers_name_despite_code_line_mid_span():
    """P031's Min/Max wraps across 4 physical lines, and its OWN code+name
    line renders in the MIDDLE of that span (not at the start or end) — the
    real manual's actual P031 "Motor NP Volts" layout. The name must still
    come out clean via bracket-span extraction, independent of the code
    line's position."""
    by_id = {p["parameter_id"]: p for p in _params()}
    p031 = by_id["P031"]
    assert p031["name"] == "Motor NP Volts"
    assert "nameplate" in p031["purpose"].lower()


def test_parse_parameters_grid_footnote_definition_line_does_not_corrupt_next_row():
    """A footnote-definition line between P042 and P031 glues a bracket
    reference to another parameter's id with no space ("A535[Motor") — this
    must not swallow P031's own "[Motor NP Volts]" bracket into one giant
    garbled span."""
    by_id = {p["parameter_id"]: p for p in _params()}
    assert by_id["P031"]["name"] == "Motor NP Volts"
    assert "A535" not in by_id["P031"]["name"]
    assert "Fdbk" not in by_id["P031"]["name"]


def test_parse_parameters_grid_worded_range_and_default_kept_honest_not_fabricated():
    """P031's Min/Max is a compound, non-numeric, per-voltage-class range
    ("10V (for 200V Drives), 20V (for 400V Drives), 25V (for 600V
    Drives)/Drive Rated Volts") and its Default is a worded phrase ("Based on
    Drive Rating") rather than a number — the real manual's actual P031 row
    (confirmed on a real-manual run: P031/P033/P034/P037/C121-123/C125/C127-
    128 all carry a worded or conditional default with no clean numeric
    range). Both must come out HONEST: ``range=None`` (never a fabricated
    numeric guess pulled from the surrounding prose) and ``default`` equal to
    the worded phrase verbatim (never silently dropped, never coerced into a
    number)."""
    by_id = {p["parameter_id"]: p for p in _params()}
    p031 = by_id["P031"]
    assert p031["range"] is None
    assert p031["default"] == "Based on Drive Rating"


# ---------------------------------------------------------------------------
# Parameter parser — labeled-block layout
# ---------------------------------------------------------------------------


def test_parse_parameters_labeled_block_layout_captures_range_and_default():
    by_id = {p["parameter_id"]: p for p in _params()}
    c124 = by_id["C124"]
    assert c124["name"] == "RS485 Node Addr"
    assert c124["default"] == "100"
    assert c124["range"] == "1/247"


def test_parse_parameters_labeled_block_quoted_options_with_inline_default():
    """The real manual's enum options render as quoted, one per line, with
    an inline "(Default)" marker (e.g. `0 "Fault" (Default)`) rather than a
    single "Options: 0 Fault, 1 Coast Stop, ..." line — this must recover
    BOTH the value_meanings AND the default from that marker."""
    by_id = {p["parameter_id"]: p for p in _params()}
    c125 = by_id["C125"]
    assert c125["name"] == "Comm Loss Action"
    assert c125["default"] == "0"
    assert {"value": "0", "meaning": "Fault"} in c125["value_meanings"]
    assert {"value": "1", "meaning": "Coast Stop"} in c125["value_meanings"]
    assert {"value": "2", "meaning": "Stop"} in c125["value_meanings"]


# ---------------------------------------------------------------------------
# related_faults semantics — THE fix: only fault codes, never a parameter id,
# and never sourced from a parameter's own "Related Parameters:" line.
# ---------------------------------------------------------------------------


def test_related_parameters_line_is_captured_separately_not_as_related_faults():
    """C125's own "Related Parameters: P045" line is a param<->param link —
    it must land in ``related_parameters``, and ``related_faults`` must
    start EMPTY (not yet linked from the fault table)."""
    by_id = {p["parameter_id"]: p for p in _params()}
    c125 = by_id["C125"]
    assert c125["related_parameters"] == ["P045"]
    assert c125["related_faults"] == []


def test_link_fault_actions_to_parameters_builds_related_faults_from_fault_action():
    """The genuine fault->param link comes from the FAULT table's action
    text ("Modify using C125 [...]"), never from a parameter's own "Related
    Parameters:" line. After linking, C125.related_faults must be the FAULT
    code(s) whose action referenced it — never "P045" (a parameter id)."""
    faults = _faults()
    params = _params()
    extractor.link_fault_actions_to_parameters(faults, params)

    by_id = {p["parameter_id"]: p for p in params}
    assert by_id["C125"]["related_faults"] == ["F081"]
    # The param<->param field is untouched by linking.
    assert by_id["C125"]["related_parameters"] == ["P045"]


def test_link_never_puts_a_parameter_id_into_related_faults():
    """Broad sanity sweep: after linking, no parameter's related_faults ever
    contains something that isn't a real fault_id from the fault table."""
    faults = _faults()
    params = _params()
    extractor.link_fault_actions_to_parameters(faults, params)

    fault_ids = {f["fault_id"] for f in faults}
    for param in params:
        for ref in param["related_faults"]:
            assert ref in fault_ids, (
                f"{param['parameter_id']}.related_faults has non-fault id {ref!r}"
            )


def test_related_faults_non_linked_entries_stay_empty_no_inference():
    faults = _faults()
    params = _params()
    extractor.link_fault_actions_to_parameters(faults, params)

    by_id = {p["parameter_id"]: p for p in params}
    assert by_id["P042"]["related_faults"] == []
    assert by_id["C124"]["related_faults"] == []


# ---------------------------------------------------------------------------
# Page-range scoping — select pages by 1-based number from the ORIGINAL pdf.
# Added after the real-manual run showed the un-scoped ``extract()`` times
# out (>280s) walking all 274 pages, and that re-slicing into a new PDF (an
# earlier, wrong fix attempt) reorders pages and destroys the per-page
# column geometry the position-aware parsers depend on — proven above by the
# Fault-Type recovery regression. The fixture has 3 pages: 1 = fault table,
# 2 = grid parameters, 3 = labeled-block parameters.
# ---------------------------------------------------------------------------


def test_parse_faults_pages_scopes_to_the_requested_page():
    scoped = extractor.parse_faults(FIXTURE, pages=[1])
    assert {f["fault_id"] for f in scoped} == {f["fault_id"] for f in _faults()}
    assert all(f["page"] == 1 for f in scoped)


def test_parse_parameters_pages_scopes_to_the_requested_pages():
    scoped = extractor.parse_parameters(FIXTURE, pages=[2, 3])
    assert {p["parameter_id"] for p in scoped} == {p["parameter_id"] for p in _params()}


def test_extract_threads_fault_pages_and_param_pages_through():
    """``extract()``'s ``fault_pages``/``param_pages`` kwargs must reach the
    underlying parsers — a scoped run must recover the same fragment as the
    whole-document (``pages=None``) default on this small fixture."""
    scoped = extractor.extract(
        FIXTURE, doc="pf_sample.pdf (synthetic)", fault_pages=[1], param_pages=[2, 3]
    )
    whole_doc = extractor.extract(FIXTURE, doc="pf_sample.pdf (synthetic)")
    assert scoped["fault_codes"] == whole_doc["fault_codes"]
    scoped_param_ids = {p["parameter_id"] for p in scoped["parameters"]}
    whole_doc_param_ids = {p["parameter_id"] for p in whole_doc["parameters"]}
    assert scoped_param_ids == whole_doc_param_ids


# ---------------------------------------------------------------------------
# Cross-parser safe-drop — a parameter-only page fed to the FAULT parser (and
# a fault-only page fed to the PARAMETER parser) must yield nothing, never a
# fabricated entry. This is what let the real manual's un-scoped whole-doc
# scan run safely (if slowly) before page scoping existed — scoping makes it
# fast, but a caller that under/over-scopes must still get a safe drop, not
# invented data.
# ---------------------------------------------------------------------------


def test_fault_parser_on_a_param_only_page_yields_no_fabricated_faults():
    assert extractor.parse_faults(FIXTURE, pages=[2]) == []  # grid param page
    assert extractor.parse_faults(FIXTURE, pages=[3]) == []  # labeled param page


def test_param_parser_on_a_fault_only_page_yields_no_fabricated_parameters():
    assert extractor.parse_parameters(FIXTURE, pages=[1]) == []  # fault table page


# ---------------------------------------------------------------------------
# Cite-integrity self-test — WITH TEETH (mirrors
# mira-bots/tests/test_drive_packs_readonly.py's catch-synthetic-violations
# self-test): a real excerpt verifies, a fabricated one does not.
# ---------------------------------------------------------------------------


def test_cite_integrity_accepts_a_real_excerpt():
    real_excerpt = "F004 UnderVoltage 1"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, real_excerpt) is True


def test_cite_integrity_rejects_a_fabricated_excerpt():
    fabricated = "F999 TotallyMadeUpFault this sentence never appears in the manual"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, fabricated) is False


def test_cite_integrity_rejects_real_text_claimed_on_the_wrong_page():
    real_excerpt_from_page_1 = "F004 UnderVoltage 1"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 2, real_excerpt_from_page_1) is False


def test_cite_integrity_rejects_empty_excerpt():
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, "") is False
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, "   ") is False


def test_cite_integrity_is_tolerant_of_whitespace_normalization():
    # Same words, different internal whitespace/newlines — must still verify,
    # since extract_text() line-wrapping shouldn't break a genuine citation.
    wrapped = "F004  UnderVoltage\n1"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, wrapped) is True


# ---------------------------------------------------------------------------
# The extractor DROPS entries with an unverifiable excerpt
# ---------------------------------------------------------------------------


def test_verify_and_filter_drops_fabricated_entry_keeps_real_one():
    real_entry = {
        "fault_id": "F004",
        "page": 1,
        "excerpt": "F004 UnderVoltage 1",
    }
    fabricated_entry = {
        "fault_id": "F999",
        "page": 1,
        "excerpt": "F999 TotallyMadeUpFault this text was never in the manual at all",
    }

    kept = extractor.verify_and_filter_entries(
        FIXTURE, [real_entry, fabricated_entry], label="fault"
    )

    kept_ids = [e["fault_id"] for e in kept]
    assert "F004" in kept_ids
    assert "F999" not in kept_ids
    assert len(kept) == 1


def test_extract_end_to_end_never_emits_a_fabricated_entry():
    fragment = extractor.extract(FIXTURE, doc="pf_sample.pdf (synthetic)")

    # Every real fault/param code that should have parsed is present, with a
    # clean name (no footnote digit, no bled-in description text).
    assert fragment["fault_codes"][4] == "UnderVoltage"
    assert fragment["fault_codes"][38] == "Phase U to Gnd"
    assert fragment["fault_codes"][81] == "DSI Comm Loss"
    parameter_ids = {p["parameter_id"] for p in fragment["parameters"]}
    assert {"P042", "P031", "C124", "C125"} <= parameter_ids

    # related_faults semantics hold end-to-end: C125 carries the FAULT code
    # (F081) whose action referenced it, never the "P045" param<->param link.
    by_id = {p["parameter_id"]: p for p in fragment["parameters"]}
    assert by_id["C125"]["related_faults"] == ["F081"]

    # Every citation the fragment carries must independently re-verify — the
    # extractor's own output is provably non-fabricated, not just "trust me".
    for citation in fragment["fault_citations"]:
        assert cite_integrity.verify_excerpt_on_page(
            FIXTURE, int(citation["page"]), citation["excerpt"]
        )
    for param in fragment["parameters"]:
        sc = param["source_citation"]
        assert cite_integrity.verify_excerpt_on_page(FIXTURE, int(sc["page"]), sc["excerpt"])
        assert param["provenance_tier"] == "manual_cited"


def test_fixture_is_clearly_marked_synthetic():
    """Guard against ever mistaking this fixture for a real licensed manual."""
    pages = extractor.read_pages(FIXTURE)
    full_text = " ".join(text for _, text in pages)
    assert "SYNTHETIC TEST FIXTURE" in full_text
    assert "not a licensed manual" in full_text
