"""Tests for the drive-pack manual extractor (PR-A, hardened).

Runs entirely against the SYNTHETIC fixture
(``tools/drive-pack-extract/fixtures/pf_sample.pdf``, generated by
``_make_pf_sample_pdf.py``) — the real PowerFlex manual is never read in CI
and is not present in this repo. The fixture reproduces the real manual's
MEASURED messiness (position-only column separation, a row's Description
rendering on a different physical line than its own code, a footnote paren
glued onto a code/Fault-Type, a shared group whose Fault-Type value floats
mid-group, a fault->parameter cross-reference rendering above its own code
line, a Min/Max column wrapping across 4 lines with the code line landing in
the middle, and the real manual's quoted-option-with-inline-"(Default)" enum
shape) — see ``_make_pf_sample_pdf.py``'s module docstring for the full list.
"""

from __future__ import annotations

from pathlib import Path

import cite_integrity
import extractor

FIXTURE = Path(__file__).parent.parent / "fixtures" / "pf_sample.pdf"


def _faults():
    return extractor.parse_faults(FIXTURE)


def _params():
    return extractor.parse_parameters(FIXTURE)


# ---------------------------------------------------------------------------
# Fault parser — position-aware Name/Fault-Type recovery
# ---------------------------------------------------------------------------


def test_parse_faults_extracts_known_codes_with_clean_name():
    by_id = {f["fault_id"]: f for f in _faults()}

    f004 = by_id["F004"]
    assert f004["code"] == 4
    assert f004["name"] == "UnderVoltage"
    assert f004["fault_type"] == "1"
    assert f004["page"] == 1
    # The row's Description rendered on a DIFFERENT physical line than the
    # code+name+type line (the real manual's actual F004 layout) — proving
    # the name came out clean means the column bins didn't bleed together.
    assert "1" not in f004["name"]
    assert "DC bus" not in f004["name"]


def test_parse_faults_strips_footnote_paren_glued_to_code():
    by_id = {f["fault_id"]: f for f in _faults()}
    f015 = by_id["F015"]
    assert f015["fault_id"] == "F015"  # not "F015(3)"
    assert f015["name"] == "Load Loss"
    assert f015["fault_type"] == "2"


def test_parse_faults_strips_footnote_paren_glued_to_fault_type():
    by_id = {f["fault_id"]: f for f in _faults()}
    f013 = by_id["F013"]
    assert f013["name"] == "Ground Fault"
    assert f013["fault_type"] == "1"  # not "1(2)"


def test_parse_faults_handles_em_dash_fault_type():
    by_id = {f["fault_id"]: f for f in _faults()}
    f000 = by_id["F000"]
    assert f000["name"] == "No Fault"
    assert f000["fault_type"] == "—"


def test_parse_faults_shared_group_yields_one_entry_per_code():
    faults = _faults()
    codes = [f["fault_id"] for f in faults]
    for code in ("F038", "F039", "F040"):
        assert codes.count(code) == 1, f"expected exactly one entry for {code}"


def test_every_fault_row_has_a_recovered_fault_type_not_none():
    """Regression for the real-manual bug where scoping by RE-SLICING pages
    into a new PDF (rather than selecting pages by number from the original)
    reordered pages and destroyed the per-page column geometry the Fault-Type
    column depends on — every fault_type came back ``None``. Every fault in
    the fixture must carry SOME recovered value (a real "1"/"2"/em-dash),
    never ``None`` or an empty string."""
    for fault in _faults():
        assert fault["fault_type"], f"{fault['fault_id']} has no recovered fault_type"


def test_parse_faults_shared_group_fault_type_floats_mid_group():
    """Regression: the real manual sometimes renders a shared group's
    Fault-Type value BETWEEN member lines (closing after the 2nd member) —
    the trailing 3rd member (F040) must still inherit the same type, not get
    swallowed into whatever unrelated fault happens to close next."""
    by_id = {f["fault_id"]: f for f in _faults()}
    for code, name in (
        ("F038", "Phase U to Gnd"),
        ("F039", "Phase V to Gnd"),
        ("F040", "Phase W to Gnd"),
    ):
        assert by_id[code]["name"] == name
        assert by_id[code]["fault_type"] == "2"


# ---------------------------------------------------------------------------
# references_parameters — fault -> parameter cross-refs (correct DIRECTION)
# ---------------------------------------------------------------------------


def test_fault_references_parameters_captured_even_when_action_renders_above_code_line():
    """F081's "Modify using C125 [...]" action text renders ABOVE its own
    code line in the fixture (mirroring the real manual's F081 layout) —
    nearest-row assignment must still attribute it to F081."""
    by_id = {f["fault_id"]: f for f in _faults()}
    assert by_id["F081"]["references_parameters"] == ["C125"]


def test_fault_references_parameters_empty_when_no_cross_ref():
    by_id = {f["fault_id"]: f for f in _faults()}
    for code in ("F004", "F015", "F013", "F000", "F038", "F039", "F040"):
        assert by_id[code]["references_parameters"] == []


# ---------------------------------------------------------------------------
# Parameter parser — grid layout (position-aware)
# ---------------------------------------------------------------------------


def test_parse_parameters_grid_layout_captures_range_and_default():
    by_id = {p["parameter_id"]: p for p in _params()}
    p042 = by_id["P042"]
    assert p042["name"] == "Decel Time 1"
    assert p042["range"] == "0.00/600.00"
    assert p042["default"] == "10.00"
    assert p042["unit"] == "s"
    assert "decel" in p042["purpose"].lower()


def test_parse_parameters_grid_layout_recovers_name_despite_code_line_mid_span():
    """P031's Min/Max wraps across 4 physical lines, and its OWN code+name
    line renders in the MIDDLE of that span (not at the start or end) — the
    real manual's actual P031 "Motor NP Volts" layout. The name must still
    come out clean via bracket-span extraction, independent of the code
    line's position."""
    by_id = {p["parameter_id"]: p for p in _params()}
    p031 = by_id["P031"]
    assert p031["name"] == "Motor NP Volts"
    assert "nameplate" in p031["purpose"].lower()


def test_parse_parameters_grid_footnote_definition_line_does_not_corrupt_next_row():
    """A footnote-definition line between P042 and P031 glues a bracket
    reference to another parameter's id with no space ("A535[Motor") — this
    must not swallow P031's own "[Motor NP Volts]" bracket into one giant
    garbled span."""
    by_id = {p["parameter_id"]: p for p in _params()}
    assert by_id["P031"]["name"] == "Motor NP Volts"
    assert "A535" not in by_id["P031"]["name"]
    assert "Fdbk" not in by_id["P031"]["name"]


def test_parse_parameters_grid_worded_range_and_default_kept_honest_not_fabricated():
    """P031's Min/Max is a compound, non-numeric, per-voltage-class range
    ("10V (for 200V Drives), 20V (for 400V Drives), 25V (for 600V
    Drives)/Drive Rated Volts") and its Default is a worded phrase ("Based on
    Drive Rating") rather than a number — the real manual's actual P031 row
    (confirmed on a real-manual run: P031/P033/P034/P037/C121-123/C125/C127-
    128 all carry a worded or conditional default with no clean numeric
    range). Both must come out HONEST: ``range=None`` (never a fabricated
    numeric guess pulled from the surrounding prose) and ``default`` equal to
    the worded phrase verbatim (never silently dropped, never coerced into a
    number)."""
    by_id = {p["parameter_id"]: p for p in _params()}
    p031 = by_id["P031"]
    assert p031["range"] is None
    assert p031["default"] == "Based on Drive Rating"


# ---------------------------------------------------------------------------
# Parameter parser — labeled-block layout
# ---------------------------------------------------------------------------


def test_parse_parameters_labeled_block_layout_captures_range_and_default():
    by_id = {p["parameter_id"]: p for p in _params()}
    c124 = by_id["C124"]
    assert c124["name"] == "RS485 Node Addr"
    assert c124["default"] == "100"
    assert c124["range"] == "1/247"


def test_parse_parameters_labeled_block_quoted_options_with_inline_default():
    """The real manual's enum options render as quoted, one per line, with
    an inline "(Default)" marker (e.g. `0 "Fault" (Default)`) rather than a
    single "Options: 0 Fault, 1 Coast Stop, ..." line — this must recover
    BOTH the value_meanings AND the default from that marker."""
    by_id = {p["parameter_id"]: p for p in _params()}
    c125 = by_id["C125"]
    assert c125["name"] == "Comm Loss Action"
    assert c125["default"] == "0"
    assert {"value": "0", "meaning": "Fault"} in c125["value_meanings"]
    assert {"value": "1", "meaning": "Coast Stop"} in c125["value_meanings"]
    assert {"value": "2", "meaning": "Stop"} in c125["value_meanings"]


# ---------------------------------------------------------------------------
# related_faults semantics — THE fix: only fault codes, never a parameter id,
# and never sourced from a parameter's own "Related Parameters:" line.
# ---------------------------------------------------------------------------


def test_related_parameters_line_is_captured_separately_not_as_related_faults():
    """C125's own "Related Parameters: P045" line is a param<->param link —
    it must land in ``related_parameters``, and ``related_faults`` must
    start EMPTY (not yet linked from the fault table)."""
    by_id = {p["parameter_id"]: p for p in _params()}
    c125 = by_id["C125"]
    assert c125["related_parameters"] == ["P045"]
    assert c125["related_faults"] == []


def test_link_fault_actions_to_parameters_builds_related_faults_from_fault_action():
    """The genuine fault->param link comes from the FAULT table's action
    text ("Modify using C125 [...]"), never from a parameter's own "Related
    Parameters:" line. After linking, C125.related_faults must be the FAULT
    code(s) whose action referenced it — never "P045" (a parameter id)."""
    faults = _faults()
    params = _params()
    extractor.link_fault_actions_to_parameters(faults, params)

    by_id = {p["parameter_id"]: p for p in params}
    assert by_id["C125"]["related_faults"] == ["F081"]
    # The param<->param field is untouched by linking.
    assert by_id["C125"]["related_parameters"] == ["P045"]


def test_link_never_puts_a_parameter_id_into_related_faults():
    """Broad sanity sweep: after linking, no parameter's related_faults ever
    contains something that isn't a real fault_id from the fault table."""
    faults = _faults()
    params = _params()
    extractor.link_fault_actions_to_parameters(faults, params)

    fault_ids = {f["fault_id"] for f in faults}
    for param in params:
        for ref in param["related_faults"]:
            assert ref in fault_ids, (
                f"{param['parameter_id']}.related_faults has non-fault id {ref!r}"
            )


def test_related_faults_non_linked_entries_stay_empty_no_inference():
    faults = _faults()
    params = _params()
    extractor.link_fault_actions_to_parameters(faults, params)

    by_id = {p["parameter_id"]: p for p in params}
    assert by_id["P042"]["related_faults"] == []
    assert by_id["C124"]["related_faults"] == []


# ---------------------------------------------------------------------------
# Page-range scoping — select pages by 1-based number from the ORIGINAL pdf.
# Added after the real-manual run showed the un-scoped ``extract()`` times
# out (>280s) walking all 274 pages, and that re-slicing into a new PDF (an
# earlier, wrong fix attempt) reorders pages and destroys the per-page
# column geometry the position-aware parsers depend on — proven above by the
# Fault-Type recovery regression. The fixture has 5 pages: 1 = 520/525 fault
# table, 2 = grid parameters, 3 = labeled-block parameters, 4 = PowerFlex 40
# fault table (circled-digit Fault-Type), 5 = PowerFlex 40 labeled parameters.
# ---------------------------------------------------------------------------


def test_parse_faults_pages_scopes_to_the_requested_page():
    scoped = extractor.parse_faults(FIXTURE, pages=[1, 4])
    assert {f["fault_id"] for f in scoped} == {f["fault_id"] for f in _faults()}
    assert all(f["page"] in (1, 4) for f in scoped)


def test_parse_parameters_pages_scopes_to_the_requested_pages():
    scoped = extractor.parse_parameters(FIXTURE, pages=[2, 3, 5])
    assert {p["parameter_id"] for p in scoped} == {p["parameter_id"] for p in _params()}


def test_extract_threads_fault_pages_and_param_pages_through():
    """``extract()``'s ``fault_pages``/``param_pages`` kwargs must reach the
    underlying parsers — a scoped run must recover the same fragment as the
    whole-document (``pages=None``) default on this small fixture."""
    scoped = extractor.extract(
        FIXTURE, doc="pf_sample.pdf (synthetic)", fault_pages=[1, 4], param_pages=[2, 3, 5]
    )
    whole_doc = extractor.extract(FIXTURE, doc="pf_sample.pdf (synthetic)")
    assert scoped["fault_codes"] == whole_doc["fault_codes"]
    scoped_param_ids = {p["parameter_id"] for p in scoped["parameters"]}
    whole_doc_param_ids = {p["parameter_id"] for p in whole_doc["parameters"]}
    assert scoped_param_ids == whole_doc_param_ids


# ---------------------------------------------------------------------------
# Cross-parser safe-drop — a parameter-only page fed to the FAULT parser (and
# a fault-only page fed to the PARAMETER parser) must yield nothing, never a
# fabricated entry. This is what let the real manual's un-scoped whole-doc
# scan run safely (if slowly) before page scoping existed — scoping makes it
# fast, but a caller that under/over-scopes must still get a safe drop, not
# invented data.
# ---------------------------------------------------------------------------


def test_fault_parser_on_a_param_only_page_yields_no_fabricated_faults():
    assert extractor.parse_faults(FIXTURE, pages=[2]) == []  # grid param page
    assert extractor.parse_faults(FIXTURE, pages=[3]) == []  # labeled param page
    assert extractor.parse_faults(FIXTURE, pages=[5]) == []  # PF40 labeled param page


def test_param_parser_on_a_fault_only_page_yields_no_fabricated_parameters():
    assert extractor.parse_parameters(FIXTURE, pages=[1]) == []  # fault table page


# ---------------------------------------------------------------------------
# Cite-integrity self-test — WITH TEETH (mirrors
# mira-bots/tests/test_drive_packs_readonly.py's catch-synthetic-violations
# self-test): a real excerpt verifies, a fabricated one does not.
# ---------------------------------------------------------------------------


def test_cite_integrity_accepts_a_real_excerpt():
    real_excerpt = "F004 UnderVoltage 1"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, real_excerpt) is True


def test_cite_integrity_rejects_a_fabricated_excerpt():
    fabricated = "F999 TotallyMadeUpFault this sentence never appears in the manual"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, fabricated) is False


def test_cite_integrity_rejects_real_text_claimed_on_the_wrong_page():
    real_excerpt_from_page_1 = "F004 UnderVoltage 1"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 2, real_excerpt_from_page_1) is False


def test_cite_integrity_rejects_empty_excerpt():
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, "") is False
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, "   ") is False


def test_is_chapter_section_label():
    # chapter-section labels (AutomationDirect GS10 style) vs integer pages
    assert cite_integrity.is_chapter_section_label("4-188") is True
    assert cite_integrity.is_chapter_section_label("3-6") is True
    assert cite_integrity.is_chapter_section_label("A-12") is True
    assert cite_integrity.is_chapter_section_label("162") is False  # int-string
    assert cite_integrity.is_chapter_section_label(162) is False  # int
    assert cite_integrity.is_chapter_section_label("F004") is False
    assert cite_integrity.is_chapter_section_label("") is False


def test_verify_excerpt_in_document_finds_real_text_anywhere():
    # A citation whose page is a chapter-section label ("4-188") is verified
    # whole-document — the excerpt exists on SOME page (still catches fabrication),
    # just not pinned to one page.
    # "F004 UnderVoltage" is on fixture page 1; "[Decel Time 1]" on page 2 — both
    # found whole-document regardless of the (chapter-section) page cited.
    assert cite_integrity.verify_excerpt_in_document(FIXTURE, "F004 UnderVoltage") is True
    assert cite_integrity.verify_excerpt_in_document(FIXTURE, "[Decel Time 1]") is True
    assert cite_integrity.verify_excerpt_in_document(FIXTURE, "invented text nowhere in manual") is False
    assert cite_integrity.verify_excerpt_in_document(FIXTURE, "") is False


def test_cite_integrity_is_tolerant_of_whitespace_normalization():
    # Same words, different internal whitespace/newlines — must still verify,
    # since extract_text() line-wrapping shouldn't break a genuine citation.
    wrapped = "F004  UnderVoltage\n1"
    assert cite_integrity.verify_excerpt_on_page(FIXTURE, 1, wrapped) is True


# ---------------------------------------------------------------------------
# The extractor DROPS entries with an unverifiable excerpt
# ---------------------------------------------------------------------------


def test_verify_and_filter_drops_fabricated_entry_keeps_real_one():
    real_entry = {
        "fault_id": "F004",
        "page": 1,
        "excerpt": "F004 UnderVoltage 1",
    }
    fabricated_entry = {
        "fault_id": "F999",
        "page": 1,
        "excerpt": "F999 TotallyMadeUpFault this text was never in the manual at all",
    }

    kept = extractor.verify_and_filter_entries(
        FIXTURE, [real_entry, fabricated_entry], label="fault"
    )

    kept_ids = [e["fault_id"] for e in kept]
    assert "F004" in kept_ids
    assert "F999" not in kept_ids
    assert len(kept) == 1


def test_extract_end_to_end_never_emits_a_fabricated_entry():
    fragment = extractor.extract(FIXTURE, doc="pf_sample.pdf (synthetic)")

    # Every real fault/param code that should have parsed is present, with a
    # clean name (no footnote digit, no bled-in description text).
    assert fragment["fault_codes"][4] == "UnderVoltage"
    assert fragment["fault_codes"][38] == "Phase U to Gnd"
    assert fragment["fault_codes"][81] == "DSI Comm Loss"
    parameter_ids = {p["parameter_id"] for p in fragment["parameters"]}
    assert {"P042", "P031", "C124", "C125"} <= parameter_ids

    # related_faults semantics hold end-to-end: C125 carries the FAULT code
    # (F081) whose action referenced it, never the "P045" param<->param link.
    by_id = {p["parameter_id"]: p for p in fragment["parameters"]}
    assert by_id["C125"]["related_faults"] == ["F081"]

    # Every citation the fragment carries must independently re-verify — the
    # extractor's own output is provably non-fabricated, not just "trust me".
    for citation in fragment["fault_citations"]:
        assert cite_integrity.verify_excerpt_on_page(
            FIXTURE, int(citation["page"]), citation["excerpt"]
        )
    for param in fragment["parameters"]:
        sc = param["source_citation"]
        assert cite_integrity.verify_excerpt_on_page(FIXTURE, int(sc["page"]), sc["excerpt"])
        assert param["provenance_tier"] == "manual_cited"


def test_fixture_is_clearly_marked_synthetic():
    """Guard against ever mistaking this fixture for a real licensed manual."""
    pages = extractor.read_pages(FIXTURE)
    full_text = " ".join(text for _, text in pages)
    assert "SYNTHETIC TEST FIXTURE" in full_text
    assert "not a licensed manual" in full_text


# ---------------------------------------------------------------------------
# PowerFlex 40 layout hardening — circled-digit Fault-Type column, single-digit
# fault codes, emit-not-drop for untyped faults, wrapped names, the PF40 label
# dialect ("Values Default:" / bare "Min/Max:"), the "Options"-prefixed enum,
# and the bold-header gate that rejects a plain-Helvetica graph callout. All on
# the fixture's pages 4 (PF40 faults) and 5 (PF40 labeled params).
# ---------------------------------------------------------------------------

_PF40_FAULT_PAGES = [4]
_PF40_PARAM_PAGES = [5]


def _pf40_faults():
    return {f["fault_id"]: f for f in extractor.parse_faults(FIXTURE, pages=_PF40_FAULT_PAGES)}


def _pf40_params():
    return {
        p["parameter_id"]: p for p in extractor.parse_parameters(FIXTURE, pages=_PF40_PARAM_PAGES)
    }


def test_circled_digit_helper_maps_all_three_unicode_runs():
    # ➀/➁ (U+2780/1, the real PF40), ①/② (U+2460/1), ❶/❷ (U+2776/7).
    assert extractor._circled_digit("➀") == "1"
    assert extractor._circled_digit("➁") == "2"
    assert extractor._circled_digit("①") == "1"
    assert extractor._circled_digit("❶") == "1"
    assert extractor._circled_digit("A") is None
    assert extractor._circled_digit("2") is None  # a plain digit is not circled
    assert extractor._circled_digit("12") is None  # only single glyphs


def test_pf40_single_digit_fault_codes_parse():
    faults = _pf40_faults()
    assert faults["F2"]["code"] == 2
    assert faults["F2"]["name"] == "Input Fault"
    assert faults["F3"]["code"] == 3
    assert faults["F3"]["name"] == "Bus Warning"


def test_pf40_fault_type_comes_from_the_circled_digit_column():
    faults = _pf40_faults()
    assert faults["F2"]["fault_type"] == "1"  # ➀
    assert faults["F3"]["fault_type"] == "2"  # ➁
    assert faults["F5"]["fault_type"] == "2"  # ➁ on the shared-group leader


def test_pf40_untyped_faults_are_emitted_not_dropped():
    """A shared-group continuation with no own glyph (F6) and a genuinely
    untyped fault (F7, no glyph at all) must still appear in the fault set with
    fault_type "—" — the code+name belongs in the pack's fault map, and the
    type is never fabricated by inheritance."""
    faults = _pf40_faults()
    assert faults["F6"]["fault_type"] == "—"
    assert faults["F6"]["name"] == "Phase B Short"
    assert faults["F7"]["fault_type"] == "—"
    assert faults["F7"]["name"] == "Config Reset"


def test_pf40_wrapped_fault_name_is_rejoined():
    faults = _pf40_faults()
    assert faults["F8"]["name"] == "Heatsink OverTemp"


def test_pf40_last_fault_on_page_does_not_bleed_footer_into_name():
    """The last fault's wrapped-name span must not sweep in the page footer."""
    faults = _pf40_faults()
    for f in faults.values():
        assert "SYNTHETIC" not in f["name"]
        assert "not a licensed" not in f["name"]


def test_pf40_single_digit_code_carries_its_cross_reference():
    """F9 (single-digit code) references A205 via a multi-line numbered action
    list — the cross-vendor comm-loss proof analog (F81 -> A105 on the real
    PF40)."""
    faults = _pf40_faults()
    assert faults["F9"]["references_parameters"] == ["A205"]


def test_pf40_cross_ref_span_containment_attributes_to_the_right_fault():
    """The A205 ref lives several action lines BELOW F9's code line; nearest-by-
    top would misattribute it. No OTHER PF40 fault picks it up."""
    faults = _pf40_faults()
    for fid, f in faults.items():
        if fid != "F9":
            assert "A205" not in f["references_parameters"]


def test_find_cross_refs_tolerates_subpixel_top_jitter():
    """Regression for the real PF525 F100/F109 -> P053 miss: pdfplumber renders
    the bracket token ~0.0003pt ABOVE its own id on one physical line, so a raw
    global (top, x0) sort puts "[Reset" BEFORE "P053" and the "id immediately
    followed by [" adjacency check silently drops the reference. Line-clustering
    (the fix) absorbs that jitter — the same tolerance the rest of the extractor
    already uses (`_LINE_TOL`). The old global-sort implementation returned []
    for exactly these words."""
    words = [
        {"text": "Set", "x0": 444.4, "top": 177.279},
        {"text": "P053", "x0": 456.0, "top": 177.2793},  # id renders 0.0003pt LOWER
        {"text": "[Reset", "x0": 473.1, "top": 177.279},  # its bracket, 0.0003pt HIGHER
        {"text": "To", "x0": 494.7, "top": 177.279},
        {"text": "Defalts]", "x0": 503.5, "top": 177.279},
    ]
    assert [ref for ref, _top in extractor._find_cross_refs(words)] == ["P053"]


def test_pf40_labeled_value_dialect_and_unit_extraction():
    """A201 uses the PF40 label dialect: 'Values Default: 5.0 Secs' (Values on
    Default) + bare 'Min/Max: 0.1/60.0 Secs', with the unit extracted+normalized."""
    a201 = _pf40_params()["A201"]
    assert a201["default"] == "5.0"
    assert a201["range"] == "0.1/60.0"
    assert a201["unit"] == "s"


def test_pf40_options_prefixed_enum_recovers_meanings_and_default():
    """The first option line is prefixed with the label word ('Options 0 "Fault"
    (Default) …'); stripping it recovers the value_meanings and the (Default)."""
    a200 = _pf40_params()["A200"]
    values = {vm["value"]: vm["meaning"] for vm in a200["value_meanings"]}
    assert values["0"] == "Fault"
    assert values["1"] == "Coast Stop"
    assert a200["default"] == "0"


def test_pf40_related_parameters_not_related_faults():
    a200 = _pf40_params()["A200"]
    # "Related Parameters: A201," wraps to a second line "A202, A203" — the
    # continuation extends related_parameters and never leaks into purpose.
    assert a200["related_parameters"] == ["A201", "A202", "A203"]
    assert a200["related_faults"] == []  # populated only by the fault->param link
    assert "A202" not in a200["purpose"]
    assert "A203" not in a200["purpose"]


def test_pf40_bold_header_gate_rejects_a_plain_helvetica_graph_callout():
    """A299 [Phantom Freq] is a plain-Helvetica curve callout — its line IS on
    the page (so it would pass cite-integrity), but it is not a real parameter
    and MUST be rejected by the bold-header gate (the real PF40 p.71 A034 typo).
    """
    params = _pf40_params()
    assert "A299" not in params
    # ...but the callout text really is on the page — proving the GATE (not
    # cite-integrity) is what dropped it.
    page5_text = dict(extractor.read_pages(FIXTURE))[5]
    assert "A299" in page5_text
    assert "Phantom Freq" in page5_text


def test_pf40_fault_page_fed_to_the_param_parser_yields_nothing():
    assert extractor.parse_parameters(FIXTURE, pages=_PF40_FAULT_PAGES) == []


def test_pf40_end_to_end_extract_links_fault_to_parameter_and_verifies_cites():
    """End-to-end on the PF40 pages: F9 -> A205 would link if A205 were in the
    param pages; here A200/A201 are, and every emitted PF40 entry cite-verifies."""
    fragment = extractor.extract(
        FIXTURE,
        doc="pf_sample.pdf (synthetic)",
        fault_pages=_PF40_FAULT_PAGES,
        param_pages=_PF40_PARAM_PAGES,
    )
    # single-digit codes reached the fault map
    assert fragment["fault_codes"][2] == "Input Fault"
    assert fragment["fault_codes"][9] == "Net Fault"
    # the graph callout never became a parameter
    assert "A299" not in {p["parameter_id"] for p in fragment["parameters"]}
    # every emitted citation verifies verbatim on its page
    for citation in fragment["fault_citations"]:
        assert cite_integrity.verify_excerpt_on_page(
            FIXTURE, int(citation["page"]), citation["excerpt"]
        )
    for param in fragment["parameters"]:
        sc = param["source_citation"]
        assert cite_integrity.verify_excerpt_on_page(FIXTURE, int(sc["page"]), sc["excerpt"])
