"""Inline-button callback handler for daily content drafts.

Wired in `bot.py` as a CallbackQueryHandler with pattern `^(approve_all|approve_blog|reject):`.
Buttons are generated by `mira-seo/mira_seo/tools/telegram_notifier.py`.
"""

from __future__ import annotations

import logging

from celery_client import send_task
from shared.tenant.authorizer import Authorizer
from telegram import Update
from telegram.ext import ContextTypes

logger = logging.getLogger("mira-bot.content-approval")

_PUBLISH_TASK = "mira_seo.tasks.daily_content.publish_approved"


async def handle_approval_callback(
    update: Update,
    context: ContextTypes.DEFAULT_TYPE,
    *,
    auth: Authorizer,
) -> None:
    """Route approve_all / approve_blog / reject callback to mira-seo Celery task."""
    query = update.callback_query
    if query is None or query.data is None:
        return
    await query.answer()

    user_id = query.from_user.id if query.from_user else 0
    if not auth.is_admin(user_id):
        logger.warning("APPROVAL_REFUSED non-admin from=%s data=%s", user_id, query.data)
        try:
            await query.edit_message_text("Admins only.")
        except Exception:
            pass
        return

    try:
        action, draft_id = query.data.rsplit(":", 1)
    except ValueError:
        logger.warning("Malformed callback_data=%s", query.data)
        return

    if action == "reject":
        task_id = send_task(_PUBLISH_TASK, draft_id, reject=True)
        status_text = "❌ Rejected. Draft archived." if task_id else "❌ Rejected (task dispatch failed)."
    elif action in ("approve_all", "approve_blog"):
        task_id = send_task(_PUBLISH_TASK, draft_id)
        status_text = (
            "✅ Publishing… I'll confirm when live."
            if task_id
            else "⚠️ Approved but task dispatch failed — check Redis."
        )
    else:
        logger.warning("Unknown approval action=%s draft_id=%s", action, draft_id)
        return

    logger.info("APPROVAL action=%s draft=%s user=%s task_id=%s", action, draft_id, user_id, task_id)
    try:
        await query.edit_message_text(status_text)
    except Exception:
        logger.exception("Failed to edit approval message")
